### ISSUE TITLE
Missing @private_scope on ParticipatoryProcessSerializer

### ISSUE THREAD

**Issue by moustachu** [OpenSourcePolitics/decidim#1046]
**Describe the bug**
Participatory processes are no longer exported and raising an error related to the `private_cope` parameter.

This is probably related to the commit 7e32803 and was never detected before.
😉 @Quentinchampenois 

**To Reproduce**
1. Go to https://pink.osp.cat/admin/participatory_processes
2. Click on the 'Export' icon
3. Go to the `production.log` on the server

**Expected behavior**
An export of the participatory process

**Stacktrace**
```
E, [2020-09-24T14:11:16.747403 #12307] ERROR -- : [ActiveJob] [Decidim::ExportParticipatorySpaceJob] [190d590b-3a1d-46bc-9834-8542e57ebd88] Error performing Decidim::ExportParticipatorySpaceJob (Job ID: 190d590b-3a1d-46bc-9834-8542e57ebd88) from Sidekiq(default) in 17.74ms: ArgumentError (wrong number of arguments (given 2, expected 1)):
/home/mako/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/bundler/gems/decidim-0917591dd860/decidim-participatory_processes/app/serializers/decidim/participatory_processes/participatory_process_serializer.rb:13:in `initialize'
/home/mako/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/bundler/gems/decidim-0917591dd860/decidim-core/lib/decidim/exporters/json.rb:16:in `new'
```

**Comment by Quentinchampenois** [comment]
hi @moustachu,

Nice catch, I apologize I did not notice this bug. You are right, I should have update every serializer that implements `initialize` method 

Update `decidim-participatory_processes/app/serializers/decidim/participatory_processes/participatory_process_serializer.rb` with : 

```
      # Public: Initializes the serializer with a participatory_process.
      def initialize(participatory_process, private_scope = false)
        @participatory_process = participatory_process
        @private_scope = private_scope
      end
```
should fix this issue. 

I can do it if you want because I have to update every serializer to avoid futur issues

**Comment by moustachu** [comment]
I was trying to fix it for just this one , thinking that it was a custom one for our 0.18 version and that it was fixed in later release on the BCN version ( > 0.22.0).
We'll talk later if there is other serializer to fix.
