### ISSUE TITLE
Admin logs broken because of i18n Proposals

### ISSUE THREAD

**Issue by moustachu** [OpenSourcePolitics/decidim#1048]
**Describe the bug**
Admin dashboard cannot be access due to the migration of the i18n Proposals

The branch [`feature/maximum-number-of-vote-per-project`](https://github.com/OpenSourcePolitics/decidim/tree/feature/maximum-number-of-vote-per-project) probably need a merge for the latest 0.23.dev commits, especially PR [#6518](https://github.com/decidim/decidim/pull/6518)

⚠️ 🚨  Beware of the last 0.23.dev issues with the core Rails library (SegFault drama)

**To Reproduce**
1. Go to https://ecrivons.angers.fr/admin/
2. See error

**Stacktrace**
```
ActionView::Template::Error
undefined method `gsub' for {"fr"=>"Des composteurs collectifs nouvelle génération"}:ActiveSupport::HashWithIndifferentAccess
```
see https://sentry.io/organizations/open-source-politics/issues/1918290949

**Additional context**
The Admin dashboard view has been patched on the deployment app (https://github.com/OpenSourcePolitics/osp-app/tree/bump_develop/alt/angers) to hide the admin logs. See OVERRIDES list to delete to concerned file

**Comment by moustachu** [comment]
since I patched the Admin dashboard view, you can't see the error but you have the Sentry stack trace

**Comment by paulinebessoles** [comment]
You can also see it here if you need : https://ecrivons.angers.fr/admin/logs. 
(Not a call for a patch 😁)
