### ISSUE TITLE
On Nancy some official proposals don't appear in FO

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#105]
https://nancy.opensourcepolitics.eu/processes/nancyentransition/f/8/
There is only one proposal displayed

https://nancy.opensourcepolitics.eu/admin/participatory_processes/nancyentransition/components/8/manage/
But there are 4 official proposals that were created (even if the badge says there is only 1 proposal)
![capture d ecran 2018-05-28 a 18 07 22](https://user-images.githubusercontent.com/29771726/40622648-e7eaf16a-62a2-11e8-9bf1-f728c821380e.png)

Impossible to reproduce this locally :/

**Comment by moustachu** [comment]
**Postponed (or to be closed) for now** 

--> with a fresh copy (duplicate) of the participatory process (with steps & components), there **don't** seems to be a filtering problem. 

My best guess could be some issues with the upstream moderation being enabled / disabled when testing ...
