### ISSUE TITLE
Add status tags for the comment moderation

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#11]
# This is a Feature Proposal

#### :tophat: Description

Context : 
Ludivine has been working on moderations adding the possibility to moderate content a priori for proposals and comments (on all comment objects on the app : meetings, results, etc.). On the Decidim core it is only possible to moderate a posteriori, meaning after a comment / proposal was published and signaled. A priori moderation means that moderators and admins can review what's being published before hand and decide to publish it or not. Here is the spec that was given to Ludivine
![user flow](https://user-images.githubusercontent.com/11473995/34524542-33af5cfe-f09c-11e7-8a53-1893c8c3bddc.png)

Admin and moderator can see content that is not visible to normal users so they can checkout what they moderate.

The problem we had is that when moderating comments, it's not easy for admins and moderators to see the effect of their moderation work as everything was displayed (included content that were moderated and don't display for normal users). So to see the effect you had to log off and load the page as a normal user.

For proposals we just filtered the list of proposals to only show those which where tagged as OK to display.

For comments @ludivinecp told me it might be complicated to filter them to only show those which were tagged as OK to display. 
>Maybe if you could quickly explain why

We came up with this solution of displaying tags next to comments to specify the status of the comment to help admin and moderators distinguish them. Here is a little mockup we did.
![](https://trello-attachments.s3.amazonaws.com/59a418193cf8ea0aabc1e0e4/5a429064a2cba79083e87061/56a226f485e9dccb2361de1ff2f80ce8/moderations-tags.png)

Ludivine suggested that @netbe could try to work on this as the comment system on decidim uses react and he is familiar with that technology.

**Comment by armandfardeau** [comment]
@virgile-dev Is this issue still pertinent or may we close it ?
