### ISSUE TITLE
"No method error eid_verified?" on Bosa

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#111]
![capture d ecran 2018-06-06 a 17 36 01](https://user-images.githubusercontent.com/29771726/41051127-8751ff82-69b5-11e8-9998-73a8ba8fb164.png)

**Comment by armandfardeau** [comment]
@juliesimon Is this issue still pertinent or may we close it ?

**Comment by juliesimon** [comment]
@armandfardeau the bug might be still here on the staging platform but is not consistent. We put this here for documentarion matters but we did not planned to fix it for now.
