### ISSUE TITLE
Display logo in emails

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#112]
Branch decidim: [0.10-stable](https://github.com/OpenSourcePolitics/decidim/tree/alt/0.10-stable)
Branch osp-app: [alt/CD44-0.10-stable](https://github.com/OpenSourcePolitics/osp-app/tree/alt/CD44-0.10-stable)

Logo is here on the platform: 
![capture d ecran 2018-06-08 a 11 14 28](https://user-images.githubusercontent.com/29771726/41149962-29f58abc-6b0d-11e8-8704-c44ae1099c6c.png)

But not in the emails:
![capture d ecran 2018-06-08 a 11 14 17](https://user-images.githubusercontent.com/29771726/41149974-31cd387a-6b0d-11e8-85d0-06a3568938d6.png)

**Comment by moustachu** [comment]
# ✅ 

![image](https://user-images.githubusercontent.com/464350/41167231-9dfc8fe8-6b42-11e8-822c-2cd5d89f0939.png)
