### ISSUE TITLE
Time is not GMT+1 on the platform

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#113]
Probably a server configuration, because for now, when someone leaves a message at 15:00, time on the platforme says 14:00

**Comment by moustachu** [comment]
The correct way to set this is by adding 

```
    config.time_zone = "Paris"
```

to the `config/application.rb` file in your deployment app 
like : https://github.com/OpenSourcePolitics/osp-app/blob/0.12-stable/config/application.rb#L13

**BTW**
it's definitly on the app level so if neede, it needs to be reopen on osp-app
