### ISSUE TITLE
Bad resolution on profile pics

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#119]
Might come from us or be sent to Barcelona: my profile pic which is ok on my account configuration page is really shitty on my profile page! 

![screenshot-2018-6-25 demo decidim osp](https://user-images.githubusercontent.com/10398564/41864067-f2c901aa-78a8-11e8-8921-19c0f2037f6e.png)

<img width="1185" alt="capture d ecran 2018-06-25 a 18 52 55" src="https://user-images.githubusercontent.com/10398564/41864093-046d8840-78a9-11e8-8151-a4831013430b.png">

**Comment by virgile-dev** [comment]
This is being fixed here : https://github.com/decidim/decidim/pull/3716
