### ISSUE TITLE
Make OSP signature more shinny :)

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#121]
Not urgent at all, but: on Decidim's footer, "Open Source Politics" & "logiciel libre Decidim" are in dark grey, not really readable... whereas the rest of the line is white. Perhaps should we change for the opposite, or simply write OSP and Decidim in a lighter tone. 

<img width="1256" alt="capture d ecran 2018-07-04 a 14 53 09" src="https://user-images.githubusercontent.com/10398564/42278324-bb72678e-7f9a-11e8-9b6b-f1c84b755a6c.png">

**Comment by armandfardeau** [comment]
As discussed with @valentinchaput : 

On footer, switch text color from grey to white and white to grey
