### ISSUE TITLE
Doc on putting decidim on production

### ISSUE THREAD

**Issue by armandfardeau** [OpenSourcePolitics/decidim#125]
# This is an enhancement proposal

#### :tophat: Description

There is very little documentation on Decidim concerning the platform's deployment in production. As this is a need of Barcelonians, it might be interesting to constitute documentation on the subject while keeping their needs in mind.

This can be concomitant with the implementation of a Docker production architecture.

#### :pushpin: Related issues
* https://github.com/decidim/decidim/issues/3702

**Comment by armandfardeau** [comment]
I found this : https://github.com/Platoniq/decidim-install

@moustachu What do you think about it?

**Comment by CivicTechFR** [comment]
@moustachu <https://github.com/moustachu> va bien aimer les passages sur le débugage du mailer.

Olivier.
