### ISSUE TITLE
0 commentaires with an "s"

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#131]
<img width="1069" alt="capture d ecran 2018-07-10 a 10 59 07" src="https://user-images.githubusercontent.com/29771726/42499973-6852b0be-8430-11e8-8c61-35a8a892b90c.png">

There's an "s" in the end of " 0 commentaire" when there should not be !

Tested on `osp-app#alt/elogie` pointing to `decidim#0.12-stable-updated`

**Comment by juliesimon** [comment]
@moustachu seems like we still have the comment issue on demo !
- I posted a comment that I moderated but the two comment counters under the titles still says "2 comments"
- there's still an "s" in "1 commentaires"
https://demo.decidim.opensourcepolitics.eu/processes/modules-decidim/f/9/posts/1

![screenshot_2018-07-12 un nouveau lieu pour les riders - actualites - presentation des fonctionnalites - demo decidim osp](https://user-images.githubusercontent.com/29771726/42634836-a29d599e-85e4-11e8-92a7-af179069f0cc.png)

**Comment by juliesimon** [comment]
@armand could you please take a look at this issue ?
Only my last comment.

**Comment by armandfardeau** [comment]
@juliesimon Will investigate

**Comment by armandfardeau** [comment]
Can't reproduce : 
![image](https://user-images.githubusercontent.com/20232956/43635741-4723e50a-9710-11e8-8676-a513f5d3d31c.png)
![image](https://user-images.githubusercontent.com/20232956/43635639-fe0813be-970f-11e8-9024-3a2253b8f22c.png)
![image](https://user-images.githubusercontent.com/20232956/43635679-125bb1d6-9710-11e8-84c9-000a5da7adf6.png)

**Comment by armandfardeau** [comment]
We need further investigation, I could be useful to have a db dump to check.

**Comment by juliesimon** [comment]
@armandfardeau I think you dodn't reproduce it well. This was a test on the "actualités" component. Steps to reproduce:

- Create 2 comments on a blog post
- Moderate and hide one of the comments (click on the flag on the comment > then admin BO > name of process > moderation > hide the flagged comment)
- Problem is where I've put the three red squares on the image below:
![42634836-a29d599e-85e4-11e8-92a7-af179069f0cc](https://user-images.githubusercontent.com/29771726/43636151-91d5996c-9711-11e8-9309-8f468f117c59.png)

**Comment by juliesimon** [comment]
@armandfardeau as you can see the number of commentaires is not ok:
- on the right of the title of the post
- under the title of the post on the "Articles les plus commentés" section

Please see the image in my latest comment and look at what is in red !!

**Comment by armandfardeau** [comment]
@juliesimon The problem come from the comments part of the author cell, which return the comments count. The issue is that it return all comments, not only comments which are not moderated.

I'm looking for a solution.
