### ISSUE TITLE
Issues with the redesign of our voting buttons

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#132]
Four months ago, Ludivine created for/neutral/against voting buttons on proposals with thumbs up and down. 

<img width="419" alt="capture d ecran 2018-07-10 a 23 42 38" src="https://user-images.githubusercontent.com/10398564/42539272-f5ddd322-849a-11e8-8ac3-3a4dc8dab80e.png">
 
While enhancing this development with the 0.12 version, Alain has come with a redesign. Main evolution is the wider separation of the three buttons, which works well on proposals' detailed page

<img width="282" alt="capture d ecran 2018-07-10 a 23 39 44" src="https://user-images.githubusercontent.com/10398564/42539401-5591feec-849b-11e8-9488-96ef921016ce.png">

... but not so well on the proposals' index. To me, the top 3 main issues are :
1) the inconsistent margin at the bottom of the card, which is already very big on Decidim;
2) buttons appear very narrow/too tall/too round compared to other Decidim components;
3) I guess the button will widen if the counter reaches 2 or 3 digits with 10+ or 100+ votes... then it won't share the same width with the other 2 buttons.

<img width="863" alt="capture d ecran 2018-07-10 a 23 39" src="https://user-images.githubusercontent.com/10398564/42539508-91bad4de-849b-11e8-8148-2ad2630ea3c3.png">

My suggestion would be to come closer to what appears on a proposal's page, i.e. a wider section of 3 buttons with no bottom space. 

_For further and more important redesign operations on the platform, I think we should have a validation process before it is implemented in production_

Allez les Bleus !

**Comment by valentinchaput** [comment]
@juliesimon did you or Alain change anything on this?

**Comment by juliesimon** [comment]
@valentinchaput it's back to the first design
https://steamroll.osp.cat/processes/eveniet-et/f/62/

**Comment by valentinchaput** [comment]
top!

**Comment by valentinchaput** [comment]
I'm curious about these buttons on https://demo.decidim.opensourcepolitics.eu/processes/projet-terrain-de-basket/f/39/

<img width="427" alt="capture d ecran 2018-09-09 a 10 50 28" src="https://user-images.githubusercontent.com/10398564/45262794-340bb080-b41e-11e8-9b66-3c6523f6985a.png">

- not the previous design we agreed on
- no counter on the buttons
- no change showing what you have already voted

Why did this design come back on the demo?

We shall have the design that was made for Nouvelle-Aquitaine here (and discuss its improvement).
Thanks !
