### ISSUE TITLE
Cannot do any action on a debate

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#136]
We cannot update or delete a debate from the backoffice : seems like all the buttons to do any action have disappeared...
You can only see the debate when clicking on its title.
https://demo.decidim.opensourcepolitics.eu/admin/participatory_processes/modules-decidim/components/7/manage/
![capture d ecran 2018-07-17 a 18 58 46](https://user-images.githubusercontent.com/29771726/42833134-9b62ea14-89f3-11e8-9b90-5b59db57e72d.png)

**Comment by moustachu** [comment]
@juliesimon don't why a simple debug print is fixing this one ... let's put that on hold for later
