### ISSUE TITLE
Address not found on here.com

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#139]
From CD44:
"sur la localisation des rencontres : nous avons fait faire une contribution sur openstreetmap pour avoir une adresse pour le [port de pêche de la Turballe](https://www.openstreetmap.org/search?query=port%20de%20p%C3%AAche%20de%20la%20turballe#map=18/47.34772/-2.51355) hier (== il y a une semaine), mais notre atelier n’est toujours pas bien localisé : https://cerise.osp.cat/processes/porturballe/f/78/meetings/42 (il est rue du port à la place) : est-ce que le service qui sert pour la localisation possède un cache qui met du temps à intégrer les nouvelles adresses ?"

==> L'adresse apparait bien sur open street map mais n'est pas trouvée sur decidim

**Comment by moustachu** [comment]
### Actual
- "port de pêche de la Turballe" is miss placed on here.com
- We don't know how to feed back to them that info (and we need a sustainable solution)
- We don't know if and when Here.com fetch OSM changes (the address has been added to OSM)

### Informations 
- [Geocoding Services List for Rails Geocoder](https://github.com/alexreisner/geocoder/blob/master/README_API_GUIDE.md)
- 

### Requirements
- part of `0.12-stable` common branch
- Service(s) need to be configurable by deployment (in `config/decidim.rb`)

### Options (not exclusive)

1. Change to `:nominatim` (OSM) **only**
    - but we need to double check to cache settings to make sure API calls are limited (to prevent IP ban)
2. Set multiple geocoding services to be executed in sequence in case of failure
    - **will not prevent miss placed results**
3. Set multiple geocoding services and add the ability to select it with the address input
    - if we go this way, users might ask to have direct access to check the results with a map preview (could be a external link to service map like openstreetmap.com)
4. Add the Latitude and Longitude fields aside the address field to bypass geocoding

> Notes : 
> it seems that "port de pêche de la Turballe" is also miss placed in https://adresse.data.gouv.fr/api/ (to be double check). So `:ban_data_gouv_fr` cannot be used as a standalone service (it needs to have a fallback service)

**--> Need definition** @juliesimon @virgile-dev

**Comment by juliesimon** [comment]
The idea is to:

**1/ Change here.com to Open Street Map**
- We deploy a Decidim instance with OSM
- We test it
- If ok, we'll use that for everyone (with a process on how to do when an adress is missing : who does the contribution on OSM ?)
- Else, we might consider using gmaps

**2/ Add the possibility to add a place with latitude & longitude**
--> _TO BE DESIGNED_
- Where : add an address for a proposal, for a meeting, for a project
- So far, until you validate your proposal/meeting/project, you cannot see where it will be located. There should be some kind of preview of the adress that was entered by the user and if not ok, you click on a link that shows a hidden field with latitude and longitude. Should it be a pop-up window?

@moustachu @virgile-dev @armandfardeau are you ok for 1/ ?
And 2/ can be Armand's mission for the summer after we validate the specs.

**Comment by armandfardeau** [comment]
@juliesimon How do you want to function? Should we vote on each proposal?

**Comment by juliesimon** [comment]
1/ and 2/ are not really choices but more like steps. 

We all agreed on the fact that we need to change our geocoding service (at least that's what I understood from our meeting yesterday) so 1/ is mandatory, but feel free to comment on it and say if you think it's the right way to do !

2/ is something that we'll do but it needs some design first
