### ISSUE TITLE
Impossible to add a question to a survey on CD44

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#140]
https://cerise.osp.cat/admin/participatory_processes/processus-test/components/82/manage/

When clicking on "Ajouter une question", it only prints "survey-question-tmpl"

![capture d ecran 2018-07-24 a 18 37 38](https://user-images.githubusercontent.com/29771726/43153343-5777472c-8f71-11e8-89a4-764602ae4370.png)

I get this problem only on Cerise, working fine on dev

**Comment by moustachu** [comment]
@Julie Fixed 🔧 ! 

Something to do with old assets still present on the server ...
