### ISSUE TITLE
Layout issue on accountability

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#143]
See here: https://demo.decidim.opensourcepolitics.eu/processes/modules-decidim/f/6/results/3

<img width="1244" alt="capture d ecran 2018-07-25 a 14 48 34" src="https://user-images.githubusercontent.com/29771726/43202990-46b3655e-901d-11e8-95c9-748970d47db6.png">

Problem should come from `decidim-accountability/app/views/decidim/accountability/results/_show_leaf.html.erb`, line 29:
`<div class="columns mediumlarge-9 mediumlarge-pull-3">`should be `<div class="small-12 mediumlarge-8 large-9 columns">`

This solution works when you modify it in the browser inspector but cannot test locally since I don't manage to configure a result to make this `div` appear :thinking:

Tested on branch `0.12-stable`

**Comment by juliesimon** [comment]
@armandfardeau can you post an update about this one ?

**Comment by armandfardeau** [comment]
@juliesimon Actually I can't reproduce this issue.
![image](https://user-images.githubusercontent.com/20232956/43586906-280ae184-9669-11e8-8e47-83796997c80c.png)

Have you been able to reproduce?

**Comment by juliesimon** [comment]
Me neither, maybe try to recrete the "messy" accountability feature on demo
?

2018-08-02 15:32 GMT+02:00 Armand Fardeau <notifications@github.com>:

**Comment by armandfardeau** [comment]
@juliesimon 
I add that for a quick and dirty fix
```
<style>
.accountability .mediumlarge-pull-3 {
  left: initial !important;
}
</style>
```
As I'm not able to reproduce, I'm assuming that this issue is restricted to the this instance perimeter.

**Comment by juliesimon** [comment]
@armandfardeau ok seems fixed, we'll see if the problem reappears somewhere

**Comment by lu-hamani** [comment]
@armandfardeau 
This one reappeared on RIVP platform. See the problem here : 
https://budget-participatif.rivp.fr/processes/stalingrad-riquet/f/62/results/13

**Comment by moustachu** [comment]
Dirty fix applied on https://budget-participatif.rivp.fr (header snippets)

But this need to fix globally in the file 
https://github.com/OpenSourcePolitics/decidim/blob/0.16-stable/decidim-accountability/app/views/decidim/accountability/results/_show_leaf.html.erb#L29

( probably remove the `mediumlarge-pull-3` )
