### ISSUE TITLE
Impossible to create a result on steamroll

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#146]
I'm in the backoffice, component "Accountability", I try to create a result and get a server error:
<img width="1552" alt="capture d ecran 2018-07-26 a 15 41 21" src="https://user-images.githubusercontent.com/29771726/43265999-86db4962-90ea-11e8-99d7-d0bd3b424015.png">
https://steamroll.osp.cat/admin/participatory_processes/eveniet-et/components/64/manage/results

**Comment by lu-hamani** [comment]
@armandfardeau 
Can we assume that we face the same issue as #279 ?

**Comment by armandfardeau** [comment]
> @armandfardeau
> Can we assume that we face the same issue as #279 ?

As surprising as it gets, no ! 
this is the issue : ActiveModel::UnknownAttributeError (unknown attribute 'external_id' for Decidim::Accountability::Result.):

**Comment by moustachu** [comment]
@lu-hamani Can't seem to reproduce this one on the given URL : 
https://steamroll.osp.cat/admin/participatory_processes/eveniet-et/components/64/manage/results
Component was deleted ... 

Any idea how to reproduce ?

**Comment by lu-hamani** [comment]
@moustachu 
Try to create a result here
https://steamroll.osp.cat/admin/participatory_processes/proposition/components/112/manage/

**Comment by lu-hamani** [comment]
Issue will be stale in a matter of days, weeks. Hence I close it.
