### ISSUE TITLE
Banner image not clear

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#148]
https://cerise.osp.cat/processes/portdelaturballe

Why is the banner image full of pixel ?

**Comment by armandfardeau** [comment]
The banner image resolution is 1000px / 200px.

Here the image is 2048 px X 550px. that mean once resized approximately 744 px width.

Maybe you could try with a lower image or with a larger one (2750 px width / 550px is perfect).

**Comment by armandfardeau** [comment]
@juliesimon Have a look at #150

**Comment by armandfardeau** [comment]
💯 How to update already existing images?
Open your rails console
rails c
paste the following :
Decidim::ParticipatoryProcess.find_each { |process| process.banner_image.recreate_versions! if process.banner_image? }

⚠️ Always backup before ! ⚠️
