### ISSUE TITLE
Searchbar not working on demo

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#151]
I cannot find a user by its username 
https://demo.decidim.opensourcepolitics.eu/search?utf8=%E2%9C%93&term=julie here if i look for "julie" it's not working, whereas its working on https://meta.decidim.org/

**Comment by armandfardeau** [comment]
@juliesimon @moustachu 
Meta.decidim is actually in 0.14

Search on user has been introduced 21 days ago : 
https://github.com/decidim/decidim/commit/7a37e4d1b3b96c3c658e6da20ede76f7b3a497e9#diff-d4f3b9b4ed475ab25cd56575b36890ad

Two options: 
* Updating the 0.12 version but we will have some trouble upgrading
* Wait for barcelona and upgrade to 0.14
