### ISSUE TITLE
FR translation missing "Invite user" and "Reserved slot"

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#152]
Issue here : https://demo.decidim.opensourcepolitics.eu/admin/participatory_processes/modules-decidim/components/3/manage/meetings/1/registrations/edit

French translation for "Invite user" button and for "reserved slot" field are missing -> it should be "Inviter un utilisateur" et "Places réservées"

![capture d ecran 2018-07-30 a 11 21 36](https://user-images.githubusercontent.com/29771726/43388967-d418b824-93ea-11e8-966d-b41d2c776931.png)

**Comment by armandfardeau** [comment]
To find missing : 
`bundle exec i18n-tasks missing`

To fix missign :
`bundle exec i18n-tasks add-missing`

**Comment by armandfardeau** [comment]
Should be fixed now, could you take a look?

**Comment by juliesimon** [comment]
@armandfardeau did this get resolved ? I remember yesterday we couldn't get the french translation for "reserved slots"

**Comment by armandfardeau** [comment]
@juliesimon 19 tests are still pending, but so far I think I managed to solve the "reserved slot issue"
