### ISSUE TITLE
Search bar is not centered on https://participation.lillemetropole.fr/

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#156]
Here on the MEL(https://participation.lillemetropole.fr/) you can see that the search bar is not centered on the top navbar when it is centered on the other platforms.

What went wrong ?
Thanks !

MEL:
![capture d ecran 2018-08-01 a 17 25 53](https://user-images.githubusercontent.com/29771726/43531540-4a13919a-95b0-11e8-825d-74d6b46ac71a.png)

Demo:
![capture d ecran 2018-08-01 a 17 28 22](https://user-images.githubusercontent.com/29771726/43531562-548ce2ac-95b0-11e8-968f-272d51eb1172.png)

**Comment by armandfardeau** [comment]
There is a missing class on input field.

![image](https://user-images.githubusercontent.com/20232956/43532172-c66999e6-95b1-11e8-8fff-dbfa27d3da36.png)

![image](https://user-images.githubusercontent.com/20232956/43532269-f740307a-95b1-11e8-8c4a-2b14c254efd2.png)


The missing class : 
```
.m-none {
    margin: 0;
}
```
