### ISSUE TITLE
Dynamically update images in forms

### ISSUE THREAD

**Issue by armandfardeau** [OpenSourcePolitics/decidim#157]
# This is a Feature Proposal

#### :tophat: Description

For feature proposals:
* US: As a user I want to have a preview of an image as I upload it.

Actually when an user upload an image, the previous image is still in the form until the form is submitted. 

![image](https://user-images.githubusercontent.com/20232956/43575130-506ddad2-9646-11e8-9828-bbe4c1f08e5d.png)

In case of mistake this can be confusing as the user need to re-upload the previous form if He/she still have it.

Something like this could be great : 
https://jsfiddle.net/stN8U/1/

Off course a flash notice could be added to inform the user that the file will be uploaded on submit.

What do you think? Let's vote with 👍 and 👎

**Comment by juliesimon** [comment]
@armandfardeau yes !
