### ISSUE TITLE
Navbar links

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#159]
Navbar links have proven to be useful for our clients to add entries in the secondary navbar. 
The use case is to put forward some page in Decidim. Angers and le Loiret use to showcase their participatory budget and more the generally in the industry client want to be able to have a custom navbar.

## Roadmap
- [ ] finish writing tests for the feature as it is: https://github.com/OpenSourcePolitics/decidim/pull/163
- [ ] send PR to decidim with a few thoughts on how we think that feature can evolve

A were a few ideas we discussed with @armandfardeau : 
- Display all navbar links (even default ones) and allow for admin to edit them
- As it might get crowded quite quickly let's think of adding making dropdown menus with a few entries by adding a parent attribute.

**Comment by armandfardeau** [comment]
Is it something that the user should customize?

**Comment by virgile-dev** [comment]
After discussing this with @armandfardeau I'm transforming this into EPIC.
