### ISSUE TITLE
On new profile notifications, dates must be translated to French

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#160]
On the new profile page notifications section (example https://ecrivons.angers.fr/profiles/mako/notifications), dates appear as "Wed 1" or "Mon 30". It should be translated into "Mercredi 1er / Lundi 30" (if we have enough space) or "Mer 1er / Lun 30"

<img width="867" alt="capture d ecran 2018-08-02 a 16 05 59" src="https://user-images.githubusercontent.com/10398564/43589176-77d39576-966e-11e8-9755-0942b3dc5f8f.png">

**Comment by valentinchaput** [comment]
Any update on this one?

**Comment by juliesimon** [comment]
Issue in decidim/decidim https://github.com/decidim/decidim/issues/3982
