### ISSUE TITLE
Double signature button on initiatives

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#162]
You may have noticed it already when creating the demo but 2 buttons appear on the right sidebar of an active initiative : the first one is to add your signature, the second one to inform you that you have given your signature. I guess the correct behaviour should be a toggle button that turns green when you sign.

<img width="1147" alt="capture d ecran 2018-08-03 a 11 06 50" src="https://user-images.githubusercontent.com/10398564/43634808-8b5bcb6e-970d-11e8-852f-2ab8c53e356d.png">

**Comment by armandfardeau** [comment]
Actually I can't reproduce @valentinchaput . 

![2018-08-14 15 36 50](https://user-images.githubusercontent.com/20232956/44094995-f62d13c6-9fd7-11e8-8459-3c593114f9d4.gif)


May you link the url where the problem is located?

@moustachu I suggest a demo.decidim update
