### ISSUE TITLE
[PR TO BARCELONA] Votes weight

### ISSUE THREAD

**Issue by armandfardeau** [OpenSourcePolitics/decidim#164]
Add a new vote features so that a user can vote for/against/neutral a proposal. The feature can be activated in the BO > participatory space > proposal component

Roadmap
- [ ] finish writing tests for the feature as it is
- [ ] send PR to decidim with a few thoughts on how we think that feature can evolve

**Comment by lu-hamani** [comment]
@armandfardeau 
Any news of BCN ?
