### ISSUE TITLE
Bug in address field makes it impossible to create meetings on OSP démo

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#165]
I remember we have experienced issues with meeting creation on early 0.12; might be the reason why any correct address is rejected. 

<img width="952" alt="capture d ecran 2018-08-03 a 14 58 34" src="https://user-images.githubusercontent.com/10398564/43644138-f3e76952-972d-11e8-816b-c0b103e6224f.png">

**Comment by armandfardeau** [comment]
I'm not able to reproduce, maybe demo in on an outdated version and should be upgraded.

![2018-08-06 11 47 39](https://user-images.githubusercontent.com/20232956/43709994-a1392284-996e-11e8-8253-280e81b0a257.gif)
![image](https://user-images.githubusercontent.com/20232956/43709982-9a3a1f74-996e-11e8-97b0-867aec7c0361.png)

**Comment by valentinchaput** [comment]
Probably, as that was also my guess. What is your opinion on this @juliesimon?

**Comment by juliesimon** [comment]
We add this problem several times. Once it was because of here.com not working properly. Another time was something that Alain fixed but I did not know what it was. 
So maybe updating demo might do the trick but can't say for sure :/

**Comment by armandfardeau** [comment]
@moustachu @juliesimon This looks like an error with an unregistered address. 

2 options: 

Set geocoding as a asynchronous job or use another provider than here.com

**Comment by lu-hamani** [comment]
@armandfardeau 
any occurrences of this bug since your last comment ?

**Comment by lu-hamani** [comment]
Bug isn't there no more (tests on steamroll and demo)

**Comment by lu-hamani** [comment]
Linked to geocoding requests to OSM. As @armandfardeau pointed out, asynchronous job or other provider.

**Comment by armandfardeau** [comment]
Seems outdated.
![image](https://user-images.githubusercontent.com/20232956/48713270-2473c980-ec10-11e8-9375-5ac5369aa52f.png)
