### ISSUE TITLE
You can still respond to a comment when comments are deactivated

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#167]
It happened this weekend on Loire Atlantique's platform: https://participer.loire-atlantique.fr/processes/route/f/58/proposals/160

The process is over, users cannot add proposals or comments at this stage, but if you are connected you can still respond to other comments. We don't know if it has always been the case or if it's new with the 0.12 version.

**Comment by valentinchaput** [comment]
Any clue on this one? I have a call tomorrow morning with the client :)

**Comment by juliesimon** [comment]
https://meta.decidim.org/processes/bug-report/f/210/proposals/13090
I also think that a user should not be able to reply to a comment if commenst are blocked.
Let's wait for a reply and if they decide not to do anything, we can see with @armandfardeau how to fix this.

**Comment by armandfardeau** [comment]
TODO : 

Check with Barcelona to see if it's a desired behaviour.

If not, see with them how to solve the issue.
If yes, implement a custom behaviour for our plateform : 

US : As an ADMIN I can CHOOSE if I want to BLOCK ANSWER TO COMMENTS when comments are disabled

**Comment by juliesimon** [comment]
Issue adressed here https://github.com/decidim/decidim/issues/4003
