### ISSUE TITLE
French translation keys

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#17]
- Changer "Assemblées" (car confusion avec l'Assemblée nationale) en "Initiatives" (même mot qu'en catalan ?) @valentinchaput vu que ya déjà un espace de participation qui s'appelle "Initiative" faut qu'on lui trouve un autre nom. Des idées ?
- Dans la section "Auteurs" des filtres des proposition, remplacer "Elu-e-s" par "Propositions officielles" et "Citoyens" par "Propositions citoyennes" 
- Dans le formulaire de signalement des propositions/commentaires, rajouter "homophobes" après sexistes (Traduction actuelle: "Contient des propos racistes, sexistes, des insultes, des attaques personnelles, des menaces de mort, des incitations au suicide ou toute forme de discours de haine."

**Comment by valentinchaput** [comment]
Les trads à modifier :

**Comment by virgile-dev** [comment]
Mes commentaires en citation ci-dessous :
Les trads à valider (@virgile-dev) et modifier (@ludivinecp) pour toutes les instances : 
- (dans la secondary navbar) Assemblées >> Agora
> Dans l'admin aussi et donc partout où c'est nécessaire.
- (dans les filtres) Retenues >> Retenue 
>Bizarre j'ai regardé sur Crowdin la trad confirmée est bien "Retenue" je ne sais pas pourquoi on a "Retenues" avec un s sur notre version du code.
- (dans l'admin > processus participatif > information) Announcement >> Message d'annonce
> Traduit sur Crowdin mais en anglais chez nous...
- (dans l'admin > processus participatif > information) Show statistics >> Afficher les statistiques
> Traduit sur Crowdin mais en anglais chez nous...
- (dans l'admin + dans le formulaire de dépôt de propositions) Has address >> Renseignez une adresse
>Je viens de faire la traduction sur Crowdin
- (dans l'admin > dans les rôles utilisateurs d'un processus participatif) Rédacteur >> Relecteur
> Trad faite dans Crowdin

J'en rajoute deux que tu m'as demandé : 
- Dans les options de filtres de la section "Auteurs : Elu-e-s >> Propositions officielles
- Dans les options de filtres de la section "Auteurs : Citoyens >> Propositions citoyennes
 

Sans doute spécifique à Angers : 
- (dans les zones d'application) : Portée globale >> Toute la ville
> A mettre sur le repo Angers si vraiment tu la veux. @valentinchaput

**Comment by valentinchaput** [comment]
Yes, je valide tout ça, y compris la spécifique Angers

**Comment by ludivinecp** [comment]
@virgile @valentin J'ai l'impression que Crowdin fou la pagaille dans les trads. Car en back la plupart des traductions sont bonnes. Par exemple "Retenues" j'ai bien "Retenue. Pareil pour "Announcement", "Show statistics"...

**Comment by virgile-dev** [comment]
J'ai l'impression que c'est la config de Josep qui a foutu le boxon. Il faudrait peut être qu'on fasse un call avec lui @ludivinecp 

J'en avais discuté avec lui ici : https://github.com/decidim/decidim/issues/1860

**Comment by virgile-dev** [comment]
@ludivinecp Je lui ai mis un petit message sur l'[issue](https://github.com/decidim/decidim/issues/1860) pour voir s'il est chaud qu'on se fasse un call pour voir si on peut réparer ensemble.

**Comment by juliesimon** [comment]
@ludivinecp @virgile-dev où en est on sur les traductions manquantes ? Car Angers en a besoin rapidement, notamment decidim-angers#8

**Comment by juliesimon** [comment]
Ainsi que me l'a expliqué @moustachu , pour les modifications de trad sans attendre que ça soit remonté sur Crowdin et mis à jour dans le code des barcelonnais, le mieux c'est d'overrider les clefs sur `OpenSourcePolitics/osp-app`, dans `fr.yml` (et non de faire les modifs directement dans ce repo pour ne pas avoir de conflits aux prochaines màj)
@ludivinecp  ça te semble ok comme manière de faire ?

Là mon défi c'est de réussir à savoir où on en est dans tous les besoins de modification de traduction, notamment si la checklist là dessus est à jour 🤞 
Et aussi de tenir à jour un fichier de [suivi des modifications de traduction](https://docs.google.com/spreadsheets/d/1AE4HTpfoNszUUBE938SxqoEdy4xT_3IoxxUO8DefU88/edit#gid=0)
Et pour tous les bugs, les trads qui ne passent pas, de trouver un moyen de suivre sa résolution du côté barcelonnais
