### ISSUE TITLE
The ranking choice on surveys should be made in drag and drop

### ISSUE THREAD

**Issue by armandfardeau** [OpenSourcePolitics/decidim#171]
# This is a  Feature Proposal

#### :tophat: Description
📖 As a **user** I want to **sort my anwsers** in order to **order choices in a survey**

* The ranking choice on surveys should be made in drag and drop
* Today it's done by selecting item in order which is UX unfriendly and confusing

#### :clipboard: Additional Data

Today behaviour : 
![2018-08-06 11 22 47](https://user-images.githubusercontent.com/20232956/43708599-1acd1e56-996b-11e8-84a5-31b3ce3aeb8d.gif)

Requested behaviour : 
![rails_sortable](https://user-images.githubusercontent.com/20232956/43709016-0d13b8a0-996c-11e8-93a0-6cd0e4943d98.gif)

**Comment by armandfardeau** [comment]
@valentinchaput May you confirm the feature request?

**Comment by valentinchaput** [comment]
Yep + there should also be a counter somewhere telling that Title9 is your first pick, and so on.

**Comment by armandfardeau** [comment]
So like today but instead of clicking on a choice, you just need to drag-and drop?

**Comment by valentinchaput** [comment]
Would be even better if the counter was not a simple text with the same style but a small button or something; we need to experiment on the design here!

**Comment by lu-hamani** [comment]
@armandfardeau 
Where are we on this one since there is a WIP label on this one => #181
