### ISSUE TITLE
Toggle on voting button is not working on alt/loiret

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#173]
Connected as an admin with mako
Here https://loiret.staging.opensourcepolitics.eu/processes/budget-participatif-des-parcs/f/14/ 
- I order the proposals from the most recent ones
- I vote for "Aigles dressés contre les chats errants" --> **Button does not change to "Déjà votée" when it should**
- I go to the show of the proposal here https://loiret.staging.opensourcepolitics.eu/processes/budget-participatif-des-parcs/f/14/proposals/17
- Button is "Déjà votée" in green , I unvote but **button does not toggle to "Voter" in red**
- If I refresh the page, button is "Voter" in red

Check should be done on all the other apps as well

**Comment by armandfardeau** [comment]
Has been bumped -> Should be solved now
