### ISSUE TITLE
Ability to order processes in the back-office

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#179]
Not urgent but a fix would be nice!

As noticed by a client, participatory processes seem randomly ordered (neither by date nor by alphabetical order) on the administration panel 
https://club.decidim.opensourcepolitics.eu/processes/new-components/f/95/proposals/208#proposal_208

An admin should be able to choose and display processes by date or alphabetical order.

Follow Barcelona decision : https://meta.decidim.org/processes/roadmap/f/122/proposals/13099

**Comment by armandfardeau** [comment]
We agreed with Valentin on integrating the same filter as proposals.

Title, created at, Published etc... and if POSSIBLE, to add a field to order highlighted processes first.
