### ISSUE TITLE
On demo when connected as a user, I can see an "Admin menu"

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#182]
When I'm connected as a user and I try to access the user menus on the right, I can see "Tableau de bord de l'administrateur". When I click on it, I get an error.
![capture d ecran 2018-08-10 a 11 17 14](https://user-images.githubusercontent.com/29771726/43949915-3670bb3c-9c8f-11e8-847f-14d7e54946d6.png)

There should not be an admin menu here.

Maybe we just need to update the decidim version on demo !

**Comment by armandfardeau** [comment]
> @armandfardeau
> I feel like this is a pattern => #297 , #146 , #279

What's make you think this is a pattern?

**Comment by armandfardeau** [comment]
@lu-hamani Not reproductible, closing.

![image](https://user-images.githubusercontent.com/20232956/49032829-dfbad600-f1ad-11e8-86ef-f1bd3b00961e.png)
