### ISSUE TITLE
"Star" label near an organisation is missing on demo

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#183]
When registering as an organisation, there should be a star near the name like here:
![capture d ecran 2018-08-10 a 11 45 46](https://user-images.githubusercontent.com/29771726/43951384-4db44cf6-9c93-11e8-8a82-483e5a493fc9.png)

On demo, there's no star https://demo.decidim.opensourcepolitics.eu/processes/modules-decidim/f/2/proposals/16:
![capture d ecran 2018-08-10 a 11 45 28](https://user-images.githubusercontent.com/29771726/43951325-2689a63a-9c93-11e8-80c9-ee7133a3ec3d.png)

**Comment by armandfardeau** [comment]
![image](https://user-images.githubusercontent.com/20232956/49034723-07f90380-f1b3-11e8-9c2c-1e8841bdf152.png)
