### ISSUE TITLE
Use time ago instead of date

### ISSUE THREAD

**Issue by armandfardeau** [OpenSourcePolitics/decidim#185]
**Feature proposals**
Decidim notifications use a system of date (e.g. Mon 13, Tue 22). 
As a user I want to know since when a notification has been emitted.

**Describe the solution you'd like**
I suggest that we use [Time ago](https://timeago.yarp.com/)
![2018-08-16 11 14 11](https://user-images.githubusercontent.com/20232956/44199895-976b3100-a145-11e8-8c09-de55e002e44d.gif)

**Describe alternatives you've considered**
For a pure js alternative we could use [timeago.js](https://github.com/hustcc/timeago.js/blob/master/README.md)

**Additional context**
This feature proposal is related to #160 

**Does this issue could impact on users private data?**
no

**Comment by lu-hamani** [comment]
@armandfardeau 
How are we on the BCN decision ?
