### ISSUE TITLE
Enhancement on navbar links

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#19]
Navbar links first version was done based on this https://github.com/OpenSourcePolitics/decidim/issues/3 for spec

Is left to do :
- [x] Application should check that the url entered by the user is valid (check existing regex url check ex : https://stackoverflow.com/questions/7167895/rails-whats-a-good-way-to-validate-links-urls)
- [x] Set title field as obligatory (should add a star next to field label)
- [x] Labels for _Title_ and _Link_  fields display in English, make translations in French
![Capture d’écran 2018-01-11 à 12.08.49.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a4cd03330957c0012d7570d/125516c66e82c728ace21e0d46cb958a379791accfed3da35d585c752a54267d6956f37a28c8b379f2132a410ea3febc405a4144f4e78d22b4aa2e30c80351b882294d7ed43840a8ebd61ebf09e921d81cd1b3bc8a4fc9be3c2de1dd8a5d220c4749d7ab0268f9d31e8a4afc59e04a5fa5163766e0703e75439d177524792a.png)
- [x] Be able to choose the order of display for links. Check what is being done for activated features on a participatory process. updated mockups @bastienrobert
![Group 3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a4cd03330957c0012d7570d/125516c66e82c728ace21e0d46cf86953692c3facda5fd53b652fa912a5265296b51a27f7381b278e7412a020c0b4bac415b5612fdf18f7da3a42062c80d55b98e30063e937f03a6aa8318b500bf218e4880b6b88a44c3e93f37aa.png)
![Group 4.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a4cd03330957c0012d7570d/125516c66e82c728ace21e0d46cf86953692c3fdcda5fd53b652fa912a5265296b51a27f7381b278e7412a020c0b4bac415b5612fdf18f7da3a42062c80d55b98e30063e937f03a6aa8317b500bf218e4880b6b88b44c5ee3537aa.png)

**Comment by bastienrobert** [comment]
@ludivinecp i've check the form and there's already a ReGex to validate the link
```
# frozen_string_literal: true

module Decidim
  module Admin
    # A form object to create or update scopes.
    class NavbarLinkForm < Form
      include TranslatableAttributes

      translatable_attribute :title, String
      attribute :link, String
      attribute :organization_id, Integer
      attribute :target, String

      validates :link, :format => { :with => URI::regexp(%w(http https)) }, presence: true
      validates :title, translatable_presence: true
      validates :organization_id, :link, presence: true

    end
  end
end
```

Do you want me to add other controls ?

**Comment by virgile-dev** [comment]
hey @bastienrobert just updated the issue with 2 small things that are left to do related to navlinks. Please have a look :)

**Comment by virgile-dev** [comment]
@bastienrobert just updated again !

**Comment by virgile-dev** [comment]
Yo @bastienrobert just talked to Ludivine about url form control. She told me that for the regex for the url form we are fine with checking http and https + that it's a valid url like you showed me yesterday. 

Please send a PR when you are done :). 

Also, for next time you can just create your branch on the /decidim repo in OpenSourcePolitics org since you are part of the Decidim Dev team :-)

**Comment by bastienrobert** [comment]
@virgile-dev @ludivinecp, do you think it's better to make the link RegEx on the controller or on the command side ?

**Comment by ludivinecp** [comment]
@bastienrobert  NavbarLink model should be the right place
