### ISSUE TITLE
Conditionnal appearance of hasthag in the process thumbnail card

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#193]
0.12 redesign of processes thumbnails include the hashtag in the card by default, even when there is no hashtag related to a process:
<img width="402" alt="capture d ecran 2018-08-21 a 14 31 23" src="https://user-images.githubusercontent.com/10398564/44407572-c6770d80-a55e-11e8-82ad-9353758eb920.png">

When clicking on the #, it redirect to a twitter error page...

Hashtags should only appear when the field is filled by the admin.

**Comment by armandfardeau** [comment]
@valentinchaput Submitted on Decidim Barcelona : https://github.com/decidim/decidim/issues/4023
