### ISSUE TITLE
There is no moderation on the Debate feature

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#194]
Quite an urgent issue we must submit to Barcelona!

As far as I remember, the Debate feature started as a clone of a former version of Proposals. Unfortunately, it is missing a lot of stuff: 
- you cannot edit a debate you created as a user (even for a short period of time as with proposals)
- you cannot flag a debate, neither as a user nor as an admin, and therefore you cannot moderate a debate, which presents a legal issue for our clients 
- you cannot delete a debate as an admin (the issue would be to be able to moderate it)

--
Less urgent is the fact that we do not have the tool to compare a new debate with the previous ones that are already published.

**Comment by armandfardeau** [comment]
Hi Valentin, I'm checking on your issue a this moment. It'd be great if you could split this issue in 3 parts :
- Edit/delete
- Moderation 
- Export

**Comment by virgile-dev** [comment]
Agree with @armandfardeau here let's try to make problem specific issue.

**Comment by virgile-dev** [comment]
Mention @armandfardeau
