### ISSUE TITLE
Modifier les états d'une proposition 

### ISSUE THREAD

**Issue by ludivinecp** [OpenSourcePolitics/decidim#2]
Actuellement, les administrateurs peuvent "répondre" à une proposition en lui accordant un statut "retenue/refusée/en cours d'évaluation". Il faudrait pouvoir ajouter un ou plusieurs statuts supplémentaires (ex d'Angers : recevable, non recevable, en cours d'évaluation, réalisable, non réalisable, soumis au vote...).

by @valentinchaput

**Comment by virgile-dev** [comment]
Comme les catégories et les zones d'application l'administrateur pourrait créer les status dont il a besoin. Si on met en place quelque chose comme ça ce sera utile pour tout le monde et pas juste pour Angers.

**Comment by virgile-dev** [comment]
Voilà les css utilisées pour les trois status existants
![proposal-status-css.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a4cd03330957c0012d7570d/125516c66e82c728ace21e0d46f88695338d90a883a4ac57a549e587644534606b48e13b628ae92dbc56395b4d5a1fa8120c5e44f4aa8878f5e239708a5f02bbd0655922c32f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e68e8f473f1603108eff5827ed.png)

**Comment by netbe** [comment]
Ok we got something simpler here's all the states:

STATES = %w(accepted rejected evaluating doable notdoable tovote)
Traductions: recevable, non recevable, en cours d'évaluation, réalisable, non réalisable, soumis au vote

I am missing the translations for answer,
I'll comment in the PR for that

**Comment by virgile-dev** [comment]
Cette proposition est recevable parce que :
Cette proposition est non recevable parce que :
Cette proposition est en cours d'évaluation :
Cette proposition a été jugée réalisable :
Cette proposition a été jugée non réalisable parce que :
Cette proposition est soumise au vote :

**Comment by netbe** [comment]
Deployed: https://osp-angers.herokuapp.com/ 
FIXME:
- [ ] Resolve: Message from application: uninitialized constant Decidim::Proposals::STATES (NameError)

**Comment by netbe** [comment]
Test it on https://osp-angers.herokuapp.com/processes/aut-aliquam/f/9/?locale=fr

**Comment by valentinchaput** [comment]
Most of the feature is very good. 

1/ Only missing point is the color of the description text on a proposition specific page.

Here is what we see for an accepted ("recevable") proposition: .callout success 
<img width="781" alt="capture d ecran 2018-01-09 a 12 46 05" src="https://user-images.githubusercontent.com/10398564/34719723-224f003c-f53c-11e7-8102-e1aab144bdef.png">

It does not appear on the new states (doable notdoable tovote)
<img width="762" alt="capture d ecran 2018-01-09 a 12 50 48" src="https://user-images.githubusercontent.com/10398564/34719829-90745170-f53c-11e7-8d82-89f2bb9986ec.png">

Could you fix this with the following?
-  doable: success
- notdoable: warning
- tovote: success

2/ Then I have a design issue: we can have a "resté sans réponse" label. We should rename it "Pas encore évaluée". As it is a default status, could we also make it appear in the filter?

Please ask if it is not clear enough.

**Comment by netbe** [comment]
@valentinchaput  seems clear, I'll ping you when it's change

**Comment by netbe** [comment]
@valentinchaput done and deployed!

**Comment by valentinchaput** [comment]
Sorry, I got confused with the colors. Can we change them to 
- rejected + notdoable = danger 
- "Pas encore évaluée" = warning
Should be more logical. Thanks!

**Comment by netbe** [comment]
@valentinchaput yeah, well there is no danger class:

See here:
https://github.com/OpenSourcePolitics/decidim/blob/master/decidim-core/app/assets/stylesheets/decidim/modules/_callout.scss#L13

And 

https://github.com/OpenSourcePolitics/decidim/blob/master/decidim-admin/app/assets/stylesheets/decidim/admin/modules/_typography.scss#L5

**Comment by virgile-dev** [comment]
@netbe You have a style guide for Decidim : 
http://decidim-design.herokuapp.com/pattern-library/

**Comment by valentinchaput** [comment]
@netbe did you find an explanation/solution on this strange switch to English when we select a status?
