### ISSUE TITLE
Drag and drop of images doesn't work anymore

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#220]
**Describe the bug**
Used to be an hidden feature. When drag and dropping an image in the admin text area the file was uploaded and displayed in the text area. You could even do that on an image from you desktop. Now it only works when the image is already hosted somewhere. Which forces our clients to create processes on their test organization just to host images. 

I know that this behaviour was really used by Valentin's clients too. 

**Expected behavior**
Drag and drop an image from my desktop should upload the file and display it in the text editor.

**Extra data (please complete the following information):**
 - Decidim Version: since version 0.12
 - Decidim installation: mel.osp.cat , demo.decidim.opensourcepolitics.eu

**Additional context**
I think the Decidim team would be open to accept a PR with a feature that help admins insert images in the text editor (it's an available fonctionnality on Quill.js).

**Comment by virgile-dev** [comment]
Linking this metadecidim proposal here : https://meta.decidim.org/processes/roadmap/f/122/proposals/12375

**Comment by valentinchaput** [comment]
Still working with Firefox. Example this week on https://budgetparticipatif.elogie-siemp.paris/processes/Jemmapes/f/22/
