### ISSUE TITLE
Add date of answer to survey serializer

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#226]
When exporting the answers to a survey component, it would be useful to have the date at which the user has answered the survey.

The export seems to be handled in `survey_user_answers_serializer.rb`

**Comment by armandfardeau** [comment]
@lu-hamani What do you think of it? Would you like to take a look in next days?

**Comment by lu-hamani** [comment]
@armandfardeau 
I took a look. It might be worthwhile as since the export is minimal as of today. To assess it's priority level, I have to talk about it with @valentinchaput and @virgile-dev  first.
