### ISSUE TITLE
Bad translation "private space"

### ISSUE THREAD

**Issue by leokante** [OpenSourcePolitics/decidim#231]
**Describe the bug**
bad translation. "Private space" is not translated when decidim is in French. It should be translated in "Espace privé"

**To Reproduce**
1. Go to https://demo.decidim.opensourcepolitics.eu/admin/participatory_processes/projet-terrain-de-basket/edit

**Screenshots**
![test decidim](https://user-images.githubusercontent.com/43004803/45097756-d4fb2280-b123-11e8-85f8-6246c8b3d314.JPG)

**Stacktrace**
If applicable, add the error stacktrace to help explain your problem.

**Extra data (please complete the following information):**
 - Device: Desktop
 - Device OS:  Windows 10
 - Browser: Firefox
 - Decidim Version: 0.12
 - Decidim installation: Demo OSP

**Additional context**

**Comment by leokante** [comment]
@juliesimon  please can you check that ?

**Comment by virgile-dev** [comment]
we'e got a lot of missing translation on the MEL instance. Will comment the ones I've spotted.
