### ISSUE TITLE
Modals are not working on mel.osp.cat

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#232]
**Describe the bug**
When you try to create a proposal while not loggued in, you should be prompted with modal to login, they are not loading on mel.osp.cat

**To Reproduce**
1. While not loggued in go to https://dev.mel.osp.cat/processes/test-geoloc/f/49/
2. Click on '+ nouvelle proposition'
3. Login modal not loading

**Expected behavior**
The login modal should load. Like on [Nancy's instance](https://participez.nancy.fr/processes/osonsnancy/f/20/). 
<img width="1114" alt="capture d ecran 2018-09-05 a 16 04 56" src="https://user-images.githubusercontent.com/11473995/45098550-82bb0100-b125-11e8-8a91-5fd34e66c836.png">

**Stacktrace**
If applicable, add the error stacktrace to help explain your problem.

**Extra data (please complete the following information):**
 - Device:  Desktop
 - Device OS: MacOS
 - Browser: Chrome
 - Decidim Version: [e.g. 0.12]
 - Decidim installation: MEL

**Comment by juliesimon** [comment]
<img width="1440" alt="capture d ecran 2018-09-05 a 16 13 27" src="https://user-images.githubusercontent.com/29771726/45099039-aaf72f80-b126-11e8-9160-dc27bef1d8bc.png">

**Comment by armandfardeau** [comment]
@virgile-dev Could you check? This seems not reproducible since update : 
![2018-09-07 11 06 04](https://user-images.githubusercontent.com/20232956/45209802-29221600-b28e-11e8-93cc-7b161e61b1ea.gif)

**Comment by virgile-dev** [comment]
Yup fixed. Closing.

**Comment by virgile-dev** [comment]
This wasn't fixed by the last deploy. @armandfardeau @moustachu 
Bug can be replicated on Firefox and Chrome.
Here is what the console log has to say : 
<img width="638" alt="capture d ecran 2018-09-17 a 12 08 05" src="https://user-images.githubusercontent.com/11473995/45617345-5337bd00-ba72-11e8-8863-ed2aefbece0f.png">

**Comment by virgile-dev** [comment]
This is linked to #264

**Comment by armandfardeau** [comment]
@lu-hamani Can't reproduce locally -> 
![image](https://user-images.githubusercontent.com/20232956/48718079-f778e400-ec1a-11e8-98af-1d9d28490544.png)

Will check on production tonight

**Comment by armandfardeau** [comment]
@moustachu I suggest a `bundle exec rake tmp:clear`
