### ISSUE TITLE
Withdrawn proposal that was never withdrawn

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#234]
Here https://ecrivons.angers.fr/processes/BP2018/f/30/proposals/212

This proposal was left by an admin of the platform and she knows for sure that she never withdrew it.
Since the last update, this proposal is marked as withdrawn, which is false.

Any idea why?

**Comment by armandfardeau** [comment]
@juliesimon Does this problem concerns only one proposal?  If only one, I suggest that we edit it and keep an eye open for new ones.

**Comment by juliesimon** [comment]
Yes just one, we can indeed update the proposal in the DB but it would be better to know where the problem comes from !
