### ISSUE TITLE
"Reserved slot" not translated

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#236]
**Describe the bug**
"Reserved slot" is not translated.

**To Reproduce**
1. Go to https://dev.mel.osp.cat/admin/participatory_processes/kebab-couture/components/79/manage/meetings/33/registrations/edit

**Expected behavior**
"Reserved slot" should be translated into "Places réservées"

**Screenshots**
<img width="1020" alt="capture d ecran 2018-09-05 a 18 16 41" src="https://user-images.githubusercontent.com/11473995/45108011-b43ec700-b13b-11e8-91df-ce69e7a9055e.png">

**Stacktrace**
If applicable, add the error stacktrace to help explain your problem.

**Extra data (please complete the following information):**
 - Decidim installation: dev.mel.osp.cat

**Additional context**

**Comment by armandfardeau** [comment]
This is not replicable on 0.12-stable 
![image](https://user-images.githubusercontent.com/20232956/45223363-533bfe00-b2b7-11e8-930d-a30f2248ab5f.png)
