### ISSUE TITLE
Translation missing on demo admin side

### ISSUE THREAD

**Issue by armandfardeau** [OpenSourcePolitics/decidim#240]
**Describe the bug**
After answering to an invitation on club.decidim, the  user.updated notice is missing

**To Reproduce**
1. Invite new admin user
2. Register user
3. See error on flash notice

**Expected behavior**
The appropriate translation

**Screenshots**
![image](https://user-images.githubusercontent.com/20232956/45145569-3e7d3e80-b1c1-11e8-8055-63b5d9f2dbfd.png)

**Comment by juliesimon** [comment]
Big news, now devise locales are imported in decidim so we can change them directly !
See https://github.com/decidim/decidim/issues/4096
