### ISSUE TITLE
Button "Modifier la proposition" appears when it shoudn't

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#241]
**Describe the bug**
User can modify proposals that they didn't author. The delay for proposal modification doesn't seem to matter.

**To Reproduce**
1. Go to https://club.decidim.opensourcepolitics.eu/processes/new-components/f/95/proposals/193 a proposition made by Valentin.
2. Login as mako
3. You can see that the button "Modifier la proposition" appears
4. If I click I can access the form but fortunately I can't hit "Envoyer". 
5. If I hit send the application displays this error "Des erreurs se sont produites lors de l'enregistrement de la proposition."

**Expected behavior**
The button "Modifier la proposition" should only appear on the proposals I authored and when the timeframe for proposal modification set on the feature configuration hasn't ellapsed.

**Screenshots**
<img width="918" alt="capture d ecran 2018-09-06 a 12 49 12" src="https://user-images.githubusercontent.com/11473995/45153137-41812a80-b1d3-11e8-952a-93673a5673f0.png">

**Extra data (please complete the following information):**
 - Decidim installations impacted: demo.decidim.opensourcepolitics.eu, club.decidim.opensourcepolitics.eu, participation.lillemetropole.fr (after first pass complete).

**Comment by armandfardeau** [comment]
Seems to not be present on 0.12-stable developement_app : 
![image](https://user-images.githubusercontent.com/20232956/45155455-56fa5280-b1db-11e8-8416-2ab374ba3418.png)

**Comment by moustachu** [comment]
it seems that it comes from this hazardous fix of mine 
https://github.com/OpenSourcePolitics/decidim/commit/4931a49d14b585f0d90677153202a10be668cf24

which unexpectedly resolved this issue 
https://github.com/OpenSourcePolitics/decidim/issues/136

The _magic_ 💀 debug print was removed later in our 0.12-stable (0.12.2) so it explains why we don't reproduce it in the latest version. 

For the other platform that cannot be update soon, we can patch this with on overrides on the corresponding osp-app.

---

Platform to be fixed : 
- [ ] steamroll.osp.cat
- [ ] demo.decidim.opensourcepolitics.eu 
- [ ] club.decidim.opensourcepolitics.eu
- [ ] participation.lillemetropole.fr

**Comment by moustachu** [comment]
Closing for now. ⏲ 

It should be reopened if we find other affected platform.
