### ISSUE TITLE
"title" not translated (demo)

### ISSUE THREAD

**Issue by leokante** [OpenSourcePolitics/decidim#242]
**Describe the bug**
The word "title" is not translated in french inside the demo

**To Reproduce**
https://demo.decidim.opensourcepolitics.eu/admin/participatory_processes/projet-terrain-de-basket/components/42/manage/

**Expected behavior**
"Title" should be translated to "Titre"

**Screenshots**
![image](https://user-images.githubusercontent.com/43004803/45162992-90d55400-b1ef-11e8-97af-9c9c8dcd2b33.png)

**Extra data (please complete the following information):**
 - Device: [ Desktop]
 - Device OS: [ Windows 10]
 - Browser: [Firefox]
 - Decidim Version: [ ?]
 - Decidim installation: [Demo]

**Additional context**

**Comment by armandfardeau** [comment]
Can't see the error, @moustachu is the demo up to date?

**Comment by juliesimon** [comment]
@armandfardeau just did a test on an osp-app using last version of `decidim#0.12-stable` and I have the same problem, "title" is not translated in French.
It's not when configuring the "survey" component but when configuring the survey itself, when you click on "survey" on the left, under "Fonctionnalités"

**Comment by armandfardeau** [comment]
@lu-hamani Not repoductible
![image](https://user-images.githubusercontent.com/20232956/48353654-3ee9f800-e690-11e8-8c14-bb82745f41b9.png)
