### ISSUE TITLE
Bug sending invit for admin

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#25]
As an admin I can invite another person to be an admin when I create the organisation

# This is a Bug Report
Bug sending invitation for admin when creating an organisation 
by @virgile-dev

**Comment by ludivinecp** [comment]
@juliesimon tu as check sur "localhost:3000/letter_opener" ?
C'est là qu'arrive les mails en dev

**Comment by juliesimon** [comment]
@ludivinecp
Cette issue est isolée d'une liste d'issue qui était déjà là
Je n'ai fait que réorganiser les issues qui sont dans l'inbox/icebox, je n'ai rien checké !
C'est d'ailleurs pour ça que j'ai rajouté le label "needs definition", parce que je pense que ce n'est pas forcément très clair pour un nouveau venu

**Comment by ludivinecp** [comment]
@juliesimon Ok mais du coup qui l'a créé ? Car il n'y a pas à ma connaissance de problème sur l'envoi d'invit.
