### ISSUE TITLE
A user doesn't receive a notification when his proposal's state changes

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#251]
Everytime an admin changes the state of a proposal to "accepted", "rejected" or "being evaluated", every user following this proposal is notified.
Normally when a user publishes a proposal, he automatically follows it, so that he receives a notification when his proposal's state changes.
What needs to be fixed on our decidim is that a user does not follows automatically his proposal when he should.

To test it:
1. I publish a proposal
2. The button "Follow" (in red above) on the show of my proposal should be activated
![capture d ecran 2018-09-11 a 17 24 58](https://user-images.githubusercontent.com/29771726/45370071-b09dbb00-b5e7-11e8-9dfb-339049c214ca.png)

Problem seen on loiret.staging.opensourcepolitics.eu and steamroll.osp.cat so far
Works fine on meta.decidim.org and http://staging.decidim.codegram.com/

**Comment by moustachu** [comment]
Little snippets form Gitter : 

> from **Marc Riera** `@mrcasals`
> for the proposals issue: at the CreateProposal command we add the author as a proposal coauthor (line 53). This method automatically makes the author follow the resource
> the method is defined at the Coauthorable concern

So ... it's working on 0.14 (staging & meta)  with the _Collaborative draft_ feature but not on 0.12.2.

I will patch our 0.12-stable with a quick fix but not sure if I have the time to put up a basic unit test on this. 

- [ ] fix on 0.12-stable
- [ ] **test(s)** on 0.12-stable
- [ ] fix & deploy on Loiret platforms

**Comment by juliesimon** [comment]
Ok thanks @moustachu for the info, let's discuss more about it before doing anything
