### ISSUE TITLE
Not optimal translation on surveys "Déclaration"

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#256]
**Describe the bug**
The field label for the question title on surveys is "Déclaration" which doesn't mean much for the admin. Feedback from MEL.

Same for "Option de réponse".

**Expected behavior**
I suggest we change it for "Titre" or even "Intitulé".

**Comment by juliesimon** [comment]
Already in https://github.com/OpenSourcePolitics/decidim/issues/239 but yes let's choose "Intitulé de la question"

**Comment by juliesimon** [comment]
Fixed in https://github.com/OpenSourcePolitics/decidim/pull/245

**Comment by moustachu** [comment]
Should be fixed on MEL with the next push on osp-app#alt/mel from 0.12-stable
