### ISSUE TITLE
Configure CTA button text of the participatory process card at the "Steps" level

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#257]
To do in branch `decidim#0.12-stable`
Since this feature won't be pushed to Decidim in BCN so far, it needs to be developed through extends(views being hard-coded)
To not forget to put the translations in all the `yml` language files !
FYI [a similar feature has been discussed here](https://github.com/decidim/decidim/pull/2440) but we won't take it into account in this dev so far
______

As an admin, I want to have to possibility to configure the process CTA button so that, depending on the step, I can ask the user for different kind of action.

So far the CTA button text is always "Participer":
![capture d ecran 2018-09-13 a 18 08 50](https://user-images.githubusercontent.com/29771726/45500961-39e7f580-b780-11e8-9251-8d63c0ed1f39.png)

What it should be:
![capture d ecran 2018-09-13 a 18 09 25](https://user-images.githubusercontent.com/29771726/45500979-4409f400-b780-11e8-9d48-2d72c260ee05.png)

For that, an admin needs to be able to configurate the process CTA button in `Processes > [name-of-process] > Steps > [name-of-the-step]`:
![capture d ecran 2018-09-13 a 18 17 24](https://user-images.githubusercontent.com/29771726/45501384-4c166380-b781-11e8-8c9a-673c3a2771b0.png)

**Comment by juliesimon** [comment]
@virgile-dev @moustachu I let you review this issue and Virgile, let us know when it's confirmed !

**Comment by ludivinecp** [comment]
@juliesimon @armandfardeau  The translations and views should go in decidim and not osp-app, right ?

**Comment by juliesimon** [comment]
@ludivinecp yes everything in decidim !
