### ISSUE TITLE
Votes count appear on linked proposals even when votes are not activated

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#261]
On osons.nancy.fr, votes are not activated on proposals. 
When closing a meeting & adding linked proposals, a vote counter (with 0 vote) appear. 
https://participez.nancy.fr/processes/osonsnancy/f/23/meetings/35
<img width="766" alt="capture d ecran 2018-09-15 a 18 19 25" src="https://user-images.githubusercontent.com/10398564/45588386-5e74d680-b914-11e8-99ca-c63514a23949.png">

We should report it to Barcelona as it appear to be a bug.

**Comment by juliesimon** [comment]
Reported here on meta decidim https://meta.decidim.org/processes/bug-report/f/210/proposals/13161

**Comment by lu-hamani** [comment]
Irrelevant issue => https://github.com/decidim/decidim/issues/4172
