### ISSUE TITLE
"Compte rendu" is useless when closing a meeting

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#262]
When closing a meeting, the admin must complete a "compte rendu" which appears as such. Therefore, the "Compte rendu" feature is useless (and mistranslated as a plural), as seen below:
<img width="796" alt="capture d ecran 2018-09-15 a 18 26 54" src="https://user-images.githubusercontent.com/10398564/45588444-1bffc980-b915-11e8-971c-319783c4ef14.png">
(no link as I unpublished the first one).

**Comment by valentinchaput** [comment]
Hmmm... Minutes could be "extraits" and Report should remain as "compte-rendu" because it's embedded in the closing feature. 

As minutes appear in a specific box, it could work as a place for verbatims or quotations.

**Comment by juliesimon** [comment]
Do we validate the change of translation ?
Forgot to add the link to see how it appears in English with linked video and audio 
https://steamroll.osp.cat/processes/eveniet-et/f/2/meetings/1

**Comment by valentinchaput** [comment]
Let's wait for @virgile-dev comment/validation

**Comment by lu-hamani** [comment]
@valentinchaput 
Could you specify on which platform you did find this ? I try to work on it on steamroll as Julie but couldn't replicate the actiosn that lead to your screenshots

**Comment by valentinchaput** [comment]
It was on osons.nancy.fr but I deleted the "Minutes" as it is running in production.

**Comment by valentinchaput** [comment]
Yep, it's only a translation issue!

**Comment by lu-hamani** [comment]
Ok @valentinchaput. Translation is the issue here. Yet whatever the translation may be ("extraits" or "transcriptions", etc.) I fear the UX might be confusing, with the transcripts being before the recap.
What is your take on this @valentinchaput ? @armandfardeau  you are welcome to pitch in as well.

**Comment by valentinchaput** [comment]
Ah, right. My take is that the transcripts will be in a pdf file and this feature is not super important ;)

**Comment by virgile-dev** [comment]
@lu-hamani why not use "Retranscription" ?

**Comment by lu-hamani** [comment]
@valentinchaput 
If you feel it is clearer I am good with it. I'll change the screenshots and it is settled.

**Comment by valentinchaput** [comment]
😈 CD44 does not use the closing option as it sometimes does not want to show the number of participants or the organizations which took part or not. It would like to keep "Compte rendu de la rencontre" (singular) and not change to "Retranscription de la rencontre" >> The Product Team must consolidate in some spreadsheet every variation of the translation. We will send it to all our clients before the next migration and they might pay custom translations.

**Comment by armandfardeau** [comment]
@lu-hamani I'm closing. 
@valentinchaput Very true, I suggest that we talk about an updated translation process in the next Technical's Friday meeting, would you mind adding it to the agenda?
