### ISSUE TITLE
Difference in behaviour between 2 orgs on same install

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#264]
**Describe the bug**
Some bugs for MEL are only visible on dev.mel.osp.cat. 
#232 and potentially #248 

Additionnaly, the toggle menu on the filters of the proposal index are not working on dev.mel.osp.cat and not on mel.osp.cat. See capture
<img width="907" alt="capture d ecran 2018-09-17 a 12 55 07" src="https://user-images.githubusercontent.com/11473995/45619226-d3612100-ba78-11e8-8795-328d9c579efe.png">

**To Reproduce**
1. Go to https://dev.mel.osp.cat/processes/RLP/f/81/

**Comment by lu-hamani** [comment]
@virgile-dev 
Could you be more be more specific please. What action triggered the bug ? What did you expect the filters to do ? "Bugged" is too vague for me.

Thanks !

**Comment by armandfardeau** [comment]
@moustachu I suggest a bundle exec rake tmp:clear
