### ISSUE TITLE
Nancy cannot update/create a meeting because of error in address field

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#267]
**Describe the bug**
It's impossible to add/update a meeting on Nancy because the adress field is never valid.

**To Reproduce**
1. Go to https://participez.nancy.fr/admin/participatory_processes/nancyentransition/components/37/manage/meetings/21 (accès mako)
2. Try to put in the address field "211 Avenue Jean Jaurès, 75019 Paris"
3. Error message: "Address is not valid" and you cannot save the meeting

![capture d ecran 2018-09-18 a 16 07 21](https://user-images.githubusercontent.com/29771726/45693291-0da3ee80-bb5d-11e8-9b81-616288bacf34.png)

Problem only seen on nancy so far

**Comment by juliesimon** [comment]
@moustachu problem is quite urgent. Reminds me of previous issues we had with geocoding.

**Comment by moustachu** [comment]
Might be a good idea to set a better timeout in the code : 
`decidim-core/lib/decidim/core/engine.rb`

In the meantime, I did patch the config file : 
https://github.com/OpenSourcePolitics/osp-app/commit/5794363c8058971111a12daafdaf336d5ee72e2c

### 🎉
