### ISSUE TITLE
Navbar styling disappeared on Loiret

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#273]
https://atelierdevosidees.loiret.fr/ used to have a nice custo "Tequila" navbar. 
<img width="1279" alt="1-4-3-navbar-tequila-loiret" src="https://user-images.githubusercontent.com/10398564/45813458-f1c25900-bcd2-11e8-82a4-6d0a631afead.png">

Now, I can only see the classic black one:
<img width="1277" alt="capture d ecran 2018-09-20 a 12 42 01" src="https://user-images.githubusercontent.com/10398564/45813397-cd667c80-bcd2-11e8-9af0-9f00d8e6c85d.png">

Any problem with the header snippet/code branch?

**Comment by armandfardeau** [comment]
@moustachu @juliesimon Looks like the problem that we have encountered with another customized instance early?

**Comment by moustachu** [comment]
Fixed in https://github.com/OpenSourcePolitics/osp-app/commit/eb3eae5815d54417665c4ee7b4268ad41333197f

### Deployed ✅
