### ISSUE TITLE
OSP is not mentioned on the footer of newly deployed platforms

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#274]
I don't see the catchphrase "Site réalisé par Open Source Politics [link] avec le logiciel libre Decidim" on Orsay's new platform: 
<img width="1250" alt="capture d ecran 2018-09-20 a 12 45 55" src="https://user-images.githubusercontent.com/10398564/45813536-35b55e00-bcd3-11e8-807c-dd019f594edc.png">

Checking on other 0.12 plateforms, the same phrase appears, with no mention of OSP. Did we miss something in the migration process?

**Comment by armandfardeau** [comment]
@moustachu Has this issue been corrected? Hence may I close?

**Comment by Paulinelonguet** [comment]
This issues has not been corrected. 
If you can put the phrase "Site réalisé par [Open Source Politics](https://www.opensourcepolitics.eu/) avec le [logiciel libre Decidim](https://github.com/opensourcepolitics/decidim)"

Thanks !

**Comment by virgile-dev** [comment]
I've been looking at webmaster tools to check where inbound links come from.
Putting links on the footer of our platform is a super interesting for us at generates thousands of inbound links from quality domains.

We should think carefully of our wording and the links we apply there.
It would be great to have a word that we want to position ourselves onto with a link towards our website. 

For exemple : 
"Réalisé par [Open Source Politics, expert **Civic Tech**](https://opensourcepolitics.eu) avec le [logiciel libre Decidim](https://www.opensourcepolitics.eu/#decidim)"

@Paulinelonguet is going to do a competitive analysis on the keywords we want to position ourselves and we'll finalize the wording on the footer based on it.

**Comment by virgile-dev** [comment]
Ok @lu-hamani on a tranché avec Pauline. Voici le texte à mettre en footer.

"Réalisé par [Open Source Politics](https://opensourcepolitics.eu) grâce au [logiciel libre](https://github.com/OpenSourcePolitics/decidim/) de [démocratie participative Decidim](https://opensourcepolitics.eu/#decidim).

**Comment by virgile-dev** [comment]
Hey @lu-hamani 
I'm taking advantage this hasn't been deployed yet. We are on track with the new OSP website which should be ready for the 0.16 deploy to new clients.
We are going to have dedicated pages for decidim and démocratie participative so I change the links.
`Réalisé par [Open Source Politics](https://opensourcepolitics.eu) grâce à [Decidim, le logiciel libre](https://opensourcepolitics.eu/decidim) de [démocratie participative](https://opensourcepolitics.eu/democratie-participative).`

**Comment by lu-hamani** [comment]
@virgile-dev @moustachu 
I tag it as an epic so it doesn't get the label "wontfix". Still we might want to speed things up on the new site to get this done.

**Comment by virgile-dev** [comment]
@lu-hamani my thinking here was to use anchors /#decidim /#democratie-participative on the home page so the footer can be deployed without the new website being a constraint. So the only modification I'd do here is 

Réalisé par [Open Source Politics](https://opensourcepolitics.eu) grâce à [Decidim, le logiciel libre](https://opensourcepolitics.eu/#decidim) de [démocratie participative](https://opensourcepolitics.eu/#democratie-participative).

This said, we are hoping to launch the site on the 13th of may. We could wait until then to update the footers.
