### ISSUE TITLE
TRAD - Change 2 translations on Loiret Budget

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#276]
Repo : `decidim#0.12-stable`
- [ ] Linked proposals section on the project page "Propositions incluses dans ce projet:" > "Propositions inspirant le projet :" (because some proposals included several ideas)
- [ ] Voting button on the project page "Ajouter" > "Voter pour ce projet" ou "Vous avez déjà voté"

https://loiret.staging.opensourcepolitics.eu/processes/budget-participatif-des-parcs/f/18/projects/3
<img width="1123" alt="capture d ecran 2018-09-25 a 14 44 52" src="https://user-images.githubusercontent.com/29771726/46015153-cb852a80-c0d1-11e8-8c96-b38b8315d138.png">

**Comment by armandfardeau** [comment]
@valentinchaput Is this related to https://github.com/OpenSourcePolitics/decidim/issues/272?

May you include more contextual elements to help us find the issue?

**Comment by juliesimon** [comment]
@armandfardeau @lu-hamani @valentinchaput @virgile-dev I edited this issue, for translation modification, please use URLs and screenshots !

**Comment by juliesimon** [comment]
@armandfardeau I edited the issue, it's a go to do the modification on decidim !
