### ISSUE TITLE
Toggle not working on vote button for a project

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#278]
**Describe the bug**
Toggle not working on vote button for a project

**To Reproduce**
1. Go to https://pompano.osp.cat/processes/nouveau/f/112/projects/10
2. Click on "Choisir"
3. See button is now green and "Choisis" (sic: it should be "Choisi" in French, not "Choisis")
4. Click again on the button
5. Nothing happens, the button stays green and "Choisi", but if you refresh the page it's ok (so it means it has been saved but the show is not good)

**Expected behavior**
Button should toggle between "Choisir" and "Choisi"

**Comment by lu-hamani** [comment]
@armandfardeau 
Would you consider they you debugged on wednesday is definitive ? If it's the case issue can be closed and put in deployed for Angers project
