### ISSUE TITLE
Refactoring authorization handlers & impersonifications

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#281]
What I've done is that  I used [Decidim's default dummy authorization handler](https://github.com/OpenSourcePolitics/decidim/blob/0.12-stable/decidim-generators/lib/decidim/generators/app_templates/dummy_authorization_handler.rb) and adapted it so that it fits our clients' need.
To do so, I created a file in the osp-app, `app/services/decidim/osp_authorization_handler.rb`, commented what has to do with postal code and birthday verification, added the corresponding translations and configurated `development.rb`, `test.rb` and `production.rb` to be able to use `osp_authorization_handler.rb`.
See here https://github.com/OpenSourcePolitics/osp-app/commit/8d780789934d66630bfe32c0e68af72085c818c2 for the specific devs (and here for the right locale keys https://github.com/OpenSourcePolitics/osp-app/commit/21c9e47a07d3697884ceb4b00aad93d0ec80df55)

What has also be done is that we can now configurate in the osp-app the fact that when an authorization handler is activated, at a user's 1st connexion, he might see or not a screen offering to verify its identity with the authorization handler. See here: https://github.com/OpenSourcePolitics/osp-app/commit/13499ca7bd096dfd72575c3ab7405b304be3c515

**NEW SPECS FOR AUTHORIZATION HANDLER & IMPERSONATED USERS**

When I activate an authorization handler and try to create a new impersonated user, as an admin: 
- [ ] I should have two mandatory fields, "Name" and "Number"
- [ ] I cannot use a name that has already been used by another impersonated or standard user (else there's an error)
- [ ] To impersonate again an impersonated user, I need to enter the exact number that was entered in the creation (else there's an error). I think this is set in the method `def unique_id` in `authorization_handler.rb`. When set at `nil`, uniqueness is not verified.
- [ ] I can promote an impersonated user by entering it's email adress
- [ ] I can impersonate standard users only by using a number (for more info on this, see [this answer on meta decidim](https://meta.decidim.org/processes/bug-report/f/210/proposals?order=recent&page=2&participatory_process_slug=bug-report&random_seed=-0.6409364403218338))

**Comment by valentinchaput** [comment]
Two reactions:
- We have to manage namesakes (homonymes), i.e. possible same name but with different numbers... maybe in adding a second surname for the second person with the same name?
- What I don't understand on [Xabier's answer](https://meta.decidim.org/processes/bug-report/f/210/proposals/13075) about impersonating standard users is how the platform knows the number at first! We may have to use official ID number, but it's a barrier for participation (let's imagine someone on the field who has no ID when voting - we might consider it should not be possible to be impersonated if one cannot prove it's identity?) + we might have CNIL/GDPR issues with collecting IDs.
