### ISSUE TITLE
Check if branch f-moderation upgrade to 0.9.pre went OK

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#29]
## Context for the moderation à priori feature 
Ludivine has been working on moderations adding the possibility to moderate content a priori for proposals and comments (on all comment objects on the app : meetings, results, etc.). On the Decidim original gem it is only possible to moderate a posteriori, meaning after a comment / proposal was published and signaled. A priori moderation means that moderators and admins can review what's being published before hand and decide to publish it or not. Here is the spec that was given to Ludivine
![user flow](https://user-images.githubusercontent.com/11473995/34524542-33af5cfe-f09c-11e7-8a53-1893c8c3bddc.png)

Mockups can be checked here : https://www.figma.com/file/MX4BYbJ5VKUO1xSraC8DQefk/user-flow-moderation-a-priori?node-id=0%3A1

Ludivine just merged the branch [f-moderation](https://github.com/opensourcepolitics/decidim/tree/f-moderation) with [develop](https://github.com/opensourcepolitics/decidim/tree/develop) which was upgraded to the last version of decidim 0.9.pre. 

The task here is to check if the upgrade went ok: 
- [x] create a branch test-develop-maj on [osp-app](https://github.com/OpenSourcePolitics/osp-app) 
- [x] in the gemfile point to https://github.com/opensourcepolitics/decidim/tree/develop for the decidim gem
- [x] make migrations (see bellow) and commit
- [x] deploy to heroku and send us the link
- [x] begin testing, could be interesting that @juliesimon be involved in testing so she gets to understand how the feature works. 

Migrations to run before deploying new version

```
rails decidim:install:migrations
rails  decidim_admin:install:migrations
rails      decidim_system:install:migrations
rails      decidim_accountability:install:migrations
rails      decidim_participatory_processes:install:migrations
rails       decidim:install:migrations
rails     decidim_budgets:install:migrations
rails       decidim_pages:install:migrations
rails     decidim_meetings:install:migrations
rails     decidim_comments:install:migrations
rails    decidim_surveys:install:migrations
rails decidim_proposals:install:migrations
rails decidim_assemblies:install:migrations
```

**Comment by bastienrobert** [comment]
Well deployed on https://osp-test-develop-maj.herokuapp.com/

**Comment by virgile-dev** [comment]
Proposal moderation seems to work fine. But we have a problem with comment moderation. Only comment I have is when moderation a priori is unchecked for proposals.
It displays the same validation message as when it's activated which is misleading. 
<img width="1266" alt="capture d ecran 2018-01-16 a 16 36 46" src="https://user-images.githubusercontent.com/11473995/34997076-c05e6f02-fadb-11e7-9bbd-f8659909b0a1.png">

Here is what's happening:
When moderation à priori on comments is activated, when I try to make a comment nothing happens. 
- Email is not sent to admin and moderators
- A new entry is not added to the moderation table "A modérer" either

Here is a screencast:
![comment-moderation](https://user-images.githubusercontent.com/11473995/34997207-1ff045bc-fadc-11e7-9349-1ec253b02044.gif)

I've tried unchecking moderation à priori on comments and as I try to publish a user nothing is displayed in the comment feed either.

**Comment by juliesimon** [comment]
@bastienrobert @virgile-dev  Si je reprends les issues, je m'aperçois que celle-ci n'a jamais été fermée. Le déploiement sur https://osp-test-develop-maj.herokuapp.com/ est fait mais pas le fix des problèmes qu'a soulevés Virgile. Et en effet, la modération des propositions à priori marche bien mais impossible de laisser un commentaire.

De plus, maintenant test-develop-maj n'est plus à jour de develop.

Qui s'occupe du fix @virgile-dev ?

@ludivinecp est ce que tu t'es penché sur ce problème dans le cadre de SQR ?

**Comment by ludivinecp** [comment]
@juliesimon Je m'en occupe aujourd'hui
