### ISSUE TITLE
Select proposal location through map

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#293]
**Is your feature request related to a problem? Please describe.**
A client (MEL) requests that when submitting a proposal, a user should be able to pick the location associated to his proposal with a drag and drop within a map. Client was inspired with the following service : http://demo.carticipe.fr/#

**Describe the solution you'd like**
As a User, I want the address I picked for my proposal displayed on a map, so that I can change its position directly on the map before publishing it.

**Describe alternatives you've considered**
Asking the user for longitude and latitude beforehand. Though it is unlikely that he/she will have such information.

**Additional context**
User journey for the feature

**Comment by virgile-dev** [comment]
⚠️ If user can change geocoding by dragging the pin on the map the address associated to the proposal might no longer be relevant. How can we prevent this ?

**Comment by virgile-dev** [comment]
We did a demo to the client.

Feedback overall is good.
- He really liked the display the map in the preview, how it integrates to the actual flow of Decidim proposal wizard.
- He is concerned that user might not know what to input in the address field and get blocked in their proposal creation process. 

A couple UX improvements we can address now: 
- Add tip so the user understand what to input in the address field (complete address, city, neighbourhood etc.)
- Add tip so the user understand that he can move the pin on the map
- Add tip so the user understand that he has to hit the button to save the new location

Improvements for future iterations:
- Always display address field when geocoding activated
- Add autocomplete on address field
- Add admin config so the address is a mandatory field. 

--> The client need is to have more geocoded propositions when it's activated, right now the ratio is too low for him. 

@lu-hamani can you run @armandfardeau 's code locally and provide me with a screen capture of the whole feature flow. (Armand has a nice to make screen capture in gif format.

**Comment by lu-hamani** [comment]
@armandfardeau 
To supplement the feature UX, we add three instructions in the journey, so the user know how to accomplish his task.

Here are screenshots so that you know what the instructions are and where to put them. Don't mind asking me if you need some further description.

![step 4](https://user-images.githubusercontent.com/32680605/47091104-819ce980-d224-11e8-9bb6-fd6152446471.png)
![step 3](https://user-images.githubusercontent.com/32680605/47091105-819ce980-d224-11e8-9540-8372acc9ef03.png)

**Comment by armandfardeau** [comment]
Primary text -> Vous pouvez déplacer le point sur la carte.
Secondary text -> N'oubliez pas de cliquer sur le bouton "Mettre à jour la position" avant de publier votre proposition.
