### ISSUE TITLE
Bug on notifications

### ISSUE THREAD

**Issue by antoinegaboriau1** [OpenSourcePolitics/decidim#297]
@lu-hamani 
Sur le Club utilisateurs (0.12), j'ai un bug serveur dès que je clique sur l'icone notifs. Pareil quand j'y accède via le menu utilisateurs.

**Comment by lu-hamani** [comment]
Might be linked to #279 .

**Comment by lu-hamani** [comment]
@armandfardeau @moustachu 
Sentry can be of some help on the matter I assume. What can we do about it ? Even though it is not an urgent matter, it would be much appreciated if we solved it once and for all.

**Comment by armandfardeau** [comment]
> Might be linked to #279 .

Not linked to #279 
#279 is a duplicate key value violation.

**Comment by leokante** [comment]
I just observed the same error on the 0.16 version of the https://demo.decidim.opensourcepolitics.eu/
Any news ? @lu-hamani
