### ISSUE TITLE
Navbar custom

### ISSUE THREAD

**Issue by ludivinecp** [OpenSourcePolitics/decidim#3]
Objectif : rendre la secondary navbar éditable pour pouvoir 
- intégrer un lien direct vers une page du site (ex : budget Angers)
- intégrer un lien direct vers un site externe

by @valentinchaput

**Comment by ludivinecp** [comment]
@valentinchaput Il faut que ce soit éditable dans le back office ? Et que l'admin puissent rajouter le nombre de liens qu'il veut (que ce soit interne ou externe) ?

**Comment by valentinchaput** [comment]
Oui, dans l'idéal !

**Comment by ludivinecp** [comment]
@valentinchaput Je suis partie sur quelque chose comme ça : <img width="1251" alt="screen shot 2017-12-28 at 18 41 09" src="https://user-images.githubusercontent.com/12518762/34418495-ba5d2634-ebfe-11e7-82fe-a1a3d6212c58.png">
Ce n'est pas fini, mais je te montre à mi chemin pour que tu valides

**Comment by virgile-dev** [comment]
ça l'air pas mal :) ya moyen de voir le formulaire de saisi qui permet de rajouter le formulaire ?

**Comment by ludivinecp** [comment]
@virgile-dev  Et voici, tout chaud !
<img width="910" alt="screen shot 2017-12-28 at 19 11 59" src="https://user-images.githubusercontent.com/12518762/34419252-0ece0586-ec03-11e7-884a-99b6cab0ebff.png">

**Comment by virgile-dev** [comment]
Nickel ! Je me demande si c'est intéressant de rajouter une option "Ouvrir le lien dans un nouvel onglet" en mode checkbox. T'en penses quoi ?

**Comment by CivicTechFR** [comment]
Excellent !

@ValentinChaput
+33 6 45 49 56 78

**Comment by ludivinecp** [comment]
@virgile-dev Je n'avais pas vu ton commentaire.
J'ai mis un target blank par défaut.
Vous pouvez tester sur develop si vous voulez, c'est mergé.

**Comment by virgile-dev** [comment]
2 options
- ouvrir sur un nouvel onglet
- ouvrir dans le même onglet

**Comment by virgile-dev** [comment]
@ludivinecp Avec @juliesimon on a pas réussi à tester les navlinks.  On a pourant déployé ton code en local (branche develop). Faudra que tu nous dises comment faire pour tester
