### ISSUE TITLE
Unreadable CTAs in mobile menu

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#301]
**Describe the bug**
Both links for connexion and registration are unreadable in the mobile menu as they are black on black. It happens when desktop primary menu has a white background.
Behavior can be found on mulitple platorms (cf. screenshots)

![orsay menu](https://user-images.githubusercontent.com/32680605/46597531-be5c3880-cae0-11e8-87e7-a8cbb4fa74c2.jpg)
![angers menu](https://user-images.githubusercontent.com/32680605/46597533-be5c3880-cae0-11e8-99be-3a662dd26126.jpg)

**To Reproduce**
1. Go to Homepage => ecrivons.angers.fr
2. Click on the Burger menu
3. See error

**Expected behavior**
Both links must be readable. Quick fix would be to make them white in this menu

**Comment by armandfardeau** [comment]
@lu-hamani Closing since it's done.
