### ISSUE TITLE
Hide alert message on Orsay's private process

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#306]
When connecting to the private process where parents will fill the survey, an alert message appears:

<img width="1168" alt="capture d ecran 2018-10-11 a 14 31 49" src="https://user-images.githubusercontent.com/10398564/46804393-c62b0f80-cd62-11e8-89e5-069bf540d2ec.png">

It may be confusing and should be hidden. Best would be to do it before this weekend :)

**Comment by lu-hamani** [comment]
@armandfardeau 
Where does this kind of change occur ? Front ? Back ?

**Comment by armandfardeau** [comment]
@lu-hamani Front
