### ISSUE TITLE
Custom invitation email template for Orsay's users

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#307]
By default, the invitation email looks like that:

<img width="953" alt="capture d ecran 2018-10-10 a 10 45 52" src="https://user-images.githubusercontent.com/10398564/46804535-228e2f00-cd63-11e8-8fec-c6470e113f33.png">

We have to make these improvements before the weekend:
- [x] Sender: "OSP Agora" > "Consultation mairie d'Orsay"
- [x] Header: black > white + keep the logos

- [x] Text:

Bonjour {%Name},

Monsieur le Maire d'Orsay, David Ros, vous invite à participer à la consultation sur les rythmes scolaires et périscolaires pour la rentrée 2019. Cliquez sur le lien ci-dessous pour accéder à la page de création de votre pseudonyme et mot de passe, puis à la consultation.

Accepter l'invitation [lien]

Cette invitation est valable du lundi 15 octobre au vendredi 9 novembre 2018 à 23h59.

Attention : votre compte ne sera pas validé avant d'avoir cliqué sur le lien ci-dessus.

- [ ] Make sure the email invitation is valid until Nov.9!

**Comment by armandfardeau** [comment]
@valentinchaput The invitation will be valid 26 days. We currently can't set an expiration date on a precise day, only a number of days in the number.

**Comment by valentinchaput** [comment]
OK cool. Is it possible to:
- set the expiration date on the 9th, 
- avoid printing the automatical counter,
- write "au vendredi 9 novembre 2018 à 23h59" ?

Actually, quite the same issue with "Le maire d'Orsay" which is no user, isn't it?

**Comment by valentinchaput** [comment]
Well @lu-hamani , as you mention it, I remind you all this was not working perfectly and we will have to fix the navbar header + the text when we relaunch the process.
