### ISSUE TITLE
Improve voting confirmation btn for budgets

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#312]
**Is your feature request related to a problem? Please describe.**
Roughly 20% of the voters for participatory budget don't confirm their votes as the button is confusing. It is the same text as the voting btn (both time "Voter")
<img width="1175" alt="screen shot 2018-10-15 at 17 24 25" src="https://user-images.githubusercontent.com/32680605/46961407-fe06bf80-d0a0-11e8-8a7c-ccfc8c304831.png">

**Describe the solution you'd like**
Confirmation button text should be changed to : "Confirmer votre vote"

**Comment by valentinchaput** [comment]
I think "Valider votre vote" is even more impactful. What do you think @virgile-dev?
