### ISSUE TITLE
Mandatory answer to an optional question

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#313]
**Describe the bug**
A sortable question is mandatory for a user to answer the survey even though the admin set it as optional.
The actual error message displayed when the bug occurs is : 'choices aren't complete'

**To Reproduce**
1. Go to 'https://steamroll.osp.cat/processes/concert/f/8/'
2. Don't answer the question !
3. Click on 'Envoyer'

**Expected behavior**
Optional question shouldn't be mandatory to answer.

**Screenshots**
![screen shot 2018-10-16 at 15 19 06](https://user-images.githubusercontent.com/32680605/47019231-da05b580-d156-11e8-817a-a4fbfad1fc5e.png)

**Comment by valentinchaput** [comment]
Adding 2 points of context:
- Sortable answering was implemented after the other 4. They may have forgotten something when coding it?
- We have to *find a quick fix asap* as the client is pretty upset already after yesterday and our emails which were not sent.
