### ISSUE TITLE
Survey - Answers are changed after invalid submission 

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#315]
**Describe the bug**
Invalid submission = no answer to a mandatory question / incomplete answer to a sortable question.
When I answer a survey and my submission is invalid and my answers are changed as follows :
<img width="781" alt="screen shot 2018-10-18 at 09 59 09" src="https://user-images.githubusercontent.com/32680605/47139601-801f0000-d2bc-11e8-842d-4b7b93c32f4f.png">

Patterns :
- Answer to radio buttons question is automatically set to the last choice
- Answer to sorting is reset to original order : if I ranked the third choice as first, it is selected as third.

**Expected behavior**
Answers should be kept as originally answered.

**Comment by valentinchaput** [comment]
I did some extended tests:
- The same patterns happen on every browser (Firefox, Chrome, Safari).
- When the survey contains a mandatory text filling question that is not complete (not the case in Orsay), it triggers the error before refreshing the page/changing the other answers.

In parallel of the resolution of this issue, we may find in the logs if many parents faced this problem.
