### ISSUE TITLE
NL translation (small) issues on monopinion.belgium.be

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#318]
- [x] translation missing on facebook, twitter and google login button
<img width="415" alt="capture d ecran 2018-10-23 a 15 45 16" src="https://user-images.githubusercontent.com/11473995/47364813-77726380-d6da-11e8-88fa-d71e0eb66ddc.png">

- [x] "votes blocked" is not translated in NL
<img width="753" alt="capture d ecran 2018-10-19 a 15 01 36" src="https://user-images.githubusercontent.com/11473995/47219672-bc7f5880-d3af-11e8-9c2b-4d93ef3b3e81.png">

- [ ] "Enquête"  not translated
<img width="879" alt="capture d ecran 2018-10-25 a 11 44 22" src="https://user-images.githubusercontent.com/11473995/47491594-7280f180-d84b-11e8-9bcc-237a94334033.png">

- [ ] translation missing notif "new proposal"
<img width="763" alt="capture d ecran 2018-10-25 a 12 59 21" src="https://user-images.githubusercontent.com/11473995/47496809-4881fc00-d858-11e8-9819-3c292499fec8.png">

**Comment by moustachu** [comment]
### 🚚 delivery !
### **@** https://dev.bosa.opensourcepolitics.eu/
