### ISSUE TITLE
Update DE translation locale files

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#319]
We are receiving the professionnaly translated files.
Once I've received them all we'll have to test them.

How should we proceed ? 
1. Test them on staging 
2. Once good put them on production
2 bis. activate DE on monopinion.belgium.be

**Deadline:** Technically, the client says we need to be up and running for the 5/11.
**Use case:** they are going to use the survey (0.10, no ordering of options) component to ask about changing of hours (winter, summer).

**Comment by moustachu** [comment]
[Trad allemand-20181023T140541Z-001.zip](https://github.com/OpenSourcePolitics/decidim/files/2506429/Trad.allemand-20181023T140541Z-001.zip)

Translated YAML files (23/10/2018)

**Comment by moustachu** [comment]
### 🚚 delivery !
### **@** https://dev.bosa.opensourcepolitics.eu/

**Comment by virgile-dev** [comment]
- [ ] Seite erstellt von Open Source Politics grâce au Freie Software Decidim.
<img width="552" alt="capture d ecran 2018-10-25 a 11 34 17" src="https://user-images.githubusercontent.com/11473995/47495876-9812f880-d855-11e8-992a-4ea5bc86feb9.png">

**Comment by virgile-dev** [comment]
3 new files to add to the repo @moustachu please :)
📦[translations-de.zip](https://github.com/OpenSourcePolitics/decidim/files/2566267/translations-de.zip)
