### ISSUE TITLE
Several bugs in production related to user sign up

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#32]
# This is a (Bug Report / Feature Proposal)

#### :tophat: Description

In the past few days we've had several problems related to the decidim-angers repo that is deployed in angers.opensourcepolitics.eu. 

Bugs were related to user sign ups : 
- At first, when trying to sign up, once form filled and clicking on the sign up button, the app would return a "the server couldn't locate your page".
- Then after @moustachu spent some time on it, but it seem we haven't solved all problems. The behaviour right now is that when signing up you are able to fill the form but you never receive the confirmation email. I've been doing some testing on my side using the regular osp-app and i replicated this bug. So it's not just related to osp-angers.

**Comment by valentinchaput** [comment]
An incomplete configuration of the mailer was responsible of this bug. Problem solved!
