### ISSUE TITLE
Error message not consistent when disconnected

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#320]
<img width="1280" alt="capture d ecran 2018-10-20 a 09 24 25" src="https://user-images.githubusercontent.com/11473995/47252777-5b589300-d44a-11e8-9260-f93b79bdb8ec.png">
@lu-hamani did you have the same ?

**Comment by lu-hamani** [comment]
@virgile-dev never seen this before.
How did you come by it ?

**Comment by virgile-dev** [comment]
Almost every time the cookie for my session expired.
