### ISSUE TITLE
Possibility for pre-moderation (priori) of proposals and comments

### ISSUE THREAD

**Issue by ahukkanen** [OpenSourcePolitics/decidim#33]
# This is a Feature Proposal

#### :tophat: Description

This issue originates from the [decidim main repository](https://github.com/decidim/decidim/issues/2503).

Regarding that, I was made aware that pre-moderation (or priori moderation) has been implemented in this Decidim repository due to convincing some organizations into using Decidim. Further details regarding the feature proposal and also about the implementation details can be found from the linked Decidim main repository issue. The implemented code is available in the [f-moderation branch](https://github.com/opensourcepolitics/decidim/tree/f-moderation) of this repository.

What I am suggesting is that we should extract this feature into its own gem so that this feature would be more widely available to the decidim users. There is the ideological debate also concerning this issue whether it is good for the Decidim community to make this feature mode widely available. However, I personally believe this may lead into more Decidim users as already proven by the original need of developing this feature.

Action points:

* :+1: Yes, let's do it! - Leave a thumbs up to this thread if you feel this feature should be available for all Decidim users.
* :-1: No, this should not be done! - Leave a thumbs down to this thread if you feel this feature should NOT be available for all Decidim users.

The repository maintainer can decide the threshold on when this would be accepted/rejected.

In case this is accepted, we would need to scratch out a plan on the implementation details and how it would be possible to extract this feature into its own gem.

#### :pushpin: Related issues
* https://github.com/decidim/decidim/issues/2503

#### :clipboard: Additional Data

* ***Decidim deployment where you found the issue***:
* ***Browser & version***:
* ***Screenshot***:
* ***Error messages***:
* ***URL to reproduce the error***:

***Screens about the implementation***:
https://www.figma.com/file/MX4BYbJ5VKUO1xSraC8DQefk/user-flow-moderation-a-priori

***Logical workflow***:

![](https://user-images.githubusercontent.com/11473995/34524542-33af5cfe-f09c-11e7-8a53-1893c8c3bddc.png)

**Comment by virgile-dev** [comment]
This moderation a priori feature is making it complicated for us to maintain our codebase so I'm voting in favor to extract it to an engine.

**Comment by virgile-dev** [comment]
@ludivinecp do you think it's feasable to isolate in an engine the moderation à priori functionnality ?
