### ISSUE TITLE
Email notification for vote confirmation

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#337]
**Is your feature request related to a problem? Please describe.**
When user is voting for a budget, acceptance of his vote is not clear.

**Describe the solution you'd like**
To clarify the acceptance of a vote, user should receive a confirmation email, thanking him and telling him that his vote has been saved.

**Describe alternatives you've considered**
This feature request goes hand in hand with the revamp of vote confirmation sequence. #343 

**Mockup**
![mail notification budget](https://user-images.githubusercontent.com/32680605/52112599-3c4fcc80-2607-11e9-9927-35239b80de40.png)

**Comment by moustachu** [comment]
**Level 2** : 
- no special technical difficulties
- most of the code is already available to duplicate or reuse
