### ISSUE TITLE
Budget Instructions container with $success color for borders

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#343]
**Is your feature request related to a problem? Please describe.**
"Right after I confirmed my vote, I thought I didn't go through with the whole process. It's only after I read the instructions to erase my vote so I can do it again that I understood that my vote was saved properly."

**Describe the solution you'd like**
"I expected a change in the display that showed me my vote was saved. Not exactly the same page with only text changes."
Border color should be changed to $success to emphasize that the user vote has been a success.

**Describe alternatives you've considered**
This feature request goes hand in hand with vote confirmation email notification. #337  

**Mockup**
Vote per budget
![budget vpbb confirmed](https://user-images.githubusercontent.com/32680605/52637604-fd0b6080-2ecf-11e9-894d-b855071f785a.png)

Vote per project
![budget section confirmed](https://user-images.githubusercontent.com/32680605/52637623-085e8c00-2ed0-11e9-9210-740c9cf0d357.png)

**Comment by moustachu** [comment]
**Level 2** : 
- no special technical difficulties
- most of the code is already available to duplicate or reuse
