### ISSUE TITLE
ArgumentError: SMTP To address may not be blank: []

### ISSUE THREAD

**Issue by armandfardeau** [OpenSourcePolitics/decidim#347]
https://sentry.io/open-source-politics/saas-ema/issues/766696011/?referrer=github_plugin

```
ArgumentError: SMTP To address may not be blank: []
  mail/check_delivery_params.rb:21:in `check_to'
    raise ArgumentError, "SMTP To address may not be blank: #{addrs.inspect}"
  mail/check_delivery_params.rb:7:in `check'
    check_to(mail.smtp_envelope_to),
  mail/network/delivery_methods/smtp_connection.rb:52:in `deliver!'
    smtp_from, smtp_to, message = Mail::CheckDeliveryParams.check(mail)
  mail/network/delivery_methods/smtp.rb:101:in `block in deliver!'
    Mail::SMTPConnection.new(:connection => smtp, :return_response => true).deliver!(mail)
  net/smtp.rb:519:in `start'
    return yield(self)
...
(91 additional frame(s) were not displayed)

SMTP To address may not be blank: []
```

**Comment by armandfardeau** [comment]
@moustachu 

STEP 1 Leave a way-too-borderline comment
![image](https://user-images.githubusercontent.com/20232956/49082523-41308280-f24a-11e8-9e47-560f5712ce0b.png)

STEP 2 Delete account
![image](https://user-images.githubusercontent.com/20232956/49082393-f0b92500-f249-11e8-8ae7-db5be67279a9.png)

STEP 3 Notify user and admins
![image](https://user-images.githubusercontent.com/20232956/49082576-64f3c880-f24a-11e8-9dd5-8139e5c2ca4d.png)
![image](https://user-images.githubusercontent.com/20232956/49082589-6a511300-f24a-11e8-9874-c1da91e73994.png)

STEP 4 Content successfully deleted.

> I think the problem comes from user_to_notify_on_comment_created, which is an OSP custom method. I will work on a fix.

**Comment by lu-hamani** [comment]
@moustachu @armandfardeau 
https://github.com/decidim/decidim/issues/4423
Guess we have our fix
