### ISSUE TITLE
Post-workshop Saint-Jean de Braye debug & custo

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#350]
Hey @lu-hamani,
Small issues/todolist on SJdB:

- [x] TRAD "Global scope" when activating "secteurs" on a process >> usual French translation is "Portée générale" and we should use "Quartiers" in this context. 
- [x] We must hide "Comment participer" + the bottom "Bienvenue" sections in the header snippet.
- [x] The client asks us to remove the opacity filter on banner + process header image.
- [x] On the topbar white text, hover is in secondary blue so we cannot read it text when hovering "S'inscrire/Se connecter". We should use some grey or primary orange (?)
- [x] On the navbar section, we must replicate what Julie did with https://www.budget-participatif-romainville.fr/ >> change "Concertations" to "Budget participatif" + change link from /processes to /processes/bp.
- [x] We must activate "utilisateurs représentés".
- [x] We should add Matomo + Uptime Robot.
- [x] Please anticipate that Alain will have to erase their fake/test proposals & comments in the database (sorry for that, they add fun after the workshop + they already know we'll fix their mistake only once!). 

Thanks a lot!

_FYI: We have a last call with the client on Dec 7 / the platform will go live on Dec 11._

**Comment by lu-hamani** [comment]
@valentinchaput 
Could they just delete the concertation they had their fun with instead of asking @moustachu to intervene on the DB ?
I am sure he would appreciate it.

**Comment by lu-hamani** [comment]
@valentinchaput 
For the the impersonated users, which handler do they need ? By ID ? By Zip Code ? Both ?

**Comment by valentinchaput** [comment]
The same as for our other clients, so I guess none of the ones you mention!
I have a call with them tomorrow morning, will ask them to duplicate their process. 
I see that "Global scope" is still in English -we did not deploy the fix, right?

**Comment by lu-hamani** [comment]
@valentinchaput 
So we are talking about OSP custom handler for impersonated users. Duly noted.
Regarding the "Global Scope" I would say it is a translation rather than a fix ;). Anyway it has not been done yet since we thought an action on the DB was necessary so we had planned for the latest deployment possible.

**Comment by moustachu** [comment]
@lu-hamani 

### To be checked & to be closed ✅
