### ISSUE TITLE
Center map on organization's territory

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#355]
**Is your feature request related to a problem?** 
On participez.nanterre.fr geocoding functionnality is activated. One problem though the only proposal that was submitted with an address was geocoded in Belgium because the citizen submitting it didn't add specify the city name in the address field. 
<img width="1202" alt="capture d ecran 2018-12-04 a 18 33 24" src="https://user-images.githubusercontent.com/11473995/49461066-25e9e800-f7f3-11e8-932c-ba8520f635be.png">

This causes the map to be centered on some random place in Belgium instead of Nanterre which is quite problematic. Even if other proposals were geocoded on Nanterre we'd still have a problem with how the map is centered.

**Describe the solution you'd like**
A short term solution to this would be to center the map on Nanterre like we did for mel.osp.cat. 
Because the map is centered on the right territory geocoding messups are less visible. 
<img width="1205" alt="capture d ecran 2018-12-04 a 18 31 57" src="https://user-images.githubusercontent.com/11473995/49460929-cee41300-f7f2-11e8-9102-bab7236772c0.png">

It feels like a better solution than modifying in db the latitude and longitude every time it doesn't work.

**Describe alternatives you've considered**
A more long term alternative would be to dynamically propose addresses based on what the user is typing.

Another one would be to add Nanterre by default to the address.

**Comment by lu-hamani** [comment]
@virgile-dev 
BCN is working on the geocoding scope so that an organisation can limit the requests scope to a single city, region, etc. I didn't find the proposal on metadecidim yet, still it was shared by @moustachu  at some point regarding this feature => #296.

**Comment by lu-hamani** [comment]
@virgile-dev 
I suggest we close this one as it is getting old and we should avoid confusion.

Since the request, our feature #296 has been merged and deployed to every client and prevent this error. Especially with @moustachu further tweaks on how the map is displayed.

**Comment by virgile-dev** [comment]
What @moustachu is working (geojson areas for scopes) should provide a solution to this. It's ok to close for now since this is something we can configure with the technical team using leaflet. It can even be considered a premium feature I think.
