### ISSUE TITLE
Invitation not working in Nancy?

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#365]
On participez.nancy.fr,

When I add a new user to an assembly, the activation link he receives by email is not working >> redirect to 
<img width="1278" alt="capture d ecran 2018-12-11 a 14 45 43" src="https://user-images.githubusercontent.com/10398564/49804740-aceb1300-fd53-11e8-8af2-850b069fbe28.png">

I cannot complete my profile and access to the private processes-assemblies/my admin roles. 

+ The alert message is not translated. My guess is the version of Nancy's platform (the first client that was migrated to a 0.11 back in the days) is not up to date...

**Comment by lu-hamani** [comment]
@valentinchaput 
Who are you trying to invite ? An admin ?

**Comment by valentinchaput** [comment]
Actually, it's working when I invite an admin. 

My sequence was probably wrong, as I tried to invite a private user and then to promote him as an admin. The first link did not work, the second was ok. 

Let's check with Antoine (I try to invite him).

**Comment by valentinchaput** [comment]
Still, we should try to invite regular private users in an assembly, as we are going to need it on Thursday.

**Comment by armandfardeau** [comment]
Sentry issue: [NANCY-FIONA-C](https://sentry.io/open-source-politics/nancy-fiona/issues/783877352/?referrer=github_plugin)

**Comment by armandfardeau** [comment]
@valentinchaput @lu-hamani 


We have tested the following with Antoine:
- invite admin into a public space
- invite a user into a public space
- invite admin into a private space
- invite a user into a private space
