### ISSUE TITLE
Accountability home redirection to list of results

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#374]
Angers wants to implement Accountability feature for its PB (preview here if you are connected as an admin https://ecrivons.angers.fr/processes/BP2018/f/137/). The very last deadline would be the end of January when they launch the new edition. 

Problem is the general homepage of this feature is very confusing... and mostly blank in this case with only 6 general categories and no subcategories. 
![screenshot_2018-12-20 realisation des projets laureats - budget participatif 2018 - ecrivons angers 1](https://user-images.githubusercontent.com/10398564/50295196-d43e9000-0477-11e9-8fea-6c184382aa90.png)

On the contrary, the list of results you reach by clicking on the search glass suits perfectly with the client's need. 
![screenshot_2018-12-20 realisation des projets laureats - budget participatif 2018 - ecrivons angers](https://user-images.githubusercontent.com/10398564/50295203-d7d21700-0477-11e9-802c-33de7720330d.png)

The request here: to change the redirection on the feature button in order to skip the general homepage and go directly to the list of results (at least for Angers).

**Comment by lu-hamani** [comment]
We should take into account this PR https://github.com/decidim/decidim/pull/3217 when dealing wit this customization.
