### ISSUE TITLE
Translation inconsistency in home stats table

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#378]
**Describe the bug**
"Processus participatifs" should be "Concertations"

**To Reproduce**
https://concertations-int.nouvelle-aquitaine.fr/

**Screenshots**
<img width="891" alt="capture d ecran 2018-12-28 a 10 22 03" src="https://user-images.githubusercontent.com/11473995/50516605-779c3000-0a8a-11e9-80ca-20af16fe6179.png">

**Magnitude**
Discovered by client Nouvelle Aquitaine, this translation patch is to be applied to the rest of the clients instances as they have the same inconsistency. Check https://participez.nanterre.fr/ for example.

**Comment by moustachu** [comment]
✅ Fixed on 0.12-stable 
✅ Merged on 0.12-nouvelle_aquitaine
