### ISSUE TITLE
Layout goes automatically to the line cutting words in half

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#379]
**Describe the bug**
Layout goes automatically to the line cutting words in half. A good example is in the processes home page in mobile display.

**To Reproduce**
https://concertations-int.nouvelle-aquitaine.fr/

**Expected behavior**
The layout should make the whole word go back to the line instead of cutting it in half.

**Screenshots**
<img width="419" alt="capture d ecran 2018-12-28 a 10 26 33" src="https://user-images.githubusercontent.com/11473995/50516777-80d9cc80-0a8b-11e9-8b05-a3ceab91a4d0.png">

**Magnitude**
This bug was found by client Nouvelle Aquitaine but other clients instances have the same issue. If we come up with a patch it'd be good to apply it generally.

**Comment by moustachu** [comment]
#305 was merged on 0.12-stable and then merged on 0.12-nouvelle-aquitaine. 

This one concerns all platform. This is CSS so Quick fix will go to the osp-app but should we keep this one opened for 0.12-stable ? @virgile-dev @lu-hamani

**Comment by lu-hamani** [comment]
@moustachu 
yes since it is also present in 0.16. We'll bump it afterwards
