### ISSUE TITLE
Add images to snippets when sharing on social networks

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#40]
# This is a Feature Proposal

#### :tophat: Description
When sharing a process/page/proposal on facebook, we get the content of the proposal + the box with a link. On decidim.barcelona, they also manage to show an image which makes the content more attractive. How could we achieve the same result? 

<img width="555" alt="capture d ecran 2018-02-16 a 13 12" src="https://user-images.githubusercontent.com/10398564/36307204-5cd209e6-131b-11e8-9346-e8e27a34b945.png">

Going further, would it be possible to choose/edit those text & image?

**Comment by juliesimon** [comment]
Réponse des barcelonais (encore à tester !) 

you can use add_decidim_meta_image_url(my_image)for that @juliesimon (you need to use it from the layout
we usually use the add_decidim_meta_tags helper, both methods are defined here: https://github.com/decidim/decidim/blob/master/decidim-core/app/helpers/decidim/meta_tags_helper.rb
an example of how to use it can be found here, for example https://github.com/decidim/decidim/blob/master/decidim-participatory_processes/app/views/decidim/participatory_processes/participatory_processes/show.html.erb#L1-L7 (it is used in other places too)

**Comment by juliesimon** [comment]
@valentinchaput 
J'ai fait plusieurs tests et ça marche bien quand l'image respecte les guidelines facebook pour les images des tags meta : _https://developers.facebook.com/docs/sharing/best-practices?locale=fr_FR#images_
En cas de doute, il est possible de rentrer l'url ici https://developers.facebook.com/tools/debug/sharing afin de s'assurer que les liens se partagent correctement
