### ISSUE TITLE
Custom CTA Button misplaced on participatory process card

### ISSUE THREAD

**Issue by Paulinelonguet** [OpenSourcePolitics/decidim#408]
**Describe the bug**
The button "Voir le résultat" is located under the text instead of being on the same line

**To Reproduce**
Go to and scroll down: https://participation.lillemetropole.fr/processes?filter=all

**Expected behavior**
Button should be on the same line.

**Screenshots**

![capture d ecran 2019-01-09 a 10 11 43](https://user-images.githubusercontent.com/46523909/50895321-14a18600-1406-11e9-9d99-b446b66302e2.png)

**Extra data (please complete the following information):**
 - Device: Mac Book 13" 2015
 - Device OS: Mojave
 - Browser: Firefox 62.0.3 (64 bits)
 - Decidim Version: 0.12
 - Decidim installation: participation.lillemetropole.fr

**Comment by lu-hamani** [comment]
@Paulinelonguet @virgile-dev 
Have you considered the option to shorten the step title ?

**Comment by lu-hamani** [comment]
Issue stale for nearly 2 weeks now. Hence I close.
