### ISSUE TITLE
Scopes are empty when doing an export of proposals

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#417]
**Describe the bug**
The field "scope/name" is empty when exporting proposals. It is empty whereas scopes are enabled in the participatory process configuration and user have used it for their proposals.

**To Reproduce**
1. Go to 'https://steamroll.osp.cat/processes/eveniet-et/f/3/'
2. Leave a proposal with a scope selected.
3. Go to the back office
4. Export the proposals

**Expected behavior**
Proposals that have scopes, the latter should appear in the corresponding field of the export. 

**Screenshots**
<img width="457" alt="screenshot 2019-01-16 at 17 59 32" src="https://user-images.githubusercontent.com/32680605/51265188-82c2eb80-19b8-11e9-8bfa-cfcc498d3efd.png">

**Comment by moustachu** [comment]
@moustachu Still need a fix for generating blank translation (`empty_translatable`) from `Organization.available_locales` instead of `Decidim.available_locales`

**+ Tests**
