### ISSUE TITLE
Change mail header color

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#424]
**Describe the solution you'd like**
Set the mails header with the same color (#0094AA) as the topbar for Villeurbanne

**Comment by moustachu** [comment]
<img width="609" alt="capture d ecran 2019-02-07 a 16 13 18" src="https://user-images.githubusercontent.com/464350/52420938-58fe6f80-2af3-11e9-8312-e6f09370280b.png">

**Comment by lu-hamani** [comment]
@moustachu 
I think it should be closer to this color :
<img width="55" alt="screenshot 2019-02-07 at 16 28 36" src="https://user-images.githubusercontent.com/32680605/52421984-72a0b680-2af5-11e9-8c3d-9ced226ec131.png">
😄

**Comment by moustachu** [comment]
Sorry !! @lu-hamani 

<img width="640" alt="capture d ecran 2019-02-07 a 16 54 35" src="https://user-images.githubusercontent.com/464350/52423872-3c653600-2af9-11e9-8c23-4005f7d5db67.png">
