### ISSUE TITLE
Don't receive the reset password mail

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#434]
**Describe the bug**
No matter how many times I try the process, I don't receive any mails.

**To Reproduce**
1. Go to 'https://steamroll.osp.cat/users/password/new'
2. Click on 'Send me instructions to rest my password'
3. See error

**Expected behavior**
I should receive a mail with the instructions

**Additional context**
Issue reported by Nanterre and Angers at least. Couldn't reproduce. 
Tickets are opened on the matter in support => #471718, #641382, #795692.

**Comment by armandfardeau** [comment]
@lu-hamani ![image](https://user-images.githubusercontent.com/20232956/53108236-f7002a00-3536-11e9-9475-68b254e9cf30.png)
![image](https://user-images.githubusercontent.com/20232956/53108571-8efe1380-3537-11e9-966c-4ed4cfa9fa30.png)
