### ISSUE TITLE
incorrect number of subscribers on a profil pages

### ISSUE THREAD

**Issue by Leopold194** [OpenSourcePolitics/decidim#437]
**Describe the bug**
My number of followers is at 3, when he should be at 0

**To Reproduce**
1. Go to 'https://demo.decidim.opensourcepolitics.eu/profiles/leopold/following'
2. See error

**Expected behavior**
The number of followers should be at 0

**Screenshots**
<img width="1137" alt="capture d ecran 2019-01-23 a 16 52 38" src="https://user-images.githubusercontent.com/46968525/51618832-4569db00-1f2f-11e9-8a38-d2010960d42c.png">

**Comment by lu-hamani** [comment]
Congrats Leopold for your first issue !!
Unfortunately, I have to close it since it is a bug that has already been reported and fix for the next version of Decidim.
