### ISSUE TITLE
Exports Decidim : piste d'amélioration pour réaliser un traitement automatique

### ISSUE THREAD

**Issue by TeaMhild** [OpenSourcePolitics/decidim#44]
1 / Les exports des commentaires de Decidim ne mentionnent pas la **catégorie** de la proposition à laquelle ils sont reliés. Ceci pose problème dans l'analyse du corpus car sans ces catégories les commentaires ne peuvent pas être traités de façon pertinente. 

2 / Il faudrait donc que dans les exports des commentaires, il y ait une colone "Category" comme dans les exports des propositions, qui mentionne le nom de la catégorie.

**Comment by armandfardeau** [comment]
@juliesimon Is this issue still pertinent or may we close it ?

**Comment by juliesimon** [comment]
It's something it would be nice to do but not an emergency. I classify it as `ice`
