### ISSUE TITLE
Comments module won't activate

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#449]
**Describe the bug**
Comments are deactivated for users while they are activated in back-office

**To Reproduce**
1. Go to 'https://dev.steamroll.osp.cat/processes/bp1/f/68/collaborative_drafts/34'
2. Go to 'https://dev.steamroll.osp.cat/admin/participatory_processes/bp1/components/68/edit'
3. See error

**Expected behavior**
Comments should be activated in this case

**Screenshots**
Activé
<img width="311" alt="screenshot 2019-01-31 at 09 20 15" src="https://user-images.githubusercontent.com/32680605/52041061-97b38900-2539-11e9-87d5-58a0fddd0902.png">

Pas bloqué
<img width="401" alt="screenshot 2019-01-31 at 09 21 12" src="https://user-images.githubusercontent.com/32680605/52041060-97b38900-2539-11e9-840b-519099c3e164.png">

Front
<img width="910" alt="screenshot 2019-01-31 at 09 21 36" src="https://user-images.githubusercontent.com/32680605/52041073-a26e1e00-2539-11e9-950b-f507aa2274b3.png">

**Comment by moustachu** [comment]
It happens when we use `osp-app` in `development` mode. Should be fixed soon.

**Comment by armandfardeau** [comment]
@lu-hamani We keep it open but this issue is not reproducible and should be fixed by switching to production.

**Comment by lu-hamani** [comment]
> @lu-hamani We keep it open but this issue is not reproducible and should be fixed by switching to production.

Ok. I know @moustachu mentioned that it was a problem linked to the dev version.
Still I can't test anything linked to comments for the version bump and that is what is really bothering.

**Comment by moustachu** [comment]
@lu-hamani SWITCH ! :twisted_rightwards_arrows:

I changed the serveur form `development` to `production`

--> https://dev.steamroll.osp.cat/processes/tprops/f/73/proposals/102
(previous link are KO)

Comments seems OK ;)

**Comment by lu-hamani** [comment]
> @lu-hamani SWITCH ! 🔀
> 
> I changed the serveur form `development` to `production`
> 
> --> https://dev.steamroll.osp.cat/processes/tprops/f/73/proposals/102
> (previous link are KO)
> 
> Comments seems OK ;)

👍
