### ISSUE TITLE
no display of proposals search result

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#453]
**Describe the bug**
As I search for propositions submitted by a specific author, I can see that the request wen through (number of projects change), but the proposal itself doesn't show nonetheless

**To Reproduce**
1. Go to https://dev.steamroll.osp.cat/processes/cumque-iusto/f/3/proposals
2. Research for a proposal left by "Thomas SA"
3. See error

**Screenshots**
<img width="1272" alt="screenshot 2019-01-31 at 16 16 12" src="https://user-images.githubusercontent.com/32680605/52063791-8f783f80-2573-11e9-86d5-a5ad7e4cb63f.png">

**Comment by lu-hamani** [comment]
@moustachu 
My spidey sens tells me we are on this one again https://github.com/OpenSourcePolitics/decidim/issues/153 again 🕸

**Comment by moustachu** [comment]
This is not related to search indexes rebuilding (#153). 

The search text area is **only** working for `title` and `body`. The authors names or nicknames are not searchable from this field. 

@lu-hamani This could be a nice enhancement but it's user related so its need to be discuss on metadecidim.
