### ISSUE TITLE
Search in admin proposals

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#454]
**User Story**
As an admin, I want to search for specific proposal when in the back office, so that I don't have to browse through lots of proposals before finding the one that I am looking for.
 
**Acceptance Criteria**
When I type in a keyword from a title or the name of category, I am only displayed the proposals linked to either of those.

**Mockups**
![search bar for admin proposals](https://user-images.githubusercontent.com/32680605/52114039-5095c880-260b-11e9-98e0-5e4d3a4bcce3.png)

**Comment by moustachu** [comment]
This one will be dealed with #456 so please look at the discussion on this one.
