### ISSUE TITLE
Budget text display of vote progress

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#455]
**User Story**
As a user, I want to understand quickly how many projects I have left to choose before I can confirm my vote so that I can proceed with my vote.

**Acceptance Criteria**
When I access the page to vote, I am shown how many projects I have to choose. As I select them, I am shown how many I have to still to choose and the projects I have already chosen.

**Mockups**
![progress bar grey](https://user-images.githubusercontent.com/32680605/53578007-06a2f280-3b77-11e9-9de8-906d0f822600.png)
![progress bar success](https://user-images.githubusercontent.com/32680605/53578008-073b8900-3b77-11e9-8b60-278d304f120b.png)
![progress bar secondary](https://user-images.githubusercontent.com/32680605/53578009-073b8900-3b77-11e9-9d95-ff117809570d.png)

**Comment by moustachu** [comment]
- **Level 1** because it seems like only displaying info already available
- Checked on _0.16-stable_ but not yet on _master_

**Comment by lu-hamani** [comment]
One precision about this : 
The "montant minimum cumulé" and "projets minimum" should be updated as the admin sets the numbers in the BO.
