### ISSUE TITLE
Wrong locale for comments email notification

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#457]
**Describe the bug**
Email notification for a comment are in english.

**To Reproduce**

Hello User,
Faire des sorties sur le thème des animaux has been commented. You can read the comment in this page:

You have received this notification because you are following "Faire des sorties sur le thème des animaux" or its author. You can unfollow it from the previous link.

**Expected behavior**
Email should be in french

**PR from BCN**
https://github.com/decidim/decidim/pull/4740

**Comment by lu-hamani** [comment]
@moustachu 
How are we on this one ? Never been able to reproduce even though I have a screenshot confirming its existence.
I see that you referenced it for the last 0.12 bump, but it is still "In progress" in the weekly issues.
 By the way => https://github.com/decidim/decidim/issues/4740

**Comment by moustachu** [comment]
Backported https://github.com/decidim/decidim/issues/4740 just to be sure ;)
