### ISSUE TITLE
Newsletter display with outlook/windows

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#458]
**Problem description**
The newsletter sent isn't displayed properly with recipient using outlook

**Screenshot**
![newsletter](https://user-images.githubusercontent.com/32680605/52123260-d7f03580-2625-11e9-9c7d-eee81e498d1d.png)

**Comment by moustachu** [comment]
The main issue here is that the images "that were dragged and dropped from a browser window" doesn't have the correct width. 

In most of the mailer, images fit inside the container CSS constraint but sometimes (hello Outlook) the images take their whole size. 

Please recall that images in rich text editor are not officially supported in Decidim.

**if used, images in Newsletter should have a maximum width of 542px**

![ol2019-vertical-allowed-1366](https://user-images.githubusercontent.com/464350/52440034-63cdfa00-2b1d-11e9-914d-03aa9016c62b.png)

> Outlook still has some paragraphs padding issue but it was not the issue here.
