### ISSUE TITLE
2 collaborative drafts created instead of 1

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#464]
**Describe the bug**
I created a collaborative draft. As I wanted to modify it, I encountered an error (#463). I clicked the back btn of my browser and then saw that it duplicated the collaborative draft that I created. 

**To Reproduce**
1. Go to 'https://dev.steamroll.osp.cat/processes/tprops/f/73/collaborative_drafts'
2. See error

**Expected behavior**
The second collaborative draft shouldn't have been created.

**Screenshots**
<img width="952" alt="screenshot 2019-02-06 at 09 15 11" src="https://user-images.githubusercontent.com/32680605/52328393-bd380b00-29ef-11e9-98d6-014e75e8e366.png">

**Comment by moustachu** [comment]
### Fixed with last 0.16-stable bump ([307e4ed](https://github.com/OpenSourcePolitics/decidim/commit/307e4ed9f9096c32e148d7f8f2d2756429149708)) 🎉 ✨ 

--> https://dev.steamroll.osp.cat/processes/tprops/f/73/collaborative_drafts
