### ISSUE TITLE
ArgumentError in Decidim::Proposals::CollaborativeDraftsController#publish

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#466]
**Describe the bug**
Can't publish a proposal. But to be linked to #464. Fixing #464 renders this issue useless.

**To Reproduce**
1. Publish the collaborative draft you created
2. See error

**Expected behavior**
Collaborative draft should be published

**Screenshots**
<img width="1440" alt="screenshot 2019-02-06 at 10 23 13" src="https://user-images.githubusercontent.com/32680605/52331740-3ab44900-29f9-11e9-9dd8-7b7a1da09e5e.png">

**Comment by moustachu** [comment]
### #464 fixed with last 0.16-stable bump ([307e4ed](https://github.com/OpenSourcePolitics/decidim/commit/307e4ed9f9096c32e148d7f8f2d2756429149708)) 🎉 ✨ 

--> https://dev.steamroll.osp.cat/processes/tprops/f/73/collaborative_drafts

**Comment by lu-hamani** [comment]
Fixing #464 did fix this one as well.
