### ISSUE TITLE
Comment on debates doesn't work

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#467]
**Describe the bug**
Impossible to comment on a debate even if config is set to allow comments.

**To Reproduce**
1. Go to https://dev.cndp.opensourcepolitics.eu/processes/pngmdr-5/f/12/debates/1
2. Try to comment
3. Check config in admin https://dev.cndp.opensourcepolitics.eu/admin/participatory_processes/pngmdr-5/components/12/edit
<img width="966" alt="capture d ecran 2019-02-06 a 10 30 30" src="https://user-images.githubusercontent.com/11473995/52332146-2c1a6180-29fa-11e9-8a2e-234faacb2f39.png">

**Expected behavior**
I should be able to comment

**Extra data (please complete the following information):**
 - Decidim installation: https://dev.cndp.opensourcepolitics.eu

**Comment by lu-hamani** [comment]
Thanks @virgile-dev. This issue has already been reported #449 as mentioned in the instructions to test the 0.16 version.
