### ISSUE TITLE
/admin/officializations shows all users across all organizations

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#47]
We have a weird behaviour since we upgraded to 0.9 the /admin/officializations is showing all the users accross all the organizations. For example if signup on org A, the user will also be listed on org B in /admin/officializations. Is the same happening for you ? Thanks in advance.

The decidim core team submitted a patch : 
https://github.com/decidim/decidim/pull/2912

It'd be great to apply it to our repo.

**Comment by juliesimon** [comment]
Ils ont ouvert une PR pour merger le patch dans leur branche `0.9-stable`.
Il faudra, quand ce sera ok, merger  `decidim/decidim#0.9-stable` avec `OpenSourcePolitics/decidim#0.9-stable`.
Ça veut aussi dire pour nous un upgrade de la version 0.9.2 à la version 0.9.3 (qui est celle de la branche `decidim/decidim#0.9-stable`)

**Comment by mrcasals** [comment]
Bonjour!

On va publiquer version 0.9.4 demain probablement, on a trouvé un autre bug et on travaille pour le solutionner 😄
