### ISSUE TITLE
No button to go back to Proposals 

### ISSUE THREAD

**Issue by antoinegaboriau1** [OpenSourcePolitics/decidim#470]
Once I click on Collaborative drafts, there is no button to get me back to Proposals. Maybe we could add a new "Accéder aux propositions" button on the Collaborative drafts page.

**Comment by lu-hamani** [comment]
@antoinegaboriau1 indeed there is some thinking to do here. How about having collaborative drafts with the proposals ?

**Comment by antoinegaboriau1** [comment]
I think it would only bring confusion to the user because the proposals are a list of _published_ proposals whereas the collaborative drafts are _yet to be published_.
