### ISSUE TITLE
Maximum budget not reached but vote is blocked

### ISSUE THREAD

**Issue by antoinegaboriau1** [OpenSourcePolitics/decidim#471]
When i'm allocating budget to projects, I can't vote for more than five projects even if I have still not reached the maximum budget.

Don't know if this is due to an admin configuration or if this truly is a bug though.
https://dev.steamroll.osp.cat/processes/tests-budgets/f/79/projects?participatory_process_slug=tests-budgets&random_seed=0.3444070113118167

**Comment by lu-hamani** [comment]
@antoinegaboriau1 indeed it is not a bug. Admin configuration is the culprit. I reported it with #468
