### ISSUE TITLE
Design bug : budget jar stripes

### ISSUE THREAD

**Issue by antoinegaboriau1** [OpenSourcePolitics/decidim#472]
The budget allocating jar is filled with stripes when no project is selected. When I select a project, the stripes disappear only in part of the jar. See screenshot.
![opera instantane_2019-02-06_120528_dev steamroll osp cat](https://user-images.githubusercontent.com/35924332/52337462-fc725600-2a07-11e9-9256-50425271fdad.png)

**Comment by lu-hamani** [comment]
@moustachu 
Tested and approved 👍
