### ISSUE TITLE
Translation errors

### ISSUE THREAD

**Issue by antoinegaboriau1** [OpenSourcePolitics/decidim#473]
Here are the translation errors I noticed:

- [x] - when I log in, "Bienvenue!" should be "Bienvenue !"
- [x] - on the main Collaborative drafts page, "Ordre des brouillons par:" should be "Trier les brouillons par :"
- [x] - and "la plupart ont contribué" should be "Nombre de contributions"
- [x] - a Collaborative draft, when validated, is turned into a Proposal. But it is translated in French by "Projet collaboratif".
- [x] - the "Authors" section, "Réunions" should be "Rencontres"
- [x] - in the "State" section, "Ouvrir" should be "Ouvert"
- [x] - in a Collaborative draft, "voir d'autres versions" should be "voir les autres versions".
- [x] - when you pass on the comment-square icon of the version box on the right, "commentaires" should have a capital C. 
- [x] - in the "State" section of "Amendments", "Accepté" should be "Acceptés", "Evaluer les" should be "En cours d'évaluation" and "Rejeté" should be "Rejetés". 
- [x] - in the "Type" section of "Amendments", "Modifications" should be "Propositions amendées".
- [x] - in a survey, when I don't tick all choices of a ranking multiple choices question, translation says "Choices ne sont pas complets" instead of "Vous n'avez pas coché toutes les cases". 
- [x] - in the budget vote, when I have to allocate a budget, it says "Affecté à" instead of "Budget affecté".
- [x] - When I sign up for a Meeting, the notification I get is in English. It says "Meeting registration notification event" when it should say "Notification d'inscription à une réunion".

Enjoy :)

**Comment by lu-hamani** [comment]
Will be rewritten as list and with screenshots.

**Comment by lu-hamani** [comment]
> * [ ]  - in a survey, when I don't tick all choices of a ranking multiple choices question, translation says "Choices ne sont pas complets" instead of "Vous n'avez pas coché toutes les cases".
> * [ ]  - When I sign up for a Meeting, the notification I get is in English. It says "Meeting registration notification event" when it should say "Notification d'inscription à une réunion".

Those two seems to be bugs rather than translations
