### ISSUE TITLE
Participatory process navbar "more" dropdown functionnality behaving weirdly

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#474]
**Describe the bug**
1. Menu entry go on a second line and breaks layout.
2. Menu entry that are too long don't display well.

**To Reproduce**
1. Go to https://dev.cndp.opensourcepolitics.eu/assemblies/cpdp-pngmdr-5
2. Go to https://dev.cndp.opensourcepolitics.eu/processes/pngmdr-5 and click on "Plus"

**Expected behavior**
There shouldn't be a second line, the entry on the second line should be inside "Plus"

**Screenshots**
1. <img width="1326" alt="capture d ecran 2019-02-06 a 12 14 19" src="https://user-images.githubusercontent.com/11473995/52339728-321a3d80-2a0e-11e9-9a1e-a57a431a358b.png">

2. <img width="1349" alt="capture d ecran 2019-02-06 a 12 52 20" src="https://user-images.githubusercontent.com/11473995/52339735-37778800-2a0e-11e9-9c1a-d76442bbdcc1.png">

**Extra data (please complete the following information):**
 - Decidim Version: 0.16
 - Decidim installation: dev.cndp.opensourcepolitics.eu

**Comment by lu-hamani** [comment]
@moustachu 
Given the expected behaviour from @virgile-dev this one is not resolved. See following screenshot : 
<img width="1319" alt="Screenshot 2019-03-14 at 18 07 11" src="https://user-images.githubusercontent.com/32680605/54376789-1bf24380-4684-11e9-9604-e2c3852ea502.png">

**Comment by moustachu** [comment]
"Can't fix"

This menu system is designed to hold 6 _inline_ menu and the other in the "Plus" dropdown. It's not designed to automatically put elements outside the viewport / container in the dropdown (you wish 😁). 

What I did fix was the second screenshot showing long menu item not wrapping to next line (see capture) 

<img width="1295" alt="Capture d’écran 2019-03-18 à 22 49 46" src="https://user-images.githubusercontent.com/464350/54566553-74ea1080-49d1-11e9-886c-d593640607d5.png">

What could be feasible (but that was not the demand) is to force line break inside **each** menu item
