### ISSUE TITLE
Exporting proposals and collaborative drafts

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#479]
**User Story**
As an admin, I want to know which proposals have been collaborative drafts before being published, so that I can analyze the proposal accordingly.

**Acceptance criteria**
When I export proposals, a column indicates if the proposals were collaboratives drafts before with a "yes" or "no" mention.

**Comment by armandfardeau** [comment]
@lu-hamani Currently it's not possible to know if a proposal comes from a collaborative draft. Is it something you really need?
