### ISSUE TITLE
Comments don't appear with Internet Explorer

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#483]
Bug already documented there : 
https://github.com/decidim/decidim/issues/3562#issue-328489325

Seems there is already a solution : 
https://github.com/City-of-Helsinki/decidim-helsinki/issues/25

**Comment by moustachu** [comment]
Will be fixed **BUT** I would greatly appreciate if this blog post could be forwarded to our client that report this kind of bug : 

https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/The-perils-of-using-Internet-Explorer-as-your-default-browser/ba-p/331732

**Comment by lu-hamani** [comment]
> Will be fixed **BUT** I would greatly appreciate if this blog post could be forwarded to our client that report this kind of bug :
> 
> https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/The-perils-of-using-Internet-Explorer-as-your-default-browser/ba-p/331732

We'll do
