### ISSUE TITLE
Darken separators between processes status

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#498]
**Is your feature request related to a problem? Please describe.**
The separation between the different status of a process aren't marked enough

**Describe the solution you'd like**
Darken the lines between processes statuses in processes index page

**Screenshots**
![screenshot-user-images githubusercontent com-2019 02 21-11-46-30](https://user-images.githubusercontent.com/464350/53163763-1cd90d80-35cf-11e9-80ff-41dd9028b517.png)

**Comment by moustachu** [comment]
### Before
<img width="451" alt="capture d ecran 2019-02-21 a 11 51 17" src="https://user-images.githubusercontent.com/464350/53163804-2febdd80-35cf-11e9-96fe-d2fed8e47108.png">

### After 
<img width="451" alt="capture d ecran 2019-02-21 a 11 50 58" src="https://user-images.githubusercontent.com/464350/53163817-3712eb80-35cf-11e9-9d90-db38ff7c7969.png">
