### ISSUE TITLE
Inscriptions des organisations

### ISSUE THREAD

**Issue by ludivinecp** [OpenSourcePolitics/decidim#5]
Retirer le champ "Numéro d'identification de l'organisation" lors de l'inscription en tant qu'organisation / collectif 
<img width="587" alt="screen shot 2017-12-28 at 11 38 36" src="https://user-images.githubusercontent.com/12518762/34408371-bf66a032-ebc3-11e7-80d4-0b078ff86ba2.png">

by @virgile-dev

**Comment by virgile-dev** [comment]
Le numéro d'identification de l'orga est utilisé comme foreign key. On va donc planquer le champ et générer un automatiquement un numéro unique.
