### ISSUE TITLE
Survey export mixed answers

### ISSUE THREAD

**Issue by antoinegaboriau1** [OpenSourcePolitics/decidim#501]
When I open a survey export as a LibreOffice spreadsheet, multiple choice answers are separated and so it is disordering the answers. See screenshot : 
![export enquete](https://user-images.githubusercontent.com/35924332/53081403-18dbbb80-34fb-11e9-8b21-c5a38b38fb6b.png)
Both highlighted answers correspond to the second question of the survey.

**Comment by lu-hamani** [comment]
@antoinegaboriau1 
Which format did you choose for your export ?

**Comment by antoinegaboriau1** [comment]
.csv !

**Comment by lu-hamani** [comment]
> .csv !

As i suspected, the problem comes from the file format and the way you set up OpenOffice to read the info.
If you configure OpenOffice not to separate the content by commas, you should be fine.
Hence I close this issue
