### ISSUE TITLE
Testing vote pour abstention contre

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#502]
**Describe the bug**
First it seems I can't create a proposal. The proposal is actually created but I can access its details
undefined method `weighted_by?' for #<Decidim::Proposals::Proposal:0x00007fe621354f80>
Same as #505

**To Reproduce**
1. Go to [](https://dev.steamroll.osp.cat/processes/tprops/f/68/proposals/)
2. Create a proposal and advance until the "Publish" step
3. Click on "Publish" and see error
4. Go back to [](https://dev.steamroll.osp.cat/processes/tprops/f/68/proposals/)
5. Click on the created proposal then see error

**Expected behavior**
Shouldn't encounter any errors when creating or accessing a proposal

**Screenshots**
![screenshot-dev steamroll osp cat-2019 02 20-11-49-09](https://user-images.githubusercontent.com/32680605/53086806-1894ed80-3506-11e9-9c67-6c20b4d304b2.png)

**Comment by virgile-dev** [comment]
I've also done some testing on demo.decidim.opensourcepolitics.eu.
I activated it on https://demo.decidim.opensourcepolitics.eu/processes/demo-decidim/f/69/
<img width="657" alt="capture d ecran 2019-02-20 a 14 07 45" src="https://user-images.githubusercontent.com/11473995/53094005-4172ae00-3519-11e9-9796-c98136e1bbea.png">

Several issues : 
- the vote buttons are not displayed on the proposal cards on the index
<img width="1196" alt="capture d ecran 2019-02-20 a 14 07 29" src="https://user-images.githubusercontent.com/11473995/53094030-4cc5d980-3519-11e9-88b4-ef5437bb00e5.png">
-  while they are present on the proposal page, clicking on the buttons doesn't work, the counter doesn't change.
<img width="1209" alt="capture d ecran 2019-02-20 a 14 08 41" src="https://user-images.githubusercontent.com/11473995/53094036-53545100-3519-11e9-8ba8-928081148c8f.png">

**Comment by moustachu** [comment]
👍 There was a few missing pieces from the 0.12 merge. 

The only thing that I didn't fix / update is the ability to _update_ a current vote. Right now you have to unvote then vote again to change your vote between the 3 values.

**Comment by lu-hamani** [comment]
> 👍 There was a few missing pieces from the 0.12 merge.
> 
> The only thing that I didn't fix / update is the ability to _update_ a current vote. Right now you have to unvote then vote again to change your vote between the 3 values.

@moustachu 
actually leaving it out might not be a bad idea. It adds a click yet this addition can work as safeguard for an unintended change from the user
