### ISSUE TITLE
Background highlight bug

### ISSUE THREAD

**Issue by antoinegaboriau1** [OpenSourcePolitics/decidim#508]
In the left sidebar of the admin panel (Club des utilisateurs organization (v0.12)), when I click on any category other than "Utilisateurs", the selected category is highlighted with a white background and a purple vertical line. 
But the highlights are absent when I select "Utilisateurs". See screenshots : 

![utilisateurs](https://user-images.githubusercontent.com/35924332/53184434-4741bf80-35fd-11e9-9642-55537a7e9e73.jpg)

![bug graphisme](https://user-images.githubusercontent.com/35924332/53184504-6f312300-35fd-11e9-8b57-10f41bddfa65.jpg)

**Comment by lu-hamani** [comment]
@moustachu 
Good to go !
