### ISSUE TITLE
Typo in statistics

### ISSUE THREAD

**Issue by antoinegaboriau1** [OpenSourcePolitics/decidim#51]
On club.decidim.opensourcepolitics.eu, there is a typo in the activity statistics at the bottom of the page : 

![typo in statistics](https://user-images.githubusercontent.com/35924332/37290156-bd7fcbcc-260b-11e8-81fb-7b2ba8ce6fc5.png)

It should print "1 PROPOSITION" and "1 REUNION".

**Comment by armandfardeau** [comment]
@antoinegaboriau1 Is this issue still pertinent or may we close it ?
