### ISSUE TITLE
No error message when exceeding characters limit for a user conversation

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#512]
**Describe the bug**
After I wrote a long message (over 1000 characters) to a user. My message won't be sent and I have no message as to say why.

**To Reproduce**
1. Go to 'https://dev.steamroll.osp.cat/conversations/1'
2. Write a message over 1000 characters long
3. Click on 'Send'

**Expected behavior**
I should be shown a message telling me my message exceeds the 1000 characters limit

**Comment by moustachu** [comment]
Partial fix for now : 
- the max 1000 has been duplicated to the form Object so the text area cannot take more than 1000
- But there isn't any error message, you just can't type any more than 1000

**Comment by lu-hamani** [comment]
> Partial fix for now :
> 
> * the max 1000 has been duplicated to the form Object so the text area cannot take more than 1000
> * But there isn't any error message, you just can't type any more than 1000

@moustachu 
You mean that there is at least an error message when trying to post a message over 1000 caracters even though it doesn't state specifically that the message length is the error source ?

**Comment by lu-hamani** [comment]
@moustachu 
Tested and I am afraid the problem is not solved with your fix.
I clearly saw my message being reduced to 1000 characters. As I know what I am testing I wasn't surprised. 
Yet for a standard user, there is no clear indication of what is actually happening.
An error message or flash alert are more appropriate and what should we strive for.
