### ISSUE TITLE
Progress Bar color changing according to vote status

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#513]
**User Story**
As a user, I want to see clear indicators that my vote has been taken into account and or saved, so that i want go through with my vote.

Feature/ux budget enhanced #509

**Acceptance Criteria**
When I am on the voting page, before i selected any project, the progress bar is grey. When I select a project the progress bar becomes $secondary. Once I confirmed my vote the progress bar becomes $success.

**Mockups**
![progress bar grey](https://user-images.githubusercontent.com/32680605/53575276-8037e200-3b71-11e9-8610-72884512d976.png)
![progress bar secondary](https://user-images.githubusercontent.com/32680605/53575277-8037e200-3b71-11e9-9090-8cfead8a36c4.png)
![progress bar success](https://user-images.githubusercontent.com/32680605/53575278-8037e200-3b71-11e9-80dd-7924840acd46.png)

**Comment by armandfardeau** [comment]
Fixed in: 7b30723cc3c4b1e0b6f5c4202b142ef2c69064f9
