### ISSUE TITLE
Generation.s boot

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#515]
**Version to boot**
- [x] - 0.16

**Design customization**
- [x] - Platform URL = agora.generation-s.fr
- [x] - Platform email address = agora@generation-s.fr
- [x] - SMTP = OSP
- [x] - Primary color = #E00a63 (pink)
- [x] - Secondary color = #30a5af (green)
- [x] - Primary navbar ("Topbar") + mail header & footer = #FFFFFF (white) 
- [x] - Font = Roboto
- [x] - Remove filters on cover/banners
- [x] - Geocoding = sent to CTO
- [x] - Matomo
- [x] - Uptime Robot
- [x] - Sentry

**Additional questions**
- There might be a few thousand active users during the couple of weeks following the launch, we are going to need a strong server.

**Comment by valentinchaput** [comment]
Waiting for the client's last confirmation today. We don't move until then.

**Comment by moustachu** [comment]
@valentinchaput 
https://github.com/OpenSourcePolitics/osp-app/tree/alt/generations

![donor osp cat](https://user-images.githubusercontent.com/464350/53889670-12832e80-4027-11e9-8f3c-048601bf65e3.jpg)

<img width="1178" alt="capture d ecran 2019-03-06 a 15 43 16" src="https://user-images.githubusercontent.com/464350/53889714-2af34900-4027-11e9-8895-d6d04b45e435.png">

**Comment by valentinchaput** [comment]
@moustachu, when adding a footer logo, pages' links move to the right whereas they should remain centered. How to fix this issue? 

<img width="1220" alt="capture d ecran 2019-03-07 a 13 25 50" src="https://user-images.githubusercontent.com/10398564/53956674-8f241480-40dc-11e9-84fd-95e93cac39ba.png">

**Comment by valentinchaput** [comment]
Friday evening status check for @moustachu : 
- Redirection done on their side. Our turn to close the loop. 
- Geocoding codes sent to our almighty CTO.
- I add two tasks for the producTech team: add Matomo+UptimeRobot

Trad issues for @lu-hamani 
- On user confirmation link: Nickname > Pseudonyme
- BO date picker on a consultation info page: "format attendu **jj/mm/aaaa**" 
- "Page" feature is labelled as "Titre" which does not make sense 
- On a group creation page, a document number is necessary > we should add an explanation (either "put your SIRET" or "whatever works")... 

Questions:
- Current external links written on the back office are redirected to the platform (ex: organization url on the footer should go to generation-s.fr but evolve into donor.osp.cat/generation-s.fr). This unexpected behavior did not occur on 0.12. 
- On highlighted banners, image is compulsory but * is missing (+ I think it was not compulsory on 0.12). 

Calendar:
- Launch delayed to March 20th
- Anticipated big traffic/activity until March 27th

**Comment by valentinchaput** [comment]
@moustachu @lu-hamani last checklist before launch **tonight**: 
je la fais en français pour gagner du temps... 

Invitations : 
- [ ] Spec : Il faut que seuls les utilisateurs qui vont être invités accèdent et puissent voter sur les **deux** concertations privées (programme d'un côté https://agora.generation-s.fr/processes/programme-europeennes-2019, liste de l'autre https://agora.generation-s.fr/processes/vote-liste-europeennes-2019). _Je laisse tomber mon histoire de masquage de l'inscription pour les autres car on va se perdre comme à Orsay, je vais rattraper ça par du texte en back-office._ 
- [ ] Configuration SMTP agora@generation-s.fr
- [ ] Changer le texte du mail d'envoi : 
_Titre :_ Rejoignez l'Agora Génération·s !
_Corps :_ Bonjour {%name},
Vous êtes invité·e à participer à l'Agora Génération·s. Vous pouvez accepter cette invitation en cliquant sur le lien ci-dessous : 
Accepter l'invitation _[intégrer le lien plateforme]_
Attention : Cette invitation expirera dans une semaine. Votre compte ne sera pas créé avant d'avoir cliqué sur le lien puis défini le surnom que vous voulez utiliser sur la plateforme et votre mot de passe.
En cas de question, veuillez vous adresser à agora@generation-s.fr"

Traductions :
- [ ] (CRITIQUE) Sur la page de confirmation qui s'ouvre quand tu cliques sur le lien d'activation de compte reçu par mail : **Nickname >> Surnom** 
- [ ] (Moins important) Texte automatique de case à cocher sur des enquêtes "En participant, vous acceptez ses conditions d'utilisation" il faut changer **ses >> les**

Autres : 
- [ ] Configuration Uptime + Matomo
