### ISSUE TITLE
Updating my geolocation when submitting definitively a proposal

### ISSUE THREAD

**Issue by leokante** [OpenSourcePolitics/decidim#523]
**Describe the bug**
Updating my geolocation when submitting definitively a proposal does not work 

**To Reproduce**
1. Go to Proposals and create a new one
2. Click on submit
3. When changing the location of my proposal directly on the map, an error occurs 

**Expected behavior**
I expect my location to be changed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/43004803/53899054-9cd48e00-4039-11e9-9c53-c71c53597727.png)

![image](https://user-images.githubusercontent.com/43004803/53899021-8b8b8180-4039-11e9-9175-d049f00f6a33.png)

**Extra data (please complete the following information):**
 - Device: [Desktop]
 - Device OS: [Windows 10]
 - Browser: [Firefox]
 - Decidim Version: [0.16]
 - Decidim installation: [Demo]

**Comment by lu-hamani** [comment]
@moustachu 
Could you take a look at Sentry for this one please ? I can't access it hence I can't qualify the bug
