### ISSUE TITLE
Information not needed when submitting my proposal

### ISSUE THREAD

**Issue by leokante** [OpenSourcePolitics/decidim#524]
**Describe the bug**
When I am filing the information needed for my proposal. Some informations not need are displayed (cf. Screenshot)

**To Reproduce**
1. Go to New proposals (step 2)
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/43004803/53899628-ea9dc600-403a-11e9-807d-989792c0cbc9.png)

**Extra data (please complete the following information):**
 - Device: [Desktop]
 - Device OS: [Windows 10]
 - Browser: [Firefox]
 - Decidim Version: [0.16]
 - Decidim installation: [Demo]

**Comment by lu-hamani** [comment]
@moustachu 
Bug is fixed.
We'll see if your map pop preview pleases the user. To be honest I am not quite convinced.
Also, when did we switch to Open Street Maps rather than Here.com ?

**Comment by moustachu** [comment]
--> Map tiles are from OSM but the Geolocalisation Service comes from Here.com

Not quite sure myself about the popup but the forms were beginning to be looooong. 

With the work done, it's quite easy to change the popup for an accordeon panel
