### ISSUE TITLE
Moving cursor on map doesn't work

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#526]
it seems the custom leaflet theme doesn't work with the new functionnality.
<img width="479" alt="capture d ecran 2019-03-08 a 10 19 57" src="https://user-images.githubusercontent.com/11473995/54019714-24321680-418c-11e9-9ce5-f12e8d78a6d7.png">

This is an emergency as their launching a consultation using this today. 
Bug can be seen here using mako : https://dev.mel.osp.cat/processes/test-geoloc/f/49/proposals/893/preview

**Comment by moustachu** [comment]
### @virgile-dev Fixed ✅
