### ISSUE TITLE
Hashtags and mail notifications

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#532]
**Describe the bug**
Hastag aren't displayed as text but rather the code behind it on multiple mail notifications. As for #465 

**To Reproduce**
1. Trigger the following notifications that involve a hashtag : 
- amendment creation
- proposal/amendment comment
2. See error

To reproduce te bug, you can go [there](https://dev.steamroll.osp.cat/processes/tprops/f/73/)
**Expected behavior**
Hashtags should be displayed as text.

**Screenshots**
<img width="1108" alt="Screenshot 2019-03-11 at 17 47 04" src="https://user-images.githubusercontent.com/32680605/54203213-12c17500-44d2-11e9-87fe-e6ca0e25a7fc.png">
<img width="1105" alt="Screenshot 2019-03-11 at 17 46 47" src="https://user-images.githubusercontent.com/32680605/54203214-135a0b80-44d2-11e9-8a36-408d966477ff.png">

**Comment by moustachu** [comment]
### Tough one ! 
_Please note that these are very specific sets of configuration !_

1. Amendments & Hashtags needs to be enabled at he same time
2. User is **explicitly** putting `#something` in the title 

**Case 1.** --> 🔴 Need to be postponed. This is not fixed on `master`, the _Amendments & Hashtags_ problems hasn't been addressed yet 

**Case 2.** --> ✅ The HashtagRenderer has been added to the resource title processing (without the link as it is used in the mail subject)

<img width="876" alt="Capture d’écran 2019-03-12 à 20 20 43" src="https://user-images.githubusercontent.com/464350/54229359-651b8980-4504-11e9-9ec7-d9d69f397c2a.png">

**Comment by lu-hamani** [comment]
Several tests have been conducted and there are a few things still causing problem.

1. the "%" by the end of username in the mail object 
<img width="1106" alt="Screenshot 2019-03-14 at 17 19 52" src="https://user-images.githubusercontent.com/32680605/54373716-0ed25600-467e-11e9-89f4-b2f126dc6c3c.png">

2.
<img width="589" alt="Screenshot 2019-03-14 at 17 17 27" src="https://user-images.githubusercontent.com/32680605/54373717-0ed25600-467e-11e9-846d-3bee6b3c6dee.png">
