### ISSUE TITLE
RIVP Boot

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#535]
**Version**
- [x] - 0.16

**Design**
- [x] - Platform URL = https://budget-participatif.rivp.fr/
- [x] - Platform email adress = budget-participatif.rivp@copas.coop
- [x] - Primary color = #F1A109
- [x] - Secondary color = #4F98CC
- [x] - Primary navbar ("Topbar") + mail header & footer = #ffff
- [x] - Remove filters on cover/banners
- [x] - Geocoding
- [x] - Matomo
- [x] - Uptime Robot
- [x] - Sentry
- [x] - darken sign_up/sign_in buttons on the navbar
- [x] - Elogie custom trad with "Concertation >> Résidences"

**Comment by valentinchaput** [comment]
update on RIVP for you @lu-hamani. 2 main actions remaining at this stage: 
- darken sign_up/sign_in buttons on the navbar
- use Elogie custom trad with "Concertation >> Résidences"

**Comment by moustachu** [comment]
@lu-hamani @valentinchaput All good !
