### ISSUE TITLE
Can't upload images on NEC platform

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#537]
**Describe the bug**
I can't upload png images, neither on my profile nor in the admin panel.

**To Reproduce**
1. Go to admin panel with mako
2. Click on Settings > Appearance
3. Try uploading logos

**Expected behavior**
The same images (.png) do upload on other platforms. 

**Screenshots**
<img width="697" alt="Capture d’écran 2019-03-14 à 19 41 29" src="https://user-images.githubusercontent.com/10398564/54383108-a3927f00-4691-11e9-99f3-d98a775c0f23.png">
<img width="779" alt="Capture d’écran 2019-03-14 à 19 42 04" src="https://user-images.githubusercontent.com/10398564/54383109-a3927f00-4691-11e9-9813-a8d89584bda8.png">

**Extra data (please complete the following information):**
 - Device: Desktop
 - Device OS: MacOS
 - Browser: Firefox
 - Decidim Version: 0.16 (new boot)
 - Decidim installation: nec.osp.cat

**Additional context**
Any forgotten step during deploy?

**Comment by moustachu** [comment]
@valentinchaput Sorry about that, it was because of the DNS that was already set as "numerique-en-commun.fr" instead of "nec.osp.cat" ...

### Fixed ✅
