### ISSUE TITLE
Word Break is wrong

### ISSUE THREAD

**Issue by leokante** [OpenSourcePolitics/decidim#550]
**Describe the bug**
The title isn't displayed correctly

**To Reproduce**
1. Go to https://in.opensourcepolitics.eu/processes/orcs-2019/f/68/results/98
2. See error

**Expected behavior**
I would expect the sentence " Etat d'avancement" to be written on a single line. 

**Screenshots**
![image](https://user-images.githubusercontent.com/43004803/54920278-2245b280-4f03-11e9-8887-29e6182a7e0f.png)

**Stacktrace**
If applicable, add the error stacktrace to help explain your problem.

**Extra data (please complete the following information):**
 - Device: [ Desktop]
 - Device OS: [eWindows 10]
 - Browser: [Firefox]
 - Decidim Version: [0.16]
 - Decidim installation: [In.opensourcepolitics.eu]

**Additional context**
It may be because of the fact that the new translation would be too long to be displayed as one word

**Comment by armandfardeau** [comment]
@leokante What would you like? "Etat d'avancement" cannot be write on a single line

**Comment by leokante** [comment]
"Progression" might be short enough ?

**Comment by lu-hamani** [comment]
> @leokante What would you like? "Etat d'avancement" cannot be written on a single line

@armandfardeau 
I take it from here
