### ISSUE TITLE
Proposal counter = 1 even if no proposal was submitted

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#551]
**Describe the bug**
Proposal counter = 1 even if no proposal was submitted

**To Reproduce**
1. Go to https://participation.lillemetropole.fr/processes/concertationwattreloslesvillas
2. See error

**Expected behavior**
Counter should be 0

**Screenshots**
![imageGT0O](https://user-images.githubusercontent.com/11473995/54930416-870b0800-4f17-11e9-9074-7d06c594ccd1.png)

**Extra data (please complete the following information):**
 - Decidim installation: MEL

**Comment by lu-hamani** [comment]
@virgile-dev 
Corrected in 0.16
Do you feel the client can wait or shall we do something right away ?

**Comment by lu-hamani** [comment]
@virgile-dev 
As we talked about it I close this issue. The client will soon be on 0.16
