### ISSUE TITLE
Both buttons display "Soutenir" on MEL instance

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#552]
**Describe the bug**
Both buttons display "Soutenir" on MEL instance

**To Reproduce**
1. Go to https://participation.lillemetropole.fr/processes/granddebatmel/f/111/proposals/387
2. See error

**Screenshots**
<img width="962" alt="Capture d’écran 2019-03-25 à 16 07 54" src="https://user-images.githubusercontent.com/11473995/54930712-0698d700-4f18-11e9-901e-24c4caf8d5e5.png">

**Extra data (please complete the following information):**
 - Decidim installation: MEL

**Comment by lu-hamani** [comment]
@virgile-dev 
As the client has the 0.16 version and the translation is correct, I close this issue.
