### ISSUE TITLE
Still possible to reply to comments when comments are blocked

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#553]
**Describe the bug**
Still possible to reply to comments when comments are blocked

**To Reproduce**
1. Go to https://participez.nanterre.fr/processes/parc-anciennes-mairies-2019/f/50/proposals/208
2. Click on "Répondre" on any comments
3. See that you can add a reply even if the config is set to not accept new comments

**Expected behavior**
When comments are desactivated you shouldn't be able to reply

**Screenshots**
<img width="889" alt="Capture d’écran 2019-03-25 à 17 05 20" src="https://user-images.githubusercontent.com/11473995/54935182-0f8da680-4f20-11e9-86ba-db8faaa559f5.png">

**Extra data (please complete the following information):**
 - Decidim installation: Nanterre

**Comment by lu-hamani** [comment]
@virgile-dev 
The link you provided redirect to page where you can't comment since comments are deactivated. Are you sure you provided the right link ?

**Comment by virgile-dev** [comment]
Click on "Répondre" you'll see that you can post a reply. (please don't do it on a prod instance).

**Comment by lu-hamani** [comment]
@virgile-dev 
I managed to reproduce it. thanks

**Comment by lu-hamani** [comment]
To backport from BCN = https://github.com/decidim/decidim/pull/4938
