### ISSUE TITLE
Unwanted contents appear in Activity feed on homepage

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#556]
**Describe the bug**
2 parts of the same problem: moderated & private content appear publicly on Activity feed on homepage. 

**To Reproduce**
1. Go to https://club.decidim.opensourcepolitics.eu/ 
_1bis. Log out._
2. Scroll down to "Activités récentes"
3. Click on whichever one labelled as "Espace membres" (which is a private assembly)
Summary: you can see contents from private spaces while you are not a private member. 

**Expected behavior**
One should only see contents from spaces he has access to. 
+ moderated proposals/comments should not be displayed. 

**Screenshots**
Public access to private content
![Screenshot_2019-03-26 Club utilisateurs de Decidim](https://user-images.githubusercontent.com/10398564/55020631-8053c200-4ff7-11e9-9e78-91b447425e0e.png)

Visibility of moderated proposals
![Screenshot_2019-03-26 Numérique en commun s](https://user-images.githubusercontent.com/10398564/55020666-9497bf00-4ff7-11e9-8425-98b236ca83af.png)

**Stacktrace**
If applicable, add the error stacktrace to help explain your problem.

**Extra data (please complete the following information):**
 - Device: Desktop
 - Device OS: MacOS
 - Browser: Firefox
 - Decidim Version: 0.16
 - Decidim installation: Club, IN, NEC... 

**Additional context**
Not critical but you should check it soon.

**Comment by armandfardeau** [comment]
@valentinchaput As far as I know, this is not a bug. This is the intended behavior of Decidim, a private-space is a place you cannot interact with, but is still visible. If this is bothering you, I suggest you ask for changes on MetaDecidim.
