### ISSUE TITLE
I can answer an unmoderated comment

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#559]
**Describe the bug**
Two problems appear with this bug.
When an comment has been left as an answer to the first comment on a proposal, I am shown two "reply" buttons under it. It is confusing as I don't which to choose.
Moreover If click on the top "reply" button, I can leave a reply to a comment that is still being moderated.

**To Reproduce**
1. Go to 'https://questions.steamroll.osp.cat/processes/corporis-possimus/f/61/'
2. Create a proposal
3. Leave a first comment
4. Reply to this first comment
5. See first error
6. Click on the top "reply" btn
7. See second error

**Expected behavior**
The "reply" btn to the comment still being moderated must be hidden

**Screenshots**

<img width="967" alt="Screenshot 2019-03-27 at 11 23 44" src="https://user-images.githubusercontent.com/32680605/55068846-079a4780-5083-11e9-9b80-0f73887fbc11.png">

<img width="954" alt="Screenshot 2019-03-27 at 11 24 23" src="https://user-images.githubusercontent.com/32680605/55068848-0832de00-5083-11e9-81ed-6765e57e165a.png">

<img width="1024" alt="Screenshot 2019-03-27 at 11 25 14" src="https://user-images.githubusercontent.com/32680605/55068847-0832de00-5083-11e9-81a9-b42a857d7028.png">

**Stacktrace**
If applicable, add the error stacktrace to help explain your problem.

**Extra data (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Device OS: [e.g. iOS8.1, Windows 10]
 - Browser: [e.g. Chrome, Firefox, Safari]
 - Decidim Version: [e.g. 0.10]
 - Decidim installation: [e.g. MetaDecidim]

**Additional context**

**Comment by armandfardeau** [comment]
Fixed in 06be522bd
