### ISSUE TITLE
Notification translation problem

### ISSUE THREAD

**Issue by antoinegaboriau1** [OpenSourcePolitics/decidim#563]
On the Club des utilisateurs organization (0.16), the notification for a closed meeting says "La réunion ### était close." when it should say instead "La réunion ### a été close." or "La réunion ### a été fermée."

See here:
![Opera Instantané_2019-03-28_094839_club decidim opensourcepolitics eu](https://user-images.githubusercontent.com/35924332/55143487-20683300-513f-11e9-90ab-48110adc80c0.png)

**Comment by lu-hamani** [comment]
@antoinegaboriau1 
Changes have been made as requested. They will be effective for next platforms boot and update.
