### ISSUE TITLE
Specific export MEL

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#564]
**Describe the bug**
MEL just did [map participation exercise](https://participation.lillemetropole.fr/processes/ousontelles/f/133/).
They need to export the data to put it on their open data portal. 
Unfortunately they discovered that the export file doesn't include nor the adress nor the geocoding data.

**Expected behavior**
We should include geocoding data + address in the export generated by Decidim.

**Screenshots**

**Extra data (please complete the following information):**
 - Decidim installation: MEL

**Additional context**
Ticket info https://support.opensourcepolitics.eu/scp/tickets.php?id=153
This could be posted as feature request also. Right now I'm handling this as a punctual export with the client as it's the first they ask us this kind of data.

**Comment by lu-hamani** [comment]
@virgile-dev 
I keep this one open but this feature is already defined in #506

**Comment by virgile-dev** [comment]
@lu-hamani Since the dev pipe is so crowded I think it's safer if we just ask Alain to make the specific export so that the client doesn't wait for it's data for too long. Do you agree ?

**Comment by lu-hamani** [comment]
> @lu-hamani Since the dev pipe is so crowded I think it's safer if we just ask Alain to make the specific export so that the client doesn't wait for it's data for too long. Do you agree ?

@virgile-dev 
If you think that the client really can't wait, it is the best course.

**Comment by virgile-dev** [comment]
Just was pinggued again by the client on this matter.
I need before the end of the week. @lu-hamani 
Can you make it happen ?

**Comment by lu-hamani** [comment]
@virgile-dev 
If it is that urgent, we'll do. Still let me check with the devs first. The obstacle is more about the Decidim version than the dev itself
