### ISSUE TITLE
Upload an avatar to display on official proposals in back office 

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#565]
**Is your feature request related to a problem? Please describe.**
Clearly not critical, but a nice improvement: one cannot change the default avatar for official proposals (and other contents) published from back office. 
<img width="383" alt="Capture d’écran 2019-03-29 à 12 52 34" src="https://user-images.githubusercontent.com/10398564/55230935-93e27100-5221-11e9-86a4-5b4434d7008e.png">

**Describe the solution you'd like**
It would be nice for the institution/organisation to have its logo, or any specific image. We did this change for BOSA (directly in the code?):
<img width="366" alt="Capture d’écran 2019-03-29 à 12 45 54" src="https://user-images.githubusercontent.com/10398564/55231125-005d7000-5222-11e9-9d7f-fd4acf280514.png">

I would be great to add this configuration on the Appearance Settings, where an admin can upload logos & favicon. 

**Describe alternatives you've considered**
I guess it would be ok to set the favicon as a default avatar. 

**Does this issue could impact on users private data?**
Nope

**Comment by lu-hamani** [comment]
@armandfardeau @moustachu 
I tagged it as "quick-win". What do you think ?
