### ISSUE TITLE
Badges on my public profil are not well leveled

### ISSUE THREAD

**Issue by leokante** [OpenSourcePolitics/decidim#567]
**Describe the bug**
When i take a look at my badges on my public profile, for some badges I observe that the differents steps to get from level 1 to level 2 are too high - it requires way too much implication for the user . It is too complicated to upgrade my badges and it makes this tool not really user-friendly. 

**To Reproduce**
1. Go to ' my public frofile' > Badges

**Expected behavior**
We may have to lower the levels of requirement to get new badges (level 1, level 2, level 3, etc...)

**Screenshots**
<img width="883" alt="Capture d’écran 2019-04-01 à 14 17 50" src="https://user-images.githubusercontent.com/43004803/55326759-cc37b880-5488-11e9-8f9f-aa0445f5e865.png">

**Extra data (please complete the following information):**
 - Device: [Desktop]
 - Device OS: [ iOS8.1]
 - Browser: [Safari]
 - Decidim Version: [0.16]
 - Decidim installation: [ Demo Open Source Politics]

**Additional context**

**Comment by lu-hamani** [comment]
@leokante @valentinchaput 
As per our conversation this morning, I think this should be reported to Metadecidim.
