### ISSUE TITLE
Geocoding doesn't work on Nouvelle Aquitaine preprod

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#571]
**Problem :**
Adresses are not geocoded and map doesn't display on preprod. 
Client says "L'adresse de préprod est bien déclarée sur here.com"

**Screenshots:**
![back-decidim](https://user-images.githubusercontent.com/11473995/55473824-e9e35a00-560f-11e9-9ff9-64536173ef5c.png)
![here-decidim](https://user-images.githubusercontent.com/11473995/55473828-eb148700-560f-11e9-9468-cf2e5de655f6.png)

Instances : [Nouvelle aquitaine's preprod](https://concertations-preprod.nouvelle-aquitaine.fr/processes/feuille/f/39/)

**Comment by lu-hamani** [comment]
@virgile-dev 
Bug wasn't coming from us. It has been corrected.
