### ISSUE TITLE
Can managed-users-who-did-not-validate-their-account-while-invitation-was-active sign up as standard user?

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#579]
**User Story**
Invitations sent to managed users -especially when they are imported as in Orsay- are only active for a specific time. During that period, you cannot sign up directly with the same email. What happens if one want to sign up regularly after its invitation link ended?

**Comment by lu-hamani** [comment]
@valentinchaput 
When an invitation is sent to a managed user, his email is reserved even if he doesn't complete his registration.
The solution is for the said managed user to click on re-send confirmation instruction or forgotten to password to go through with his registration regardless of the activation period of the invitation link.
