### ISSUE TITLE
"LOL" in emails description is still here

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#58]
<img width="1200" alt="capture d ecran 2018-03-15 a 14 13 54" src="https://user-images.githubusercontent.com/29771726/37465373-417ed7c8-285b-11e8-9bd6-4af8102c17db.png">

I don't know if it is in this repo or in `osp-app` but for instance, when you receive an email from https://osp-dcd-dev.herokuapp.com/ you get "LOL" in the email description

**Comment by moustachu** [comment]
Fixed in https://github.com/OpenSourcePolitics/osp-app/commit/ccd1c34a63bf0039c685af2eb2769d53dbd8308d

**Comment by juliesimon** [comment]
app/views/layouts/decidim/mailer.html.erb

<img width="1008" alt="capture d ecran 2018-03-23 a 17 06 46" src="https://user-images.githubusercontent.com/29771726/37840174-a46a1c96-2ebc-11e8-8c6f-228f438fec7b.png">
