### ISSUE TITLE
Val de Marne Boot

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#586]
## Client
**Version**
- [x] - 0.16

**Design**
- [x] - Platform URL = [participer.valdemarne.fr](url)
- [ ] - Platform email adress = participer@valdemarne.fr
- [x] - Primary color = #009FE0
- [x] - Secondary color = #e86a10
- [x] - Primary navbar ("Topbar") + mail header & footer = #575756
- [x] - Geocoding
- [x] - Matomo
- [ ] - Uptime Robot
- [ ] - Sentry

**Comment by moustachu** [comment]
### https://94.osp.cat/system/

![decidim local osp cat_ (3)](https://user-images.githubusercontent.com/464350/56144882-77756100-5fa3-11e9-8769-10ac712a788a.jpg)

![decidim local osp cat_processes_enim-reiciendis](https://user-images.githubusercontent.com/464350/56144895-81975f80-5fa3-11e9-85d7-f234ca6d3843.jpg)

**Comment by antoinegaboriau1** [comment]
**Design customization - Client wishes**

- Extended topbar to display a bigger logo (like participer.loire-atlantique.fr). 
- Color titlebar : white (#FFFFFF)

Also, and I know it's not a design customization but once you're at it... Client would like to see the "download open data files" footer link disappear. See #618

**Comment by antoinegaboriau1** [comment]
The footer is now broken on participer.valdemarne.fr, see image below.
- the logo is cut 
- the last word of the automatic text ("participative") should be on the second line 

![image](https://user-images.githubusercontent.com/35924332/57843299-479dc100-77ce-11e9-9715-a24762dbf1ef.png)

**Comment by antoinegaboriau1** [comment]
As you can see below the email topbar is grey ; VDM would like it to be white, like the platform topbar (#ffffff).

![image](https://user-images.githubusercontent.com/35924332/58232662-67873480-7d3a-11e9-85da-4a85d70119ff.png)

**Comment by antoinegaboriau1** [comment]
Hello @moustachu I think you missed the last comment about the email topbar ;) VDM would need it before June 3rd
