### ISSUE TITLE
Translation error on Proposals' filters

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#60]
As we decide how to order proposals, it should be "les plus récent**e**s"

<img width="251" alt="capture d ecran 2018-03-17 a 16 37 31" src="https://user-images.githubusercontent.com/10398564/37557217-bd6f13d2-2a01-11e8-8970-dc0517ed5895.png">

**Comment by juliesimon** [comment]
@valentinchaput changement ok sur crowdin + les osp-app
