### ISSUE TITLE
Data export CNDP

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#603]
We need an export from participons.debatpublic.fr 
Query : 
- All users that clicked on "Recevoir une newsletter sur l'actualité de la plateforme"

Data : 
- email

---
Since then this section of the signup page has been hidden as they use a different tool for emailing.

**Comment by moustachu** [comment]
```sql
SELECT * FROM public.decidim_users
WHERE newsletter_notifications_at IS NOT NULL
```
