### ISSUE TITLE
Map preview design broken

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#604]
**Problem**
Map preview has its text stuck to the side of its box. There was originally a space (margin or padding don"t know which) between them. 

[](https://dev.steamroll.osp.cat/processes/alias-accusantium/f/12/proposals/63/preview)

<img width="1437" alt="Screenshot 2019-04-16 at 17 04 37" src="https://user-images.githubusercontent.com/32680605/56221787-2e88df80-606b-11e9-9b6b-00f4b48b3981.png">

**Comment by moustachu** [comment]
Reverted part of https://github.com/OpenSourcePolitics/decidim/commit/ec1c0d5477e96f234a5d972c4a7735e43b782182#diff-7b6ab772811b7cd35faa45f8bf8aab7e

on `decidim-proposals/app/views/decidim/proposals/proposals/_proposal_preview.html.erb`

<img width="616" alt="Capture d’écran 2019-04-16 à 18 47 50" src="https://user-images.githubusercontent.com/464350/56228501-41ee7780-6078-11e9-9542-fd1c280bc8bf.png">
