### ISSUE TITLE
Translation errors #n

### ISSUE THREAD

**Issue by antoinegaboriau1** [OpenSourcePolitics/decidim#605]
On kery.osp.cat (the Val-de-Marne organization), a translation problem occurred.
In the "Survey" functionality, the title of a question says "Déclaration" when it should say "Titre" and "La description" instead of "Description" or "Question"

**Comment by lu-hamani** [comment]
@antoinegaboriau1 
Changes have been made as requested in crowdin. They should be effective for the future platforms on 0.16 version and on next update for those already in 0.16.
Hence I close the issue
