### ISSUE TITLE
Duplicate translations nfl translation sets for pngmdr

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#606]
Mostly I went over the notifications, but I think It's pretty close to finished.
(Listed a problem with a few keys here : https://github.com/OpenSourcePolitics/decidim-questions/issues/22)

To do:
Export translation sets : 1, 2 and 3

Import translations sets as : 
- 1 = 7
- 2 = 6
- 3 = 8

**Comment by moustachu** [comment]
### DONE ✅
