### ISSUE TITLE
SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by armandfardeau** [OpenSourcePolitics/decidim#608]
https://sentry.io/organizations/open-source-politics/issues/952273228/?project=1235134&referrer=github_plugin

```
SyntaxError: Unexpected token <
```

**Comment by lu-hamani** [comment]
Bug triggered when trying to unhide a reported proposal from here : 
https://dev.steamroll.osp.cat/admin/participatory_processes/alias-accusantium/moderations?hidden=true
Another bug is triggered with this action => #609
