### ISSUE TITLE
[BUMP 0.16 MEL] Content blocs are not displayed

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#613]
## Back-office config
<img width="1046" alt="Capture d’écran 2019-04-23 à 16 36 14" src="https://user-images.githubusercontent.com/11473995/56589676-03ac0780-65e6-11e9-82b6-f85cd638bb20.png">

## What appears in front-office
![screencapture-participation-lillemetropole-fr-2019-04-23-16_37_26](https://user-images.githubusercontent.com/11473995/56589715-13c3e700-65e6-11e9-8f78-c77eed131456.png)

Are missing:
- [x] Active processes
- [x] Active assemblies
- [x] Recent activities

**Comment by lu-hamani** [comment]
@virgile-dev 

Corrected through header snippet wizardry for the time being.
