### ISSUE TITLE
Proposal cards do not always display well on process page

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#614]
An example below:
<img width="619" alt="Capture d’écran 2019-04-23 à 16 43 01" src="https://user-images.githubusercontent.com/11473995/56590273-1a9f2980-65e7-11e9-9107-6a3d55b3197f.png">
Link : https://participation.lillemetropole.fr/processes/ousontelles

It appears that cards adapt to the proposal title and description length instead of available space.

**Comment by moustachu** [comment]
### fixed ✅ 

https://github.com/OpenSourcePolitics/osp-app/commit/b506d423c77a4eca67578cbefea92f9229f5db74#diff-d7cc677841fa29001b8d7e5c54ca81ff
