### ISSUE TITLE
[CNPD] Need to move `questions` to different tab

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#616]
Debate url : https://participons.debatpublic.fr/processes/nfl

Move from [f37 - questions & réponses](https://participons.debatpublic.fr/processes/nfl/f/37/) to [f38 - avis](https://participons.debatpublic.fr/processes/nfl/f/38/)
- n°6 : [Accès aux salles d'attente des gares qui vont vers Lyon](https://participons.debatpublic.fr/processes/nfl/f/37/questions/6)
- n°10 : [ Gare de Lyon Part Dieu / Gare de Lyon Saint-Exupéry](https://participons.debatpublic.fr/processes/nfl/f/37/questions/10)

Move from [f38 - avis](https://participons.debatpublic.fr/processes/nfl/f/38/) to [f37 - questions & réponses](https://participons.debatpublic.fr/processes/nfl/f/37/) : 
- n°8 : [Liaison Anse - Gare de Vaise(https://participons.debatpublic.fr/processes/nfl/f/38/questions/8)

Move from [f39 - contributions & cahiers d'acteurs](https://participons.debatpublic.fr/processes/nfl/f/39/) to [f38 - avis](https://participons.debatpublic.fr/processes/nfl/f/38/) : 
- n°14 : [Réouverture de la liaison ferroviaire Lyon Saint-Paul / Lozanne](https://participons.debatpublic.fr/processes/nfl/f/39/questions/14)
- n°36 [Réinvestir sur la liaison directe Neuville-Sur-Saône - La Part Dieu](https://participons.debatpublic.fr/processes/nfl/f/39/questions/36)

**Comment by virgile-dev** [comment]
@lu-hamani if we can do this BDD intervention at the same time we ship the missing notification it would be ideal.

**Comment by moustachu** [comment]
DOne
