### ISSUE TITLE
Updating position not working

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#624]
**Describe the problem**
As I want to modify my proposal's position right before publishing it, it actually keeps the original address I specified.

**Journey**
1. Go to 'https://demo.decidim.opensourcepolitics.eu/processes/debug/f/96/proposals/'
2. Create a proposal and add an address
3. Modify the position when on preview page

**Expected behaviour**
Position should update as I move the marker to a new location and save it.

**Screenshots**
<img width="603" alt="Screenshot 2019-04-29 at 09 15 14" src="https://user-images.githubusercontent.com/32680605/56881343-65de8f80-6a60-11e9-84c7-e55ae053b744.png">
<img width="708" alt="Screenshot 2019-04-29 at 09 15 04" src="https://user-images.githubusercontent.com/32680605/56881344-65de8f80-6a60-11e9-85fc-2ca6fba98c69.png">

**Comment by armandfardeau** [comment]
I have not been able to reproduce, could you investigate further?
![image](https://user-images.githubusercontent.com/20232956/56961085-12993980-6b53-11e9-92c8-b69aa05ca4b8.png)
