### ISSUE TITLE
Boot Decathlon Instance

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#625]
## Client

**Version**
- [x] - 0.16.0
- [x] - 0.16.1

**Design**
- [x] - Platform URL = vision-campus.decathlon.fr 
- [x] - Platform email adress = need to confirm address
- [x] - We are using our SMTP for the pilot
- [x] - Primary color = #0272B6
- [x] - Secondary color = #EA6923
- [x] - Primary navbar ("Topbar") + mail header & footer = #FFF
- [x] - Geocoding 
- [ ] - Matomo
- [ ] - Uptime Robot
- [x] - Sentry

**SSO**
- [x] - Employees SSO
- [ ] - Clients SSO (to confirm)

**Comment by virgile-dev** [comment]
@moustachu can you add the conference module on the Decathlon instance ? Thanks in advance 😊

**Comment by virgile-dev** [comment]
@moustachu can you increase file size upload limit to 25mb ? 
Not today as we'll be using the platform today the whole day.
But would be nice if done this week. 

Also what's the status on the SSO integration ?

**Comment by virgile-dev** [comment]
@moustachu to recap what remains to be done here : 
- [ ] Ship SSO on the production instance
- [ ] Add English language to instance, (french remains the default one)
- [ ] Increase file upload to 25mb
- [ ] Config platform email address, probably needs a little sync with Damien
- [ ] Port automatic translation from 0.11 to 0.16.

**Comment by virgile-dev** [comment]
@valentinchaput @moustachu  before launching (and I'm guessing it is soon) the platform needs a final polish. 
- [ ] email sent by the platform are still sent as OSP Agora
- [ ] SSO needs to be shipped and tested on production
- [ ] As the color picking functionnality is [not working properly](https://meta.decidim.org/processes/bug-report/f/210/proposals/14582) might be better to set the primary and secondary color directly in the code

Also for now registration is allowed only for existing users, I'm switching it to "all users can subscribe".

**Comment by valentinchaput** [comment]
@moustachu on a le mail : vision-campus@decathlon.net

**Comment by valentinchaput** [comment]
On mobile hamburger button + drop down menu for language selection are not visible. Sorry I can't upload an image on the mobile version of GitHub...

**Comment by virgile-dev** [comment]
@valentinchaput fixed it with the following. It will work for all the instances with a white nav bar. 
```
@media only screen and (max-width: 411px) {
.topbar__menu button{color:#000;}
.topbar__user__login a{color:#fff;}
.topbar__dropmenu>ul>li>a{color:#fff;}
}
```

**Comment by virgile-dev** [comment]
Just added the Google Analytics script to the platform. @moustachu @valentinchaput Did you end up modifying the legal terms ?

**Comment by virgile-dev** [comment]
- [ ] Change Surnom for "Pseudonyme"
- [ ] Add small help field on password, explaining the criterias to create a password that's gonna work
<img width="636" alt="Capture d’écran 2019-06-03 à 17 34 48" src="https://user-images.githubusercontent.com/11473995/58814385-ec6d2a80-8625-11e9-9a17-db3c3e10b841.png">

**Comment by valentinchaput** [comment]
@moustachu actually, we could add "Votre" before "surnom" (generic) or "pseudonyme" (specific to Decathlon) + deploy the help field on our standard osp-app for every platform! Muchas gracias

**Comment by moustachu** [comment]
> * [ ]  Change Surnom for "Pseudonyme"
> * [x]  Add small help field on password, explaining the criterias to create a password that's gonna work
> 
> <img alt="Capture d’écran 2019-06-03 à 17 34 48" width="636" src="https://user-images.githubusercontent.com/11473995/58814385-ec6d2a80-8625-11e9-9a17-db3c3e10b841.png">

### --> fixed with 9201aab674ce12adb8837495f8efc8c7beb958ce

**Comment by virgile-dev** [comment]
@moustachu can you activate the server task so that the app generates the participation curves in the statistics blocs.

<img width="1196" alt="Capture d’écran 2019-06-05 à 15 20 07" src="https://user-images.githubusercontent.com/11473995/58959430-64159380-87a5-11e9-9d01-a07ef15f99b2.png">

**Comment by valentinchaput** [comment]
As mentioned earlier on the chat, the text we display for translation should adapt to your language: if your are reading a French proposal, it should propose you to "Translate to English". And if you have translated a text from English to French, it should say "Go back to original version".
<img width="419" alt="Capture d’écran 2019-06-05 à 23 55 52" src="https://user-images.githubusercontent.com/10398564/58993350-95b24d00-87ed-11e9-903f-aca44bcf7308.png">
<img width="412" alt="Capture d’écran 2019-06-05 à 23 56 20" src="https://user-images.githubusercontent.com/10398564/58993352-95b24d00-87ed-11e9-87e8-55dd6c08c0ad.png">

**Comment by virgile-dev** [comment]
The platform uses the old footer. It was noticed by our friends from BCN.
<img width="1220" alt="Capture d’écran 2019-06-06 à 14 35 02" src="https://user-images.githubusercontent.com/11473995/59033229-815f6600-8868-11e9-8ad4-afc188daeddb.png">
