### ISSUE TITLE
Can't export proposals

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#627]
https://sentry.io/organizations/open-source-politics/issues/1005054033/?project=1324058&query=is%3Aunresolved

https://sentry.io/organizations/open-source-politics/issues/997776868/?project=1324058&query=is%3Aunresolved

Errors appeared with the exports enhancements.

**Comment by armandfardeau** [comment]
Has the database migration done properly? This like this is the issue.

**Comment by moustachu** [comment]
Yep --> missing migration on server ... my bad ...

### Fixed & deployed

https://github.com/OpenSourcePolitics/osp-app/commit/e7f877a089cdce3123fc6ebf8a9f579692dc9571
