### ISSUE TITLE
Assemblies homepage dropdow menu behaving weirdly

### ISSUE THREAD

**Issue by antoinegaboriau1** [OpenSourcePolitics/decidim#631]
**Describe the bug**
On the Assemblies homepage, the Assemblies' list has a dropdown menu that allows users to select a specific type of Assembly they want to join. It seems like there are three separate problems with this.
1. **Conception.** This functionality looks weird because it says "help" right next to the selection dropdown menu, which in my opinion does not make any sense.
2. **Design.** The "help" text is not a button but we can click on it and launch the dropdown menu.
3. **Translation.** There is a translation error, since it says "help" instead of "aide" (even if I wonder what is the purpose of a "help" text here. 

**To Reproduce**
1. Go to https://participez.nancy.fr/assemblies, scroll down to the "8 Assemblées" part.
2. Click on 'help' on the right of the screen.
3. See error

**Expected behavior**
I don't think there is need for a "help" text, even less for a text that is clickable. Keeping only the dropdown menu should be sufficient.

**Screenshots**
![image](https://user-images.githubusercontent.com/35924332/57141360-4c1fae00-6dba-11e9-9687-ab820af9346f.png)

**Extra data:**
 - Device: Desktop
 - Device OS: Ubuntu 18.04
 - Browser: Opera
 - Decidim Version: 0.16
 - Decidim installation: Nancy

**Comment by armandfardeau** [comment]
Hi @antoinegaboriau1. Thanks for your contribution! 

We suggest updating the translation to "Montrer : " as the original text is "Show:" in English. This should solve 1 and 3.

Regarding 2, I don't think it's really an issue as you can click on both the filter and the text.

Keep me in touch.
