### ISSUE TITLE
Up / Down / Neutral votes

### ISSUE THREAD

**Issue by armandfardeau** [OpenSourcePolitics/decidim#637]
**Describe the bug**
When voting using Up / Down / Neutral buttons, votes are correctly saved but are displayed as the last button used on the page for all proposals. When reloading the page, the votes are correctly displayed.

**To Reproduce**
1. Activate and Go to pproposals page
2. Click on up, then on neutral, then on down.
3. See error

**Expected behavior**
The vote should be displayed differently depending on the button used.

**Screenshots**
![](https://media.giphy.com/media/kbRcXgSzhURg2gHdx1/giphy.gif)

**Comment by moustachu** [comment]
There was a conflict between the restrictions on vote per user and the AJAX request/callback used to update the proposals on screen after a weighted vote. 

Might be a strong warning on the technical debt of the Weighted vote feature.

**Comment by armandfardeau** [comment]
@moustachu Yes, Let's talk about it Friday.

**Comment by leokante** [comment]
Voting on a proposal does not have effect on the votes of the other proposals anymore. But an issue remain when voting on a proposal. Here a two screens to explain in : 

**Before voting :** 
![before voting](https://user-images.githubusercontent.com/43004803/58543934-addc0800-8200-11e9-867b-e6c79d1f8da4.PNG)

**After voting :**
![after voting](https://user-images.githubusercontent.com/43004803/58543939-b0d6f880-8200-11e9-8b21-377a9c654ce1.PNG)

**Comment by leokante** [comment]
This issue should remain open
