### ISSUE TITLE
Can't find a user in /admin/officializations using the search bar

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#639]
**Describe the bug**
The /admin/officializations user list is not showing an account I just registered. I tried with and without confirming my account by clicking on the link sent via email.

Account tested I with : demo.cndp.opensourcepolitics.eu/profiles/test-vir/

**Expected behavior**
I was expecting to find the user in the list by inputing test-vir in the search bar

**Extra data (please complete the following information):**
 - Decidim installation: I tested this as it is an issue raised by Nouvelle Aquitaine (concertations.nouvelle-aquitaine.fr) with the user i.loulmet. I found the same issue with test-vir on a newer version

Ticket link : https://support.opensourcepolitics.eu/scp/tickets.php?id=196

**Comment by virgile-dev** [comment]
Is this being looked into @moustachu ?

**Comment by armandfardeau** [comment]
I'm sorry @virgile-dev But this cannot be reproduced.
Please check me when you have some time.

![image](https://user-images.githubusercontent.com/20232956/58113860-c8a5ef80-7bf6-11e9-85dc-646674239093.png)

**Comment by virgile-dev** [comment]
Let's check it out together when you get to the office today.

**Comment by virgile-dev** [comment]
Solved in 0.16. Hence closing.
