### ISSUE TITLE
Stange vanishing of an assembly on https://participer.ecollectivitesvendee.fr/

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#649]
**Describe the bug**

"Commune des Epesses" assembly still appears on the homepage, but "il y a un probleme avec votre serveur" and the assembly has vanished from the BO (which is not possible to do for an admin)... 

<img width="992" alt="Capture d’écran 2019-05-16 à 15 32 23" src="https://user-images.githubusercontent.com/10398564/57857636-d5d66f00-77ef-11e9-9cd6-dbce9df097b5.png">

![Capture](https://user-images.githubusercontent.com/10398564/57857584-bb03fa80-77ef-11e9-8db2-0c409911fa6c.JPG)

![Capture JPG1](https://user-images.githubusercontent.com/10398564/57857685-ef77b680-77ef-11e9-8b33-836389bac42f.JPG)

Do you find any explanations in the logs? 

**Additional context**
Critical: they have a presentation tonight...

**Comment by moustachu** [comment]
@valentinchaput The 2 missing Assemblies where set with parent "as themself" so it was messing up with the access.

--> I put them back as first level assemblies so you need to restore the correct hierarchy
