### ISSUE TITLE
Server error when clicking on meeting in Conference module

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#651]
**Describe the bug**
When clicking on a meeting from the conference module the app crashes.
[Here](https://vision-campus.decathlon.fr/conferences/waouh-days/f/5/meetings/4) is where in happenned to me.

Found a [log](https://sentry.io/organizations/open-source-politics/issues/1029986617/?project=1460480&query=is%3Aunresolved) on Sentry that attached to it.

@moustachu does it looks like an easy fix that could be ready for monday ? Otherwise I'll find a way "pour contourner". 

Thanks in advance for your reply.

**Comment by armandfardeau** [comment]
HI @virgile-dev and thanks for your contribution. 

However, this error cannot be reproduced locally nor online.

![image](https://user-images.githubusercontent.com/20232956/58105712-3c400080-7be7-11e9-9652-b3f942005163.png)
https://vision-campus.decathlon.fr/conferences/waouh-days

**Comment by virgile-dev** [comment]
Let's check it out together when you get to the office today.

**Comment by virgile-dev** [comment]
@armandfardeau It's when clicking on : https://vision-campus.decathlon.fr/conferences/waouh-days/f/5/meetings/4
