### ISSUE TITLE
Angers - Bug on the Following number of a user

### ISSUE THREAD

**Issue by antoinegaboriau1** [OpenSourcePolitics/decidim#653]
**Describe the bug**
The Following number displayed on the left does not correspond with what is displayed in the "Following" detailed section of the public profile. It seems the public profile does not display any of accounts followed by a user. 

**To Reproduce**
1. Go to 'ecrivons.angers.fr'
2. Click on any user
3. Scroll down to see which accounts s/he follows
4. See error: the corresponding accounts are not displayed

**Expected behavior**
I expect either the corresponding followed accounts to be displayed. It seems to be resolved on 0.16 instances (Val-de-Marne and Club display Following results correctly)  

**Screenshots**
![image](https://user-images.githubusercontent.com/35924332/58010975-abd3c400-7af1-11e9-886d-e4e68c47f22c.png)

It seems to be the same on Loire-atlantique 
![image](https://user-images.githubusercontent.com/35924332/58011282-34eafb00-7af2-11e9-8594-0e2f9305f24d.png)

and Roubaix
![image](https://user-images.githubusercontent.com/35924332/58011928-9790c680-7af3-11e9-9421-363c23177abc.png)

**Comment by armandfardeau** [comment]
Hi @antoinegaboriau1 and thank you for your contribution. It seems there is a problem that is fixed in version 0.16-stable, as this problem is supposed to be updated in the coming days and since it is not a blocking bug, I suggest that we do not fix this problem and continue to update normally.
