### ISSUE TITLE
Double snipet

### ISSUE THREAD

**Issue by leokante** [OpenSourcePolitics/decidim#665]
**Describe the bug**
Double snipet in the back office

**To Reproduce**
1. Go to Back office
2. Click on "apparences

**Expected behavior**
only one snipet

**Screenshots**
![image](https://user-images.githubusercontent.com/43004803/58331059-92f04900-7e38-11e9-87b8-73909c3f326f.png)

**Stacktrace**
If applicable, add the error stacktrace to help explain your problem.

**Extra data (please complete the following information):**
 - Device: [Desktop]
 - Device OS: [ Windows 10]
 - Browser: [ Safari]
 - Decidim Version: [0.10]
 - Decidim installation: [Romainville]

**Additional context**
I think there use to be some customized CSS on Romainville. It might have had an incidence.

**Comment by moustachu** [comment]
Fixed with https://github.com/OpenSourcePolitics/decidim/commit/00f428ece38f76de4cb6e23e0c0ddffc02a84768
