### ISSUE TITLE
Missing meeting title in meeting export

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#67]
Currently : 
<img width="482" alt="capture d ecran 2018-03-23 a 14 37 22" src="https://user-images.githubusercontent.com/29771726/37832043-be6f39b0-2ea7-11e8-8a70-0477f8ec3402.png">

There should be more data (at least name, better if the date also) instead of "tableau 1"

**Comment by armandfardeau** [comment]
@juliesimon Is this issue still pertinent or may we close it ?

**Comment by juliesimon** [comment]
@armandfardeau yes, you still get this when exporting the list of registrations of a meeting: 
<img width="784" alt="capture d ecran 2018-08-27 a 14 14 41" src="https://user-images.githubusercontent.com/29771726/44659193-a2ef0f80-aa03-11e8-9dd9-369acd4e2fbf.png">

Instead of "registrations-27_08_2018-51270" you should have the meeting's title
