### ISSUE TITLE
Make "envelopp icon" great again

### ISSUE THREAD

**Issue by leokante** [OpenSourcePolitics/decidim#671]
**Describe the bug**
the envelopp icon can not be seen on 

**To Reproduce**
1. Go to  the home page of https://participer.numerique-en-commun.fr/

**Expected behavior**
Would it be possible to see the envelopp in grey ? #e6e6e6

**Screenshots**
![image](https://user-images.githubusercontent.com/43004803/58462516-5ec7a180-8132-11e9-9dca-67e4d6554525.png)

**Stacktrace**
If applicable, add the error stacktrace to help explain your problem.

**Extra data (please complete the following information):**
 - Device: [Desktop]
 - Device OS: [ Windows 10]
 - Browser: [Safari]
 - Decidim Version: [e.g. 0.16]
 - Decidim installation: [Numérique en commun]

**Additional context**
It is not an emergency

**Comment by armandfardeau** [comment]
@leokante Resolved.
