### ISSUE TITLE
Showing user data in exports (of proposals, meetings, etc)

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#68]
So far, nothing about the user appears in the export of a proposal (and for all exports)

<img width="1223" alt="capture d ecran 2018-03-23 a 17 30 52" src="https://user-images.githubusercontent.com/29771726/37841392-f79ebcfc-2ebf-11e8-9e29-1deecb308ead.png">

Angers needs it since the administrators of the platform sends the xls to the service which in fine contacts the users regarding their proposals.

Should we include user data, in terms of privacy ?
If so, what could we include ? Name, username, email ?

**Comment by armandfardeau** [comment]
What does CGV says regarding theses points?

I suggest we provide all informations the user agreed to give.

**Comment by juliesimon** [comment]
I don't think it really depends on the TOS but on how this information is used.
What was decided for some clients' osp-app is to add `author.id` and `published_date` to proposal export (https://github.com/OpenSourcePolitics/osp-app/commit/1722bf4b9d22b27e07bc60e4390582ec75432ffe) but since we never got any answer from the decidim team on this subject (https://github.com/decidim/decidim/issues/3682), we did not backport this dev to our decidim repo
