### ISSUE TITLE
Proposal exports don't work on participez.nanterre.fr

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#680]
@moustachu Check out the sentry error for more details : https://sentry.io/organizations/open-source-politics/issues/1048371350/?project=1316909&query=is%3Aunresolved&statsPeriod=14d

**Comment by armandfardeau** [comment]
@moustachu IMHO you need to update migration and run db:migrate because I can't reproduce locally.
![image](https://user-images.githubusercontent.com/20232956/59184450-71000180-8b6e-11e9-8580-333bcdbf48f5.png)

**Comment by virgile-dev** [comment]
Thanks for the analysis. Here is the task related #701

**Comment by moustachu** [comment]
### @virgile-dev Fixed ✅
