### ISSUE TITLE
Unreadable color+text combination button on newsletter pop-up 

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#684]
This one is for @armandfardeau 

**To Reproduce**
1. Go to https://participer.ecollectivitesvendee.fr/ (or several of our platforms, as we fixed it recently on Loiret's platform)
2. Try to sign up without checking newsletter
3. See error

**Expected behavior**
This box should be transparent with border+text in dark grey. 

**Screenshots**
<img width="620" alt="Capture d’écran 2019-06-05 à 16 28 55" src="https://user-images.githubusercontent.com/10398564/58964564-6bda3580-87af-11e9-956a-abd2c3489334.png">

**Comment by armandfardeau** [comment]
@valentinchaput I'm closing since this is not present in the current decidim version

![Uploading image.png…]()

@moustachu ping!

**Comment by valentinchaput** [comment]
OK thanks.
How to process a short fix/update of our most sensitive platforms in production?
