### ISSUE TITLE
Vulnerability fix backport

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#688]
@moustachu @armandfardeau the Decidim fixed an important vulnerability. 
They sent me the code that we need to backport to our fork.
It seems that we should do it asap

Here is it : https://github.com/decidim/decidim/pull/5147/files

**Comment by moustachu** [comment]
**Warning ! This could break display on Notification / Cards & Emails so this need to be tested !!** 

Also, a good look at the discussions on https://github.com/decidim/decidim/pull/5037 & https://github.com/decidim/decidim/pull/5146 seems **mandatory**
