### ISSUE TITLE
in-depth statistics on homepage

### ISSUE THREAD

**Issue by leokante** [OpenSourcePolitics/decidim#689]
**Describe the bug**
The evolution of the statistics is not displayed anymore on the homepage

**To Reproduce**
1. Go to homepage
2. Scroll down to the bottom of the page
3. See error

**Expected behavior**
I expect the statistics to be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/43004803/59032784-604a4580-8867-11e9-83ff-92ba21160eb4.png)

![image](https://user-images.githubusercontent.com/43004803/59032811-748e4280-8867-11e9-828e-ff020c4d9387.png)

**Extra data (please complete the following information):**
 - Device: [Desktop]
 - Device OS: [Windows 10]
 - Browser: [Firefox]
 - Decidim Version: [0.16]
 - Decidim installation: [https://demo.decidim.opensourcepolitics.eu/

**Additional context**
Is it just a CSS issue ?

**Comment by leokante** [comment]
@armandfardeau this issue remains unsolved

**Comment by armandfardeau** [comment]
@leokante We will check

**Comment by leokante** [comment]
I think, this issue remains unsolved.
