### ISSUE TITLE
Small SSO login button is confusing for users

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#694]
Client says that with the DE button it is not clear enough that it's to connect with the Decathlon SSO.
<img width="401" alt="Capture d’écran 2019-06-07 à 16 57 14" src="https://user-images.githubusercontent.com/11473995/59113997-8692e280-8946-11e9-8a08-94b8ae972d46.png">

Can we put : 
<img width="423" alt="Capture d’écran 2019-06-07 à 17 07 48" src="https://user-images.githubusercontent.com/11473995/59114055-9e6a6680-8946-11e9-9fd2-fc30096196de.png">

**Comment by virgile-dev** [comment]
If we could have the term-customizer module on Decathlon I could change "ou" for "Se connecter avec Decathlon" and problem solved !
@moustachu

**Comment by virgile-dev** [comment]
My solution to use the term customizer doesn't work currently because blocks are inverted in the login_modal vs the login page

Login modal
<img width="492" alt="Capture d’écran 2019-06-09 à 10 11 18" src="https://user-images.githubusercontent.com/11473995/59156652-3da27180-8a9f-11e9-96f1-c3fd0e17b11f.png">

Login page
<img width="474" alt="Capture d’écran 2019-06-09 à 10 10 49" src="https://user-images.githubusercontent.com/11473995/59156654-42672580-8a9f-11e9-96aa-05cb8a2500f3.png">

@moustachu any chance we have the full SSO login button on the login modal ?

**Comment by armandfardeau** [comment]
Done !
![image](https://user-images.githubusercontent.com/20232956/59189929-b8d95580-8b7b-11e9-82cd-5e3eef331028.png)
