### ISSUE TITLE
Run the task for open data download on our platforms

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#706]
As it now appears on every footer, we need to had this in the process when booting or updating a new platform...

At least all the recently updated ones
- [ ] - https://codefor.fr/
- [ ] - https://vision-campus.decathlon.fr/
- [ ] - https://atelierdevosidees.loiret.fr/
- [ ] - https://participer.numerique-en-commun.fr/
- [ ] - https://www.budget-participatif-romainville.fr/
- [ ] - https://budgetparticipatif.ville-roubaix.fr/
- [ ] - https://ecrivons.angers.fr/

**Comment by valentinchaput** [comment]
Little up @moustachu before your technical meeting this afternoon

**Comment by virgile-dev** [comment]
@valentinchaput I'm hidding it via header snippet in the mean-time. 
here is the code `.footer-nav li:nth-child(6){display: none;}`
You can replace 6 by the rank the link is in the footer.
