### ISSUE TITLE
Improve Decathlon SSO workflow 

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#707]
## First connexion error message (Priority : High)
I've tested with 2 new users, after inputing their data on the Decathlon SSO page they are redirected to the complete your profile page with this error message. `Impossible de vous authentifier à partir de Decathlon car un autre compte utilisateur utilise la même adresse email`
I made sure that they never connected before so the error message shouldn't be there.
![error-message](https://user-images.githubusercontent.com/11473995/59337503-06cb9600-8d01-11e9-85ee-b3d41a600cc0.png)
Moreover the user can click on `Compléter votre profil` and proceed to finish completing their profile.
![completer-compte](https://user-images.githubusercontent.com/11473995/59338364-8312a900-8d02-11e9-9530-1cb4d4678dc0.png)

##  When clicking on the button "Complete your profile page" redirect to "Accept our updated terms and condition page"
Is this just wording or is this page really about accepting updated terms and conditions ? Is this step obligatory ? I've added translation on the term and conditions so it's just about accepting the terms and conditions.
![termsandcontitions](https://user-images.githubusercontent.com/11473995/59338807-5e6b0100-8d03-11e9-8c37-7f517275ba1f.png)

## People registering with SSO do not have a way to opt in to receive the platform's newsletter
- We could use the "Complete your profile" page or the "Accept the terms and conditions" to have people subscribing to the newsletter. By adding this block on the page (and the modal that goes with it).
<img width="550" alt="Capture d’écran 2019-06-12 à 11 16 47" src="https://user-images.githubusercontent.com/11473995/59339029-b86bc680-8d03-11e9-8f9b-4af845e03214.png">

**Comment by valentinchaput** [comment]
_Just adding it must be the same with Emmaüs SSO._

**Comment by moustachu** [comment]
### Resolution track _(for developpers)_
_First these behavior needs to be checked with the internal OAuth system between 2 Decidim platform_

- [ ] Mount 2 local Decidim platform (we need 2 organizations with 2 distinct `host:port`)
- [ ] Configure the first one as an OAuth Provider
- [ ] Configure the second with an Omniauth connector (`omniauth-decidim`) set on the first platform
- [ ] Tests the mentionned behaviors 
- [ ] If reproductible --> Analyse the cause and **create new issues if needed**
- [ ] If not reproductible --> check the code of the [Decathlon connector](https://github.com/OpenSourcePolitics/osp-app/blob/alt/decathlon/lib/omniauth/strategies/decathlon.rb) to analyse the diff with [`omniauth-decidim` connector](https://github.com/decidim/omniauth-decidim/blob/master/lib/omniauth/strategies/decidim.rb)
- [ ] Report here your analysis 

_thanks ✨_

**Comment by moustachu** [comment]
@virgile-dev 

- [ ] **1.** The error message could come from bug bypassed on #709 , related to the image profile. This error could cause a fallback to "Complete your profile page".
- [ ] **2.** We didn't reproduce any wrong behavior with the ToS acceptation. 
- [ ] **3.** Indeed. We could add the Newsletter settings in the ToS acceptation page --> New issue

**Comment by virgile-dev** [comment]
Hi @armandfardeau and @moustachu 
Thanks for the diagnosis and fixes. 

Regarding the ToS acceptation page, I'd like to be sure. All the wording on the page in French and English is about accepting **updated** ToS. Is this just bad wording or something in the SSO process that thinks the platform had an update in the ToS ?
![Uploading 59338807-5e6b0100-8d03-11e9-8c37-7f517275ba1f.png…]()

If it's just a translation issue I'll change the keys in crowdin.

Here is the issue for the newsletter optin on accept the ToS page https://github.com/OpenSourcePolitics/decidim/issues/711

**Comment by moustachu** [comment]
@virgile-dev 

Indeed ! the error message doesn't make sense in this case 
![image](https://user-images.githubusercontent.com/464350/59414253-730dce80-8dc1-11e9-9fef-6ec53bf2c442.png)

**--> To be fixed**
