### ISSUE TITLE
URGENT trad update for Roubaix

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#713]
Roubaix is launching today a participatory budgeting vote with only one project to select within a group of 10. While updating steps, we discover current voting instructions are irrelevant:

<img width="1235" alt="Capture d’écran 2019-06-14 à 14 40 10" src="https://user-images.githubusercontent.com/10398564/59509941-bc8a1680-8eb2-11e9-9ef8-bb3974f9eea4.png">

The client suggests to remplace with the following:
"**Vous décidez**
Faîtes votre choix puis confirmer le. Vous devez choisir [x] projet(s)." 

I think it is generic enough to support future processes. 

_Btw: congrats for the other improvements on this feature!_

**Comment by armandfardeau** [comment]
![image](https://user-images.githubusercontent.com/20232956/59515545-a8004b00-8ebf-11e9-874a-f9b80f461ae6.png)
Shame !

**Comment by armandfardeau** [comment]
@valentinchaput I've choosed : "A quels projets pensez-vous que nous devrions allouer un budget ? Choisissez %{minimum_project} projets et validez votre vote." wich is clearer IMHO.

**Comment by valentinchaput** [comment]
"confirmer votre vote" might be better than "valider" as it appears on the button

**Comment by valentinchaput** [comment]
let's make it simpler: "A quels projets devrions-nous allouer un budget ? Choisissez %{minimum_project} projets et confirmez votre vote."
