### ISSUE TITLE
When selected, related processes cannot return to blank option on assemblies

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#718]
**Describe the bug**
When selected, related processes cannot return to blank option on assemblies

**To Reproduce**
... well, you saw it @armandfardeau on Generation's platform before hiding it ;)
+ backoffice: behavior appears when you click on one related process and then want to remove it -the only option is to select another one but you cannot have none.

**Expected behavior**
A blank option as in many other selective fields on Decidim.

**Comment by virgile-dev** [comment]
You just need to hold command or control and click and the selection will disappear

**Comment by valentinchaput** [comment]
Right. We should add a text to explain it directly on the admin panel (if we don't develop the blank field)
