### ISSUE TITLE
[Decidim-Budget] Adapt vote per project wording

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#719]
**Describe the bug**
@valentinchaput has raised a point about wording not being correct for the instructions when the vote is set up per project.

In admin config is as follow : 
<img width="773" alt="Capture d’écran 2019-06-19 à 11 38 10" src="https://user-images.githubusercontent.com/11473995/59754657-cfbc2e00-9286-11e9-8c66-40c13d04145a.png">
Meaning the user can only select one project and then confirm its vote. If he selects more than one he is prompted the following modal. 
<img width="1116" alt="Capture d’écran 2019-06-19 à 11 39 18" src="https://user-images.githubusercontent.com/11473995/59755169-bcf62900-9287-11e9-9637-89ce46fe6adb.png">
We can agree here that the "Nombre de projet total" is set up as a maximum.

Yet the instructions for the user are confusing as they referer to a min.
<img width="1100" alt="Capture d’écran 2019-06-19 à 11 40 58" src="https://user-images.githubusercontent.com/11473995/59754842-35a8b580-9287-11e9-87a3-0458c607bb9b.png">

**To Reproduce**
1. Go to https://participez.nanterre.fr/processes/budget-participatif-2019/f/63/projects

**Expected behavior**
Adapt wording like it was done for [Roubaix](https://budgetparticipatif.ville-roubaix.fr/processes/pcp2019/f/10/projects) "Vous devez choisir [Nombre de projets maximum] projet(s)"

**Decidim instance**
--> https://participez.nanterre.fr/processes/budget-participatif-2019/f/63/projects

**Comment by virgile-dev** [comment]
Referencing this here https://github.com/OpenSourcePolitics/decidim/issues/713
Also @valentinchaput as Armand says in #713 it seems that it's something we can do on crowdin.

**Comment by armandfardeau** [comment]
@virgile-dev Is this something we should still work on? Or is it solved by #713 ?
