### ISSUE TITLE
User invitation : Forbidden characters in user name

### ISSUE THREAD

**Issue by moustachu** [OpenSourcePolitics/decidim#723]
**Describe the bug**
Forbidden characters (like `(`) are not detected when you invite a user from the admin panel.

**To Reproduce**
1. When you invite a user form the admin panel (eg: like a new organization admin), forbidden characters (like `(`) doesn't raise any errors.  
2. When the user click on the invitation link, it leads to the "Complete your profile".
3. In that case, the `name` field is hidden (this value was provided on invitation).
4. When the user complete his profile and validate the form, it leads to a blank page without validating the completed profile.

**Expected behavior**
Forbidden characters should be notified on the admin panel when creating the invitation  
**AND / OR**  
When validating the "Complete your profile" form, the error should take the user back the form with the `name` field displayed with an error

**Stacktrace**
```
{
   "method":"PUT",
   "path":"/users/invitation",
   "format":"html",
   "controller":"Decidim::Devise::InvitationsController",
   "action":"update",
   "status":422,
   "error":"ActiveRecord::RecordInvalid: La validation a échoué : Nom d'utilisateur n'est pas valide",
   "duration":118.8,
   "view":0.0,
   "db":4.24,
   "remote_ip":null,
   "params":{
      "_method":"put",
      "authenticity_token":"[FILTERED]",
      "user":{
         "invitation_token":"[FILTERED]",
         "nickname":"alain_osp",
         "password":"[FILTERED]",
         "password_confirmation":"[FILTERED]",
         "tos_agreement":"1",
         "newsletter_notifications":"1"
      },
      "commit":"",
      "invite_redirect":"/admin/"
   },
   "user_id":null,
   "organization_id":null,
   "referer":null
}
```

**Comment by armandfardeau** [comment]
@moustachu I've shipped a PR to BCN, will cherrypick 🍒 when merged!
