### ISSUE TITLE
Cannot submit amendements

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#725]
**Describe the bug**
When logged as user, I cannot submit my amendment.

**To Reproduce**
1. Go to https://agora.generation-s.fr/assemblies/notreprojetpourparis/f/25/proposals/552
2. Click on 'Modifier la proposition'
3. Introduce an change
4. Click on 'Envoyez votre amendement'
5. See error

**Expected behavior**
I should be able to send my amendment.

**Screenshots**
Here is the error message I'm prompted.
<img width="1240" alt="Capture d’écran 2019-06-25 à 17 51 33" src="https://user-images.githubusercontent.com/11473995/60113375-ee806000-9771-11e9-8e80-d332030e1de4.png">

**Extra data (please complete the following information):**
 - Decidim Version: [0.16]
 - Decidim installation: [Agora Generation.s.](https://agora.generation-s.fr/uploads/decidim/organization/logo/1/medium_Agora_Logo_small.png)

**Additional context**
This is an urgent demand, consultation is over in 5 days and almost nobody was able to participate.

**Comment by moustachu** [comment]
@virgile-dev Should be fixed with a hard patch on the production server : 
https://agora.generation-s.fr/assemblies/notreprojetpourparis/f/25/proposals/552

But we need to finalize this fix.
Hints : 

replace
```ruby 
recipient.notification_types
```
by 
```ruby 
recipient.try(:notification_types)
```

in 
`decidim-core/app/services/decidim/email_notification_generator.rb`  
and  
`decidim-core/app/services/decidim/notification_generator.rb`

**Comment by moustachu** [comment]
Another note : 

There was also a bug on the `EtiquetteValidator` : 
When importing a "Participatory Text" (Proposals), section titles are not subject to validations (... it seems so). If a section title is for example "less than 15 characters", it will not raised an error on import *BUT* it will raise an error when an emendation / amendment on this section is created with an unchanged title (still "less than 15 characters").

- [ ] Add validations on Participatory Text import
- [ ] Errors on amendments creation should be more explicit (NO general error message)

**Comment by armandfardeau** [comment]
> @virgile-dev Should be fixed with a hard patch on the production server :
> https://agora.generation-s.fr/assemblies/notreprojetpourparis/f/25/proposals/552
> 
> But we need to finalize this fix.
> Hints :
> 
> replace
> 
> ```ruby
> recipient.notification_types
> ```
> 
> by
> 
> ```ruby
> recipient.try(:notification_types)
> ```
> 
> in
> `decidim-core/app/services/decidim/email_notification_generator.rb`
> and
> `decidim-core/app/services/decidim/notification_generator.rb`

I don't get how the `notification_types` can be nil since it defaults to "all"
In schema.rb:
 `t.string "notification_types", default: "all", null: false`
