### ISSUE TITLE
[Angers 0.16] Some users do not appear neither in search results nor in conversation panel

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#726]
**Describe the bug**
Angers need to contact project holders on its prticipatory budgeting. Their platform was migrated to 0.16 last week. Several bugs appear on some (but not all) users:
- Some users are not clickable: Annick Causse on proposal 992 https://ecrivons.angers.fr/processes/BP2019/f/138/proposals/992 or Adeline de Ferron on proposal 994 & 995 https://ecrivons.angers.fr/processes/BP2019/f/138/proposals/994.
- They do not appear in the search engine. Actually, we have another issue: only 29 out of 7000+ users appear in the search engine, and I have some doubts about some of them being bots of some kind (see image below).

**To Reproduce**
1. Go to https://ecrivons.angers.fr admin panel
2. Navigate to Participations > Budget participatif 2019 > Je dépose mon idée > order them by id > go to page 14 and have a look at proposals 992, 994, 995 (or directly use the links above)
3. Click on user name 

**Expected behavior**
Active user name on proposal, as for exemple with proposal 988 https://ecrivons.angers.fr/processes/BP2019/f/138/proposals/988

**Screenshots**
![Screenshot_2019-06-27 Ecrivons Angers](https://user-images.githubusercontent.com/10398564/60259516-b72bc380-98d7-11e9-8a2a-5e602a036335.png)

**Additional context**
Not deadly urgent but still a priority as Angers' team must contact the users before July (next week).

**Comment by moustachu** [comment]
@valentinchaput This was fixed with *2* actions :  
- Rebuild the index for users as `SearchableResource` (because of some silent errors at the 0.16 migration time)
- Restore all the empty or blank users `nickname` to the default based on their full name

eg : "Firstname Lastname" --> "firstname_lastname"
