### ISSUE TITLE
"Key" : unable to understand what it means

### ISSUE THREAD

**Issue by paulinebessoles** [OpenSourcePolitics/decidim#731]
**Is your feature request related to a problem? Please describe.**
When I try to create a state of progress in the "accountability component", I don't understand what the "key" input field means. 

**Describe the solution you'd like**
I'd like it to be clearer and understand what it means

**Describe alternatives you've considered**
May be a short information below the input field

**Additional context**
https://decidim.etalab.opensourcepolitics.eu/admin/participatory_processes/modules-decidim/components/4/manage/statuses/1/edit

![image](https://user-images.githubusercontent.com/52420208/60451403-41538f00-9c2c-11e9-9690-1448bcfa9e5f.png)

**Does this issue could impact on users private data?**
No

**Comment by armandfardeau** [comment]
@OpenSourcePolitics/product Could you help @paulinebessoles on this?

We should work on some placeholders to enhance ux.
