### ISSUE TITLE
[UX / mobile] The menu is hard to find on mobile

### ISSUE THREAD

**Issue by leokante** [OpenSourcePolitics/decidim#740]
**Describe the bug**
When using the mobile, it is not obvious nor instinc that the whole menu can be displayed when using the black arrow on the right of the screen. 

**To Reproduce**

**Expected behavior**
Would be possible to put the black arrow more visible ? Would a colourful animation be a good idea ? 

**Screenshots**
![image](https://user-images.githubusercontent.com/43004803/60681803-e5d60b00-9e90-11e9-90ff-2cd035bf860f.png)

**Stacktrace**
If applicable, add the error stacktrace to help explain your problem.

**Extra data (please complete the following information):**
 - Device: [Samsung S5 plus]
 - Device OS: [Android]
 - Browser: [Google]
 - Decidim Version: [0.16]
 - Decidim installation: [Emmaüs-solidarité]

**Additional context**
Does it have to be discuss wtih the BCN crew ?

**Comment by virgile-dev** [comment]
> Does it have to be discuss wtih the BCN crew ?
@leokante yes :)
Another one is once you are on proposal you can't really go back to the list unless you click on another tab.
