### ISSUE TITLE
Boot Kulturr Connect

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#746]
**Version**
- [ ] - 0.16

**Design**
- [ ] - Platform URL = http://Samenwerkplatform.cultuurconnect.be 
- [ ] - Platform email adress = klaar.leroy@cultuurconnect.be
- [ ] - Primary color = #ffdb09
- [ ] - Secondary color = #d70096
- [ ] - Primary navbar ("Topbar") + mail header & footer = #FFF 
- [ ] - Geocoding
- [ ] - Matomo
- [ ] - Uptime Robot
- [ ] - Sentry

**Comment by leokante** [comment]
## Cultuurconnect

**Version**
- [ ] - 0.16
- Default language : Dutch
- Please make translations available

Informations for **Design** still pending

**Comment by leokante** [comment]
Nouvelles informations @moustachu 

- Url :  http://Samenwerkplatform.cultuurconnect.be
- Email : klaar.leroy@cultuurconnect.be  (changes might occur later) 

The graphic chart is displayed in this document : 
[Huisstijlgids_cultuurconnect_def.pdf](https://github.com/OpenSourcePolitics/decidim/files/3393302/Huisstijlgids_cultuurconnect_def.pdf)

It looks like they have different primary colors + different secondary colors... Which doesn't help us. 
But there is no emergency. I can check this point with them directly when i'll see them on the 17th. 
        **Primary colours:** 
o   yellow: C0 M10 Y100 K0
R255 G219 B9
HTML #ffdb09
PMS 109
RAL 1021
o   black: C0 M00 Y0 K100
R0 G0 B0
HTML #000000
PMS black
RAL 9004
o   green: C100 M10 Y100 K5
R0 G133 B69
HTML #008545
PMS 347
o   blue: C100 M0 Y5 K5
R0 G151 B209
HTML #0097d1
PMS cyan
        **Secundary colours** :
            C0 M100 Y0 K0 R215 G0 B150 HTML #d70096 PMS magenta
            C0 M100 Y100 K0 R215 G16 B28 HTML #d7101c PMS 185
            C68 M0 Y100 K0 R122 G175 B63 HTML #7aaf3f PMS 361


**The priority remains to make the translation feature available.**
