### ISSUE TITLE
Fixing the filter in Assemblies index (front office)

### ISSUE THREAD

**Issue by leokante** [OpenSourcePolitics/decidim#752]
**Describe the bug**
When entering the index of all the published assemblies (https://crowbar.osp.cat/assemblies), the filter on the top right of the screen & below the navbar works randomly. 
The whole menu can be displayed but depending on what category you click on, some options have no effect and other do. 
Actually, the filter only works some times, and then it's blocked. If you want to click on another category, you're forced to refresh the page and start again. 

![Group 25](https://user-images.githubusercontent.com/52420208/62051409-9d9dd480-b213-11e9-88ab-cb8424e4485e.png)

**To Reproduce**
1. Go to Assemblies
2. Click on the filter menu right to "Laten zien"
3. Scroll down to display the whole list and click on categories randomly. 

**Expected behavior**
Two expectations : 
- Would it be possible to display in the menu ONLY the categories of assemblies that are currently used by the admin on the platform ? (for example : If I have 3 assemblies : One referred to as "work group" and two referred to as "Other" ; I expect that the menu would only dispay two choices : Work Group & Other). 
- If this first behaviour is not possible, would it be possible to mask the menu in order not to complexify the UX ? 

**Extra data (please complete the following information):**
 - Device: [Desktop]
 - Device OS: [Windows 10]
 - Browser: [ Firefox]
 - Decidim Version: [0.16]
 - Decidim installation: [Cultuurconnect (Crowbar.osp.cat)]

**Additional context**
I think we'd never spotted this issue because it is the first OSP' client having such an ambitious use of assemblies. 

Please note that until this issue isn't fixed, the client won't be able to proceed to the setting up of its platform. The arborescence decided by the client will be different whether this (cool) feature is available or not.

**Comment by virgile-dev** [comment]
Hi @leokante 
The filter is not operating because you didn't choose an assembly type.
No data, no filter result. 

I found one filter that works and shows that it works see capture : 
<img width="1132" alt="Capture d’écran 2019-07-22 à 09 27 48" src="https://user-images.githubusercontent.com/11473995/61614038-14126380-ac63-11e9-8720-97709f4b57b3.png">

**Comment by leokante** [comment]
@moustachu @armandfardeau ; @paulinebessoles has just edited my previous issue. You can see with her directly today in case you need further informations.
As i told you, this issue is quite important for the configuration of one of our clients' platform.
May the force be with us
