### ISSUE TITLE
Admins of a concertation don't have access to the dashboard

### ISSUE THREAD

**Issue by antoinegaboriau1** [OpenSourcePolitics/decidim#754]
On participer.numerique-en-commun.fr, people got invited as administrators of a specific participatory process (see below) :

![image](https://user-images.githubusercontent.com/35924332/61640511-c1a26880-ac9d-11e9-9945-d28cb91ab21e.png)

but the invite wasn't send, and the specific people that got invited cannot access the admin dashboard anyway (see below) : 

![image](https://user-images.githubusercontent.com/35924332/61640596-e39beb00-ac9d-11e9-9da5-f9fb6cbd8854.png)

thanks!

**Comment by moustachu** [comment]
This comes from a confusion on the user account, the user mentionned has 2 account with the same name.
