### ISSUE TITLE
Comment export doesn't include visibility column

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#755]
**Describe the bug**
CNDP needs to exports comment for a synthesis. Currently the export doesn't include a column that states if the comment was hidden or published. 

**Expected behavior**
There should be a column in the comment export indicating the comment status.
The status we have on CNDP for comments are : 
- A traiter
- Visible
- Non visible

**Comment by moustachu** [comment]
Done with 0b0fcacda4bd0e2f1c8cb7f5e7e26e1dc537feaa
