### ISSUE TITLE
[CNDP] Process admin cannot invite private users

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#756]
**Describe the bug**
They do not see the tab.

@paulinebessoles can you check if this is the case in 0.18 and in 0.16 ? Thanks !

**Comment by paulinebessoles** [comment]
On both 0.16 and 0.18 version, process admin can't see the "Private users" tab. 

**0.16** 
(demo.decidim.opensourcepolitics.eu)

![image](https://user-images.githubusercontent.com/52420208/61781669-0eed1a00-ae05-11e9-8ee8-8237d24594c5.png)

**0.19-dev** 
(doc.hitobito.osp.cat)

![image](https://user-images.githubusercontent.com/52420208/61782227-fc271500-ae05-11e9-858c-07478d9fd2a3.png)
