### ISSUE TITLE
To have graphQL queries examples 

### ISSUE THREAD

**Issue by paulinebessoles** [OpenSourcePolitics/decidim#757]
## OSP

I'd like to :
- [ ] - Have examples of graphQL queries
- [ ] - List all the assemblies and participatory processes a user is member of
- [ ] - List the proposals, meetings etc. of those assemblies and participatory processes

**Comment by leokante** [comment]
A conversation has been opened on MetaDecidim : https://meta.decidim.org/processes/supportforum/f/705/proposals/14715
