### ISSUE TITLE
Photos don't show up in the "conseilcitoyen.ema.osp.cat" platform

### ISSUE THREAD

**Issue by paulinebessoles** [OpenSourcePolitics/decidim#763]
**Describe the bug**
In the "conseilcitoyen.ema.osp.cat" platform, I can download photos on the admin panel but they don't show up on the platform. 

**To Reproduce**
1. Go to 'Paramètres>Page d'accueil"
2. Click on 'Image principale (hero)'
3. Download an image and update the platform
4. See error on the front office

**Screenshots**
![image](https://user-images.githubusercontent.com/52420208/62555295-f522ec80-b872-11e9-9c87-8556411b3b35.png)
![image](https://user-images.githubusercontent.com/52420208/62555312-feac5480-b872-11e9-8ad1-fbb4cc5146ef.png)

**Extra data (please complete the following information):**
 - Device: [Desktop]
 - Device OS: [Windows 10]
 - Browser: [Chrome]
 - Decidim Version: [0.16]
 - Decidim installation: [Rillieux-la-Pape]

**Comment by moustachu** [comment]
## FIXED ✅
