### ISSUE TITLE
Remove the process header compression to low definition 

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#765]
**Describe the bug**
With the 0.16 design, a process banner seems to be automatically compressed to 1000 px width while the section might be wider on laptop/desktop screens. Banners appear in low definition on good quality/retina screens. We used to have better definition in 0.12. Can we improve this?

**To Reproduce**
1. Go to a process page (https://participer.loire-atlantique.fr/processes/portdelaturballe/f/83/debates/18)
2. Inspect sizes with your browser.

**Comment by valentinchaput** [comment]
@armandfardeau if you are still looking for something to check this afternoon ;)

**Comment by valentinchaput** [comment]
@armandfardeau I know it's not an emergency, but did you have a look at this one?

**Comment by virgile-dev** [comment]
If present on lastest version of Decidim. Please report on https://github.com/decidim/decidim/
