### ISSUE TITLE
Evaluation for a PR to BCN>Helsinki on our budget last improvements

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#769]
**Describe the solution you'd like**
We developed improvements on Budget voting phase recently: vote per projects, status bar progression while selecting projects, email confirmation, green layer and updated wording after voting... Developments were made on our 0.16 version. 

Helsinki would like to use our features for their own budget (starting October 1st, with a testing phase in September) and could fund an updated PR from OSP to Decidim master. But we need to announce a budget evaluation very quick.  

**Additional context**
Katja's messages explaining the context and tight schedule:

1. _I am very curious about usability improvements that you have made to the budgeting component.  I saw a conversation on MetaDecidim and just took a quick look at you Github repository. I wonder if you have the improved budjeting component installed somewhere so I could just look at the UI you created?  We cannot install them directly due to likely incompliance with our UI and CSS customizations._
2. _I especially appreciate making the vote confirmation more clear for users. I understood that I can choose from the admin panel weather voting is limited to (A) certain amount of money or (B) certain number of projects. Would it be possible to bring this into the main Decidim version or turn this into a module (Ruby gem) that we could more easily integrate with our system? How much time and costs would this mean? I am afraid there is not much time actually, because our budgeting phase starts 1st of October and we have reserved September for testing._  
3. _We still have some development funds left for this year and are willing to finance this PR to Decidim master. This is on the condition that the expenses are reasonable and this can be done fast enough, so that we can integrate it to our own system and still test during September. If you can, please make as an offer and I will discuss it with my manager immediately._ 
4. _Sorry to keep posting you, but have had change to look at this yet? I suppose that getting something to the Decidim core takes significant time and then we would still need to wait for next release (I do not want to use the pre-release Github version in production). One option could be that you first ship the budgeting features for us as module (Ruby gem) so that we integrate it quickly to our version? Then we can additionally sponsor integration with Decidim core. There might be a bit double work here but could help the schedule._

**Comment by moustachu** [comment]
@valentinchaput For the whole feature pack : 
> vote per projects, status bar progression while selecting projects, email confirmation, green layer and updated wording after voting...

If we planned for : 
- put the code in an external module (gem)
- make it compatible with decidim/decidim#master (+ 0.18-stable)
- add the corresponding tests coverage 

We estimate this task at 15 days. 

But we need to make sure that the development can be done for the beginning of September .
