### ISSUE TITLE
Comments not working on debates and blogs

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#77]
As a user I can't leave a comment on the features that have been added by the Decidim team since OSP developed upstream moderation.
Here is the error message I get when I try to leave a comment : 
```
Completed 500 Internal Server Error in 104ms (ActiveRecord: 8.0ms)
NoMethodError (undefined method `comments_upstream_moderation_enabled' for #<#<Class:0x00007fe94d87a620>:0x00007fe94da5c470>)
```

Maybe it's because upstream moderation has to be set for the new features "debates" and "blogs"

**Comment by virgile-dev** [comment]
Damn that sucks. Any comment @ludivinecp ?

**Comment by ludivinecp** [comment]
On a modifié l'engine comments pour la moderation, donc dès qu'un nouveau module inclura les commentaires il faudra apporter les modifications nécessaires.
