### ISSUE TITLE
Add automatic translation to debates

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#779]
# Context

First version of automatic translation could be applied to the following elements
- proposal title and description
<img width="759" alt="Capture d’écran 2019-09-02 à 10 08 23" src="https://user-images.githubusercontent.com/11473995/64100344-b5fd9380-cd6b-11e9-9842-9b611db1290d.png">
<img width="1117" alt="Capture d’écran 2019-09-02 à 10 25 02" src="https://user-images.githubusercontent.com/11473995/64100529-0ffe5900-cd6c-11e9-923f-6698eb6e3002.png">
<img width="1122" alt="Capture d’écran 2019-09-02 à 10 25 16" src="https://user-images.githubusercontent.com/11473995/64100571-24425600-cd6c-11e9-8677-f1dc5a322248.png">
- debate title and description
<img width="818" alt="Capture d’écran 2019-09-02 à 10 15 01" src="https://user-images.githubusercontent.com/11473995/64100328-ad0cc200-cd6b-11e9-83f1-9961286526af.png">
<img width="723" alt="Capture d’écran 2019-09-02 à 10 24 15" src="https://user-images.githubusercontent.com/11473995/64100454-e80ef580-cd6b-11e9-8bc2-d8792b30f0d0.png">
- comment
<img width="847" alt="Capture d’écran 2019-09-02 à 10 09 56" src="https://user-images.githubusercontent.com/11473995/64100306-a54d1d80-cd6b-11e9-857b-6d42056e032f.png">

# Spec
In the context of the 0.18 upgrade we need to : 
- [ ] add asterix and associated toggle that displays on hover that says "Automatic translation by Deepl"
<img width="541" alt="Capture d’écran 2019-09-02 à 10 25 16" src="https://user-images.githubusercontent.com/11473995/64100861-d1b56980-cd6c-11e9-9be8-72a2d8393638.png">
- [ ] extend the automatic translation to the debate feature

## Decision log
- Move to the new implementation / design (the one done in 0.16)
<img width="733" alt="Capture d’écran 2019-09-02 à 10 32 11" src="https://user-images.githubusercontent.com/11473995/64100942-01fd0800-cd6d-11e9-8fe5-a660a968b0f0.png">

- Make it a module --> postponed to near future

- Branch to use to develop : https://github.com/OpenSourcePolitics/decidim/tree/0.18-merge

**Comment by moustachu** [comment]
@virgile-dev Automatic translation is in the pipe for the next modules we might code. 

@armandfardeau **TLDR version**
- the automatic translation was present on more element in the first version
- this need to be done with the latest UX we made for 0.16 (the one you develop) 

Thanks
