### ISSUE TITLE
Server Error when adding a new category in the Conferences module

### ISSUE THREAD

**Issue by paulinebessoles** [OpenSourcePolitics/decidim#807]
**Describe the bug**
When I try to add a category in the Conference module on [participer.numerique-en-commun.fr](https://participer.numerique-en-commun.fr), a server error page appears. 

**To Reproduce**
1. Go to the admin panel of https://participer.numerique-en-commun.fr
2. Click on Conferences, then select a conference
3. Try to add a category (with or without selecting a color)

**Screenshots**
![image](https://user-images.githubusercontent.com/52420208/64958088-98155000-d88e-11e9-914b-d614bef1fdc6.png)

**Extra data (please complete the following information):**
 - Device: [Desktop]
 - Device OS: [Windows 10]
 - Browser: [Chrome]
 - Decidim Version: [0.16]
 - Decidim installation: [https://participer.numerique-en-commun.fr]

**Comment by moustachu** [comment]
@paulinebessoles FIXED ! ✅ 

( missing migrations 😛)
