### ISSUE TITLE
Bad punctuation display in mails

### ISSUE THREAD

**Issue by leokante** [OpenSourcePolitics/decidim#863]
**Describe the bug**
Characters like " **'** " are not displayed properly in mail notifications. 

**To Reproduce**
See the screenshots below -->  "constell'actions" can not be read properly

**Expected behavior**

**Screenshots**

![Capture d’écran 2019-12-11 à 11 29 10-1](https://user-images.githubusercontent.com/43004803/70647678-cdd99300-1c49-11ea-9abc-bef74dd89556.png)

**Stacktrace**

**Extra data (please complete the following information):**
 - Device: [Desktop]
 - Device OS: [iOS8.1]
 - Browser: [Firefox]
 - Decidim Version: [e.g. 0.10]
 - Decidim installation: [noussommes.36k.osp.cat]

**Comment by leokante** [comment]
@Quentinchampenois before closing definitely this issue, could you make sure the bug fix is implemented into next update for every platforms ?

**Comment by leokante** [comment]
Just for your information @paulinebessoles , the bug is still on air for some platforms such as https://demo.decidim.opensourcepolitics.eu/

Maybe it will be fixed after next update ?

Best,

**Comment by paulinebessoles** [comment]
Hi @leokante do you know if this has been fixed & merged ?

**Comment by leokante** [comment]
I guess you wanted to tag @armandfardeau or @virgile-dev ?
