### ISSUE TITLE
hashtag doesn't have the right behaviour when used in a meeting

### ISSUE THREAD

**Issue by leokante** [OpenSourcePolitics/decidim#864]
**Describe the bug**
The hashtag doesn't have the right behaviour when used in a meeting.
**#Noussommes** might be replaced by **gid://development-app/Decidim::Hashtag/24/NousSommes** 

**To Reproduce**
1. Go to [](https://noussommes.36k.osp.cat/processes/constell-actions/f/109/)
2. Click on any meeting
3. See error

**Expected behavior**
I would line "#NousSommes" to be displayed properly.

**Screenshots**
![Capture d’écran 2019-12-10 à 22 41 41-2](https://user-images.githubusercontent.com/43004803/70648215-e4ccb500-1c4a-11ea-874d-1ed3478983c0.png)
![Capture d’écran 2019-12-10 à 22 15 09-2](https://user-images.githubusercontent.com/43004803/70648218-e5fde200-1c4a-11ea-8207-648e85840a80.png)

**Extra data (please complete the following information):**
 - Device: [Desktop]
 - Device OS: [ iOS8.1]
 - Browser: [Firefox, ]
 - Decidim Version: [e.g. 0.18]
 - Decidim installation: [Noussommes.36k.osp.cat]

**Additional context**
The name of the client is "#noussommes" and not "Nous Sommes
That is why it is so important to make possible the use of the hashtag.

**Comment by leokante** [comment]
@Quentinchampenois do you know if it has been fixed ?

**Comment by virgile-dev** [comment]
I'm wondering if this is version related.
Did you check if the same happens on staging.decidim.codegram.com ?
