### ISSUE TITLE
Translate button doesn't always work on lists

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#92]
Browser: IE 11
Locale: NL

Issue: The tranlslation button doesn't work on the proposal list when viewing in nl and on IE11. When clicking nothing happens. 

This affects the proposal list on the [feature page](https://monopinion.belgium.be/processes/stopfakenews/f/81/?locale=nl) and on the [presentation page](https://monopinion.belgium.be/processes/stopfakenews?locale=nl).

I found this website to emulate IE 11 : https://www.browserling.com/browse/win/10/ie/11/http%3A%2F%2Fmonopinion.belgium.be%2F

**Comment by hgueguen** [comment]
En fait le probleme arrivait a chaque fois que quelqu'un mettait plusieurs points d'interrogation a la suite, j'ai pu corriger ça grace a un ajout de parametre dans la requete. 🥇 

Petite question @virgile-dev : je push sur la branche sur laquelle j'avais bossé ? [osp-app/alt/bosa-with-trad-auto](https://github.com/OpenSourcePolitics/osp-app/tree/alt/bosa-with-trad-auto) ou mieux vaut le faire directement sur une autre ?

**Comment by juliesimon** [comment]
@hgueguen Hello Harry, c'est plus @moustachu qui peut te répondre la dessus, j'ai été absente une semaine et donc je ne sais pas quelle branche est déployée pour Bosa.

Par ailleurs je me dis que si la trad-auto dans le repo `decidim` est sur une branche à part à partir d'une version en 0.10-stable, ce n'est pas le cas sur le repo `osp-app`, où les devs de la trad auto ne sont que dans les branches pour Bosa. @hgueguen ça te prendrait du temps de créer sur `osp-app` une branche `0.10-stable-trad-auto` à partir d'une `0.10-stable` et d'y reporter les vues spécifiques à la trad auto ?

**Comment by hgueguen** [comment]
resolved and pushed on osp-app#alt/bosa

**Comment by virgile-dev** [comment]
Hey @hgueguen , 
Just tested your code on https://monopinion.bosa.opensourcepolitics.eu/processes/stopfakenews/f/81/?locale=fr using Browserstack instanciating a IE11 in Windows 10 the issue is still here. Some how when navigating in nl and trying to translate from the index it doesn't work. Checked the console it just says error without any further details :(

**Comment by armandfardeau** [comment]
@virgile-dev  Is this issue still pertinent or may we close it ?
