### ISSUE TITLE
Hidden (moderated) proposal show up in process page

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#93]
This can be replicated here (need to login as admin): https://monopinion.bosa.opensourcepolitics.eu/processes/stopfakenews-old?locale=nl

As you can see proposal are displayed in the "Presentation" page but if you go to the feature page you'll see that [no proposals](https://monopinion.bosa.opensourcepolitics.eu/processes/stopfakenews-old/f/76/?locale=nl) are displayed there.

**Comment by juliesimon** [comment]
Le problème se retrouve sur la branche `0.10-stable`
On signale une proposition : pour ça, il faut cliquer sur le petit drapeau puis aller dans le tableau de bord admin > processus > moderation a posteriori > on modère la proposition en cliquant sur l'oeil barré
Ensuite la proposition a bien disparu de l'index des proposition mais elle apparaît toujours sur la page de présentation du processus, dans l'aperçu des propositions (https://deploy-decidim.herokuapp.com/processes/animi-velit "Les propositions") et quand on clique dessus on obtient une erreur

**Comment by juliesimon** [comment]
@moustachu 
https://pompano.osp.cat/processes/nouveau/f/59/ : il ne reste plus que 3 propositions, les autres ont été modérées (https://pompano.osp.cat/admin/participatory_processes/nouveau/moderations?hidden=true&moderation_type=downstream)
https://pompano.osp.cat/processes/nouveau : les propositions modérées s'affichent dans la section "4 propositions aléatoires"
