### ISSUE TITLE
Add a spinner for when the translation request is being sent

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#95]
Hey guys, 
Andrés the software architect of Decidim made an interesting feedback on the translation UX.
We should add a little spinner that signals that the translation is being done so that the user doesnt click multiple times on the button.

What do you think @juliesimon @hgueguen ?

**Comment by armandfardeau** [comment]
@virgile-dev Is this issue still pertinent or may we close it ?
