### ISSUE TITLE
Enhance mutli-tenancy capabilities by adding configuration options at the organization level

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#96]
# This is a Feature Proposal

#### :tophat: Description
We started experimenting with the multi-tenancy mode with the Belgium Federal State and a couple demands since then. It's particularly compelling for higher level administration that hold a service provider role towards lower level institutions.

We think that adding a couple configuration options on the organization could make the multi-tenancy feature more usable. Here are a few ideas we had, so per organization one could enable or disable:
- Social and SAML logins with different configuration
- Sender's email address used for the platform's notification
- Basic scss variable for styling

Feel free to extend the list.

**Comment by armandfardeau** [comment]
@juliesimon  Is this issue still pertinent or may we close it ?

**Comment by juliesimon** [comment]
Yes, but this needs to be discussed with @virgile-dev and @moustachu

**Comment by virgile-dev** [comment]
We might tackle this with @moustachu before the end of the year.
