### ISSUE TITLE
On Nancy platform, impossible to access to notifications

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#98]
https://nancy.opensourcepolitics.eu/notifications shows error
![capture d ecran 2018-05-25 a 11 14 00](https://user-images.githubusercontent.com/29771726/40536540-cd829b2c-600c-11e8-84f0-2177beb8bf72.png)

**Comment by moustachu** [comment]
There are problems with the Feature -> Component migrations ... 

I tried : 
```
Notification.where(decidim_resource_type: "Decidim::Feature").update_all(decidim_resource_type: "Decidim::Component")
    Notification.where(event_class: "Decidim::FeaturePublishedEvent").update_all(event_class: "Decidim::ComponentPublishedEvent")
    Notification.where(event_name: "decidim.events.features.feature_published").update_all(event_name: "decidim.events.components.component_published")
    
```

but there are still corrupted data so I did truncate the notifications table :P
